import Link from "next/link";
import { ArrowUpRight, BadgeIndianRupee, CircleDollarSign, CreditCard, Landmark, ReceiptIndianRupee } from "lucide-react";
import { requireRole } from "@/lib/auth/authorization";
import { updatePayoutRequest } from "./actions";

export default async function AdminFinancePage(){
  const {supabase}=await requireRole(["admin"]);
  const [{data:attempts},{data:orders},{data:purchases},{data:payouts}]=await Promise.all([
    supabase.from("payment_attempts").select("id,user_id,target_type,target_id,amount,currency,gateway_order_id,gateway_payment_id,status,created_at").order("created_at",{ascending:false}).limit(100),
    supabase.from("marketplace_orders").select("id,provider_id,amount,creator_earning,platform_margin,status,payout_status").order("created_at",{ascending:false}),
    supabase.from("resume_purchases").select("id,user_id,template_id,amount,purchased_at").order("purchased_at",{ascending:false}).limit(100),
    supabase.from("creator_payout_requests").select("id,creator_id,amount,status,payment_reference,admin_note,requested_at,creator_payout_items(order_id,creator_earning)").order("requested_at",{ascending:false}).limit(100),
  ]);
  const ids=new Set<string>(); attempts?.forEach(item=>ids.add(item.user_id)); orders?.forEach(item=>{if(item.provider_id)ids.add(item.provider_id)}); payouts?.forEach(item=>ids.add(item.creator_id));
  const {data:people}=ids.size?await supabase.from("users").select("id,full_name,email").in("id",[...ids]):{data:[]};
  const names=new Map((people??[]).map(person=>[person.id,person.full_name||person.email]));
  const captured=(attempts??[]).filter(item=>item.status==="captured");
  const collections=captured.reduce((sum,item)=>sum+Number(item.amount),0);
  const marketplaceMargin=(orders??[]).filter(order=>!["pending_payment","cancelled","refunded"].includes(order.status)).reduce((sum,order)=>sum+Number(order.platform_margin??0),0);
  const resumeRevenue=(purchases??[]).reduce((sum,item)=>sum+Number(item.amount),0);
  const payoutDue=(payouts??[]).filter(item=>["requested","approved"].includes(item.status)).reduce((sum,item)=>sum+Number(item.amount),0);
  const paidOut=(payouts??[]).filter(item=>item.status==="paid").reduce((sum,item)=>sum+Number(item.amount),0);
  return <div className="space-y-8"><section className="relative overflow-hidden rounded-[2.5rem] bg-zinc-950 p-9 text-white"><div className="absolute -right-16 -top-20 h-72 w-72 rounded-full border border-white/10"/><ReceiptIndianRupee/><h1 className="mt-5 text-4xl font-bold tracking-tight">Finance & Payouts</h1><p className="mt-3 max-w-3xl text-zinc-400">Verified collections, JobiVerse revenue, creator liabilities and payout processing from live transaction records.</p></section>
  <section className="rounded-3xl border border-zinc-200 bg-white p-6"><div className="flex flex-col justify-between gap-5 lg:flex-row lg:items-center"><div><h2 className="text-xl font-bold">Finance exports</h2><p className="mt-1 text-sm text-zinc-500">Download live reconciliation data as Excel-compatible CSV files.</p></div><div className="flex flex-wrap gap-2">{[["payments","Payments"],["margins","Margins"],["refunds","Refunds"],["payouts","Payouts"]].map(([type,label])=><a key={type} href={`/api/admin/finance/export?type=${type}`} download className="inline-flex cursor-pointer items-center gap-2 rounded-xl border border-zinc-200 bg-zinc-50 px-4 py-3 text-xs font-semibold transition hover:bg-zinc-950 hover:text-white">{label} CSV <ArrowUpRight size={13}/></a>)}</div></div></section>\n  <section className="grid gap-4 md:grid-cols-2 xl:grid-cols-5"><Metric icon={CreditCard} label="Captured collections" value={money(collections)}/><Metric icon={CircleDollarSign} label="Marketplace margin" value={money(marketplaceMargin)}/><Metric icon={BadgeIndianRupee} label="CV revenue" value={money(resumeRevenue)}/><Metric icon={Landmark} label="Payouts due" value={money(payoutDue)}/><Metric icon={Landmark} label="Paid to creators" value={money(paidOut)}/></section>
  <section className="rounded-3xl border border-zinc-200 bg-white p-7"><h2 className="text-2xl font-bold">Creator payout queue</h2><p className="mt-1 text-sm text-zinc-500">Approve, reject or record a completed bank payout with its transaction reference.</p><div className="mt-6 space-y-4">{payouts?.length?payouts.map(request=><article key={request.id} className="rounded-2xl border border-zinc-100 bg-zinc-50 p-5"><div className="flex flex-wrap items-start justify-between gap-4"><div><p className="font-bold">{names.get(request.creator_id)??"Creator"}</p><p className="mt-1 text-xs text-zinc-500">{money(request.amount)} | {request.creator_payout_items?.length??0} orders | {new Date(request.requested_at).toLocaleDateString("en-IN")}</p></div><span className="rounded-full bg-white px-3 py-1 text-xs font-bold uppercase">{request.status}</span></div>{!["paid","rejected"].includes(request.status)&&<form action={updatePayoutRequest} className="mt-4 grid gap-3 lg:grid-cols-[1fr_1fr_auto]"><input type="hidden" name="requestId" value={request.id}/><input name="adminNote" placeholder="Admin note (optional)" className="h-11 rounded-xl border border-zinc-200 bg-white px-4 text-sm"/><input name="paymentReference" placeholder="Transaction reference (required when paid)" className="h-11 rounded-xl border border-zinc-200 bg-white px-4 text-sm"/><div className="flex gap-2"><button name="status" value="approved" className="cursor-pointer rounded-xl border border-zinc-200 bg-white px-4 text-xs font-semibold">Approve</button><button name="status" value="paid" className="cursor-pointer rounded-xl bg-emerald-600 px-4 text-xs font-semibold text-white">Mark paid</button><button name="status" value="rejected" className="cursor-pointer rounded-xl bg-red-50 px-4 text-xs font-semibold text-red-700">Reject</button></div></form>}{request.payment_reference&&<p className="mt-3 text-xs text-zinc-500">Reference: {request.payment_reference}</p>}</article>):<Empty text="No payout requests yet."/>}</div></section>
  <section className="rounded-3xl border border-zinc-200 bg-white p-7"><h2 className="text-2xl font-bold">Razorpay transaction ledger</h2><div className="mt-6 overflow-x-auto"><table className="w-full min-w-[850px] text-left text-sm"><thead><tr className="border-b text-xs uppercase tracking-wider text-zinc-400"><th className="pb-3">Customer</th><th className="pb-3">Type</th><th className="pb-3">Amount</th><th className="pb-3">Status</th><th className="pb-3">Gateway payment</th><th className="pb-3">Date</th><th className="pb-3 text-right">Receipt</th></tr></thead><tbody>{attempts?.map(item=><tr key={item.id} className="border-b border-zinc-100"><td className="py-4 font-medium">{names.get(item.user_id)??"User"}</td><td className="py-4">{item.target_type.replaceAll("_"," ")}</td><td className="py-4 font-semibold">{money(item.amount)}</td><td className="py-4 uppercase text-zinc-500">{item.status}</td><td className="py-4 font-mono text-xs text-zinc-500">{item.gateway_payment_id??"Awaiting payment"}</td><td className="py-4 text-zinc-500">{new Date(item.created_at).toLocaleString("en-IN")}</td><td className="py-4 text-right">{["captured","refunded"].includes(item.status)?<Link href={`/payments/receipts/${item.id}`} className="inline-flex items-center gap-1 rounded-lg bg-zinc-950 px-3 py-2 text-xs font-semibold text-white">Receipt <ArrowUpRight size={12}/></Link>:<span className="text-xs text-zinc-400">Unavailable</span>}</td></tr>)}</tbody></table>{!attempts?.length&&<Empty text="No payment attempts yet."/>}</div></section></div>;
}

function money(value:number|string|null){return new Intl.NumberFormat("en-IN",{style:"currency",currency:"INR",maximumFractionDigits:0}).format(Number(value)||0)}
function Metric({icon:Icon,label,value}:{icon:React.ElementType;label:string;value:string}){return <article className="rounded-3xl border border-zinc-200 bg-white p-6"><Icon className="text-zinc-400"/><p className="mt-5 text-sm text-zinc-500">{label}</p><p className="mt-2 text-2xl font-bold">{value}</p></article>}
function Empty({text}:{text:string}){return <p className="rounded-2xl border border-dashed border-zinc-200 p-8 text-center text-sm text-zinc-500">{text}</p>}





