import Link from "next/link";
import { PageSectionIndex } from "@/components/common/page-section-index";
import { ArrowRight, BadgeCheck, BookOpen, BriefcaseBusiness, ChartNoAxesCombined, CircleDollarSign, FileText, GraduationCap, HandCoins, MessagesSquare, Palette, ShieldCheck, Sparkles, Star, Upload, UsersRound, Video } from "lucide-react";

const opportunities = [
  { icon: Palette, title: "Sell CV Templates", text: "Upload original, editable CV designs and earn from every paid download." },
  { icon: FileText, title: "Resume Services", text: "Offer resume writing, review, cover-letter and LinkedIn optimization services." },
  { icon: MessagesSquare, title: "Career Counselling", text: "Guide students and professionals through career decisions and transitions." },
  { icon: Video, title: "Mock Interviews", text: "Run role-specific HR, technical and leadership interview sessions." },
  { icon: UsersRound, title: "Industry Mentorship", text: "Share practical industry knowledge through focused one-to-one sessions." },
  { icon: BookOpen, title: "Courses & Workshops", text: "Create career courses, webinars and live skill-building workshops." },
  { icon: GraduationCap, title: "Student Guidance", text: "Support freshers with career roadmaps, portfolios and first-job preparation." },
  { icon: BriefcaseBusiness, title: "Hiring Consulting", text: "Help companies with job descriptions, hiring strategy and interview design." },
];

const steps = [
  ["01", "Create your profile", "Tell us about your expertise, experience and the services you want to offer."],
  ["02", "Submit your offering", "Upload a template or create a service with pricing, delivery details and previews."],
  ["03", "Publish instantly", "Your service becomes visible in the relevant marketplace section immediately."],
  ["04", "Sell and earn", "Earn whenever a customer downloads your template or books your service."],
];

export default function EarnWithJobiVersePage() {
  return <main className="overflow-hidden bg-[#f6f6f3] pb-24 pt-28 text-zinc-950">
    <section className="relative mx-auto max-w-[1500px] px-5 pt-8 sm:px-8"><div className="relative overflow-hidden rounded-[3rem] bg-[radial-gradient(circle_at_12%_15%,rgba(255,255,255,.18),transparent_23rem),linear-gradient(135deg,#09090b,#27272a_58%,#52525b)] px-7 py-20 text-white shadow-[0_45px_120px_-45px_rgba(0,0,0,.65)] sm:px-14 lg:py-28"><div className="absolute -right-28 -top-28 h-96 w-96 rounded-full border border-white/10"/><div className="absolute -right-10 top-10 h-72 w-72 rounded-full border border-white/10"/><div className="relative z-10 max-w-3xl"><div className="inline-flex items-center gap-2 rounded-full border border-white/15 bg-white/10 px-4 py-2 text-xs font-bold uppercase tracking-[.18em]"><Sparkles size={15}/> Creator economy for careers</div><h1 className="mt-7 whitespace-nowrap text-4xl font-semibold tracking-[-.055em] sm:text-6xl lg:text-[4.6rem]">Earn with JobiVerse.</h1><p className="mt-7 max-w-2xl text-lg leading-8 text-zinc-300 sm:text-xl">Turn your creativity, knowledge and professional expertise into income-while helping people build stronger careers.</p><div className="mt-10 flex flex-wrap gap-3"><Link href="#apply" className="inline-flex items-center gap-2 rounded-2xl bg-white px-6 py-4 font-semibold text-zinc-950">Become a Creator <ArrowRight size={18}/></Link><Link href="#ways-to-earn" className="rounded-2xl border border-white/20 bg-white/5 px-6 py-4 font-semibold">Explore ways to earn</Link></div></div><CreatorOrbit/></div></section>
    <div className="h-4" />
    <PageSectionIndex items={[{label:"Ways to earn",href:"#ways-to-earn"},{label:"Explore offerings",href:"#ways-to-earn"},{label:"Become a creator",href:"#apply"},{label:"Creator dashboard",href:"/earn-with-jobiverse/dashboard"}]}/>
    <section className="mx-auto mt-10 grid max-w-[1450px] gap-4 px-5 sm:grid-cols-3 sm:px-8"><Metric icon={CircleDollarSign} value="Creator-led" label="You choose your earning amount"/><Metric icon={HandCoins} value="Every sale" label="Earn from each successful purchase"/><Metric icon={ChartNoAxesCombined} value="Transparent" label="Track sales, earnings and payouts"/></section>
    <section id="ways-to-earn" className="mx-auto max-w-[1450px] px-5 py-28 sm:px-8"><p className="text-xs font-bold uppercase tracking-[.2em] text-zinc-400">Ways to earn</p><div className="mt-3 flex flex-col justify-between gap-5 lg:flex-row lg:items-end"><h2 className="max-w-3xl text-4xl font-semibold tracking-[-.04em] sm:text-6xl">Build income around what you do best.</h2><p className="max-w-md text-zinc-500">Start with one offering and grow your creator presence across the JobiVerse ecosystem.</p></div><div className="mt-12 grid gap-4 md:grid-cols-2 xl:grid-cols-4">{opportunities.map(({icon:Icon,title,text},index)=><article key={title} className="group rounded-[2rem] border border-zinc-200 bg-white p-7 shadow-sm transition duration-300 hover:-translate-y-1 hover:shadow-xl"><div className="flex items-center justify-between"><span className="grid h-12 w-12 place-items-center rounded-2xl bg-zinc-950 text-white"><Icon size={21}/></span><span className="text-xs font-bold text-zinc-300">0{index+1}</span></div><h3 className="mt-7 text-xl font-semibold">{title}</h3><p className="mt-3 text-sm leading-6 text-zinc-500">{text}</p></article>)}</div></section>
    <section className="bg-zinc-950 py-28 text-white"><div className="mx-auto max-w-[1450px] px-5 sm:px-8"><div className="grid gap-14 lg:grid-cols-[.8fr_1.2fr]"><div><p className="text-xs font-bold uppercase tracking-[.2em] text-zinc-500">Creator pricing</p><h2 className="mt-4 text-4xl font-semibold tracking-[-.04em] sm:text-6xl">Your price.<br/><span className="text-zinc-500">Our marketplace.</span></h2><p className="mt-6 max-w-lg leading-7 text-zinc-400">Set the amount you want to earn from every successful template download. The final customer price is calculated transparently before your listing is published.</p></div><div className="rounded-[2.5rem] border border-white/10 bg-white/[.05] p-7 sm:p-10"><div className="rounded-2xl bg-white/[.06] p-6"><p className="text-xs font-bold uppercase tracking-[.16em] text-zinc-500">Simple earnings model</p><p className="mt-3 text-2xl font-semibold">Choose your earning per sale.</p><p className="mt-2 text-sm leading-6 text-zinc-400">You will see your expected earning and the final listing price before submitting the product for review.</p></div><div className="my-8 h-px bg-white/10"/><div className="space-y-4">{["Creator earning recorded on every verified sale","Final customer price shown before publishing","Refunds and disputes reflected transparently","Payouts released after the settlement period"].map(item=><div className="flex items-center gap-3 text-sm text-zinc-300" key={item}><BadgeCheck className="text-emerald-400" size={18}/>{item}</div>)}</div></div></div></div></section>
    <section className="mx-auto max-w-[1450px] px-5 py-28 sm:px-8"><div className="grid gap-12 lg:grid-cols-[.75fr_1.25fr]"><div><p className="text-xs font-bold uppercase tracking-[.2em] text-zinc-400">How it works</p><h2 className="mt-4 text-4xl font-semibold tracking-[-.04em] sm:text-5xl">From expertise to earnings.</h2><p className="mt-5 text-zinc-500">A quality-controlled marketplace designed to protect customers and support serious creators.</p></div><div className="space-y-3">{steps.map(([number,title,text])=><article key={number} className="grid gap-4 rounded-[1.75rem] border border-zinc-200 bg-white p-6 sm:grid-cols-[60px_1fr]"><span className="text-2xl font-semibold text-zinc-300">{number}</span><div><h3 className="text-lg font-semibold">{title}</h3><p className="mt-2 text-sm leading-6 text-zinc-500">{text}</p></div></article>)}</div></div></section>
    <section id="apply" className="mx-auto max-w-[1450px] px-5 sm:px-8"><div className="relative overflow-hidden rounded-[3rem] border border-zinc-200 bg-white p-8 shadow-xl sm:p-14"><div className="absolute right-0 top-0 h-full w-1/3 bg-[radial-gradient(circle_at_center,rgba(0,0,0,.08),transparent_65%)]"/><div className="relative grid gap-10 lg:grid-cols-[1fr_auto] lg:items-center"><div><div className="flex items-center gap-2 text-xs font-bold uppercase tracking-[.18em] text-zinc-400"><ShieldCheck size={16}/> Original work. Real expertise.</div><h2 className="mt-4 text-4xl font-semibold tracking-[-.04em] sm:text-6xl">Ready to create and earn?</h2><p className="mt-5 max-w-2xl text-zinc-500">Log in, describe your expertise and publish your first service directly to the JobiVerse marketplace.</p><div className="mt-6 flex items-start gap-3 rounded-2xl bg-zinc-100 p-4 text-sm text-zinc-600"><Star className="mt-0.5 shrink-0" size={17}/><p>Creators confirm that submitted templates and service materials are their original work.</p></div></div><Link href="/earn-with-jobiverse/dashboard/services/new" className="inline-flex items-center justify-center gap-2 rounded-2xl bg-zinc-950 px-7 py-4 font-semibold text-white">Create a service <Upload size={18}/></Link></div></div></section>
  </main>;
}

function Metric({icon:Icon,value,label}:{icon:React.ElementType;value:string;label:string}){return <div className="rounded-[1.75rem] border border-zinc-200 bg-white p-6"><Icon size={20}/><p className="mt-5 text-2xl font-semibold">{value}</p><p className="mt-1 text-sm text-zinc-500">{label}</p></div>}
function CreatorOrbit(){return <div aria-hidden="true" className="absolute right-10 top-1/2 hidden h-[520px] w-[520px] -translate-y-1/2 lg:block"><div className="absolute inset-12 rounded-full border border-white/10"/><div className="absolute inset-28 rounded-full border border-white/10"/><div className="absolute left-1/2 top-1/2 grid h-36 w-36 -translate-x-1/2 -translate-y-1/2 place-items-center rounded-[2rem] border border-white/15 bg-white/10 text-center shadow-2xl backdrop-blur"><div><CircleDollarSign className="mx-auto text-zinc-300" size={34}/><p className="mt-2 text-sm font-semibold">Creator<br/>Earnings</p></div></div><OrbitCard className="left-4 top-24" icon={Palette} label="Templates"/><OrbitCard className="right-0 top-40" icon={MessagesSquare} label="Services"/><OrbitCard className="bottom-10 left-28" icon={Video} label="Sessions"/><div className="absolute right-16 top-2 rounded-2xl border border-emerald-400/20 bg-emerald-400/10 px-4 py-3 text-sm font-semibold text-emerald-300">+ New sale</div></div>}
function OrbitCard({className,icon:Icon,label}:{className:string;icon:React.ElementType;label:string}){return <div className={`absolute flex items-center gap-3 rounded-2xl border border-white/15 bg-white/10 px-4 py-3 shadow-xl backdrop-blur ${className}`}><Icon size={18}/><span className="text-sm font-semibold">{label}</span></div>}
