"use server";

import { revalidatePath } from "next/cache";
import { z } from "zod";
import { requireRole } from "@/lib/auth/authorization";
import { adminSupabase } from "@/lib/supabase/admin";
import { redirect } from "next/navigation";

const uuid=z.string().uuid();
function refresh(){revalidatePath("/admin/marketplace");revalidatePath("/marketplace");revalidatePath("/marketplace/orders","layout");revalidatePath("/earn-with-jobiverse/dashboard/orders","layout");}

export async function moderateService(formData:FormData){const id=uuid.parse(formData.get("serviceId"));const status=z.enum(["published","paused","archived"]).parse(formData.get("status"));const note=z.string().trim().max(1000).parse(String(formData.get("moderationNote")??""));if(status!=="published"&&note.length<10)throw new Error("Add a moderation reason of at least 10 characters before restricting a service.");const {supabase,user}=await requireRole(["admin"]);const{data:service}=await supabase.from("marketplace_services").select("provider_id,title,status").eq("id",id).maybeSingle();if(!service)throw new Error("Service not found.");const {error}=await supabase.from("marketplace_services").update({status,moderation_note:status==="published"?null:note,moderated_by:user.id,moderated_at:new Date().toISOString()}).eq("id",id);if(error)throw new Error(error.message);if(service.status!==status)await adminSupabase.from("notifications").insert({user_id:service.provider_id,type:"service_moderation",title:status==="published"?"Service listing restored":`Service listing ${status}`,message:status==="published"?`JobiVerse restored your service \"${service.title}\" and it is visible in the marketplace again.`:`JobiVerse ${status} your service \"${service.title}\". Reason: ${note}`,href:"/earn-with-jobiverse/dashboard/services",reference_id:id});refresh();}

export async function updateAdminOrder(formData:FormData){const id=uuid.parse(formData.get("orderId"));const action=z.enum(["mark_paid","cancel","refund","hold_payout"]).parse(formData.get("action"));const {supabase}=await requireRole(["admin"]);const updates:Record<string,unknown>={};if(action==="mark_paid")Object.assign(updates,{status:"paid",paid_at:new Date().toISOString(),payment_reference:`MANUAL-${Date.now()}`});if(action==="cancel")updates.status="cancelled";if(action==="refund")Object.assign(updates,{status:"refunded",payout_status:"held"});if(action==="hold_payout")updates.payout_status="held";const {error}=await supabase.from("marketplace_orders").update(updates).eq("id",id);if(error)throw new Error(error.message);refresh();}

export async function resolveDispute(formData:FormData){const id=uuid.parse(formData.get("disputeId"));const status=z.enum(["reviewing","resolved","rejected"]).parse(formData.get("status"));const resolution=z.string().trim().min(10).max(3000).parse(formData.get("resolution"));const {supabase,user}=await requireRole(["admin"]);const {error}=await supabase.from("marketplace_disputes").update({status,resolution,resolved_by:user.id,resolved_at:["resolved","rejected"].includes(status)?new Date().toISOString():null}).eq("id",id);if(error)throw new Error(error.message);refresh();}

export async function deleteReview(formData:FormData){const id=uuid.parse(formData.get("reviewId"));const {supabase}=await requireRole(["admin"]);const {error}=await supabase.from("marketplace_reviews").delete().eq("id",id);if(error)throw new Error(error.message);refresh();}

export async function moderateReviewReport(formData:FormData){const reportId=uuid.parse(formData.get("reportId"));const action=z.enum(["reviewing","hide","dismiss","restore"]).parse(formData.get("action"));const note=z.string().trim().max(1000).parse(String(formData.get("moderationNote")??""));if(action==="hide"&&note.length<10)throw new Error("Add a moderation reason of at least 10 characters before hiding a review.");const{user}=await requireRole(["admin"]);const{data:report}=await adminSupabase.from("marketplace_review_reports").select("id,review_id,reporter_id,status,marketplace_reviews(reviewer_id,review)").eq("id",reportId).maybeSingle();if(!report)throw new Error("Review report not found.");const review=Array.isArray(report.marketplace_reviews)?report.marketplace_reviews[0]:report.marketplace_reviews;if(action==="hide"||action==="restore"){const{error}=await adminSupabase.from("marketplace_reviews").update({is_hidden:action==="hide",moderation_note:action==="hide"?note:null}).eq("id",report.review_id);if(error)throw new Error(error.message);}const status=action==="reviewing"?"reviewing":action==="dismiss"?"dismissed":"resolved";const{error}=await adminSupabase.from("marketplace_review_reports").update({status,reviewed_by:user.id,reviewed_at:["resolved","dismissed"].includes(status)?new Date().toISOString():null,moderation_note:note||null}).eq("id",reportId);if(error)throw new Error(error.message);const notifications=[{user_id:report.reporter_id,type:"review_report_status",title:action==="hide"?"Reported review removed":action==="dismiss"?"Review report dismissed":action==="reviewing"?"Review report under review":"Review restored",message:action==="hide"?"JobiVerse reviewed your report and removed the review from public view.":action==="dismiss"?"JobiVerse reviewed the report and did not find sufficient grounds to remove the review.":action==="reviewing"?"JobiVerse has started reviewing the reported customer feedback.":"The review has been restored after moderation review.",href:"/marketplace",reference_id:report.review_id}];if(action==="hide"&&review?.reviewer_id)notifications.push({user_id:review.reviewer_id,type:"review_moderation",title:"Your review was hidden",message:`JobiVerse hid your marketplace review. Reason: ${note}`,href:"/marketplace/orders",reference_id:report.review_id});await adminSupabase.from("notifications").insert(notifications);refresh();}

export async function resolveServiceReport(formData:FormData){const id=uuid.parse(formData.get("reportId"));const status=z.enum(["reviewing","resolved","dismissed"]).parse(formData.get("status"));const{supabase,user}=await requireRole(["admin"]);const{data:report}=await supabase.from("marketplace_service_reports").select("reporter_id,service_id,status,marketplace_services(title)").eq("id",id).maybeSingle();if(!report)throw new Error("Service report not found.");const{error}=await supabase.from("marketplace_service_reports").update({status,reviewed_by:user.id,reviewed_at:["resolved","dismissed"].includes(status)?new Date().toISOString():null}).eq("id",id);if(error)throw new Error(error.message);if(report.status!==status){const listing=Array.isArray(report.marketplace_services)?report.marketplace_services[0]:report.marketplace_services;await adminSupabase.from("notifications").insert({user_id:report.reporter_id,type:"service_report_status",title:status==="reviewing"?"Service report under review":status==="resolved"?"Service report resolved":"Service report dismissed",message:status==="reviewing"?`JobiVerse is reviewing your report for \"${listing?.title??"a marketplace service"}\".`:status==="resolved"?`JobiVerse completed action on your report for \"${listing?.title??"a marketplace service"}\". Thank you for helping keep the marketplace safe.`:`After review, JobiVerse did not find sufficient grounds for action on \"${listing?.title??"the reported service"}\".`,href:"/marketplace",reference_id:report.service_id});}refresh();}

export async function updateCreatorVerification(formData:FormData){const creatorId=uuid.parse(formData.get("creatorId"));const status=z.enum(["unverified","verified","suspended"]).parse(formData.get("verificationStatus"));const note=z.string().trim().max(500).parse(String(formData.get("verificationNote")??""));const{user}=await requireRole(["admin"]);const{error}=await adminSupabase.from("creator_marketplace_profiles").upsert({creator_id:creatorId,verification_status:status,verification_note:note||null,verified_by:user.id,verified_at:status==="verified"?new Date().toISOString():null,updated_at:new Date().toISOString()},{onConflict:"creator_id"});if(error)throw new Error(error.message);await adminSupabase.from("notifications").insert({user_id:creatorId,type:"creator_verification",title:status==="verified"?"Creator profile verified":status==="suspended"?"Creator verification suspended":"Creator verification updated",message:status==="verified"?"JobiVerse verified your creator profile. A verified badge will now appear on eligible marketplace listings.":status==="suspended"?`Your creator verification was suspended. ${note}`:"Your creator profile is currently unverified.",href:"/earn-with-jobiverse/dashboard",reference_id:creatorId});refresh();redirect("/admin/marketplace?updated=verification");}

export async function updateFeaturedListing(formData:FormData){const serviceId=uuid.parse(formData.get("serviceId"));const action=z.enum(["feature","remove"]).parse(formData.get("featureAction"));await requireRole(["admin"]);const{data:service}=await adminSupabase.from("marketplace_services").select("provider_id,title").eq("id",serviceId).maybeSingle();if(!service)throw new Error("Service not found.");const featured=action==="feature";const{error}=await adminSupabase.from("marketplace_services").update({is_featured:featured,featured_until:featured?new Date(Date.now()+30*86400000).toISOString():null}).eq("id",serviceId);if(error)throw new Error(error.message);await adminSupabase.from("notifications").insert({user_id:service.provider_id,type:"service_featured",title:featured?"Service featured":"Featured placement ended",message:featured?`Your service \"${service.title}\" is featured in marketplace ranking for 30 days.`:`Featured placement for \"${service.title}\" has been removed.`,href:"/earn-with-jobiverse/dashboard",reference_id:serviceId});refresh();redirect("/admin/marketplace?updated=featured");}

export async function moderateCreatorTemplate(formData:FormData){const serviceId=uuid.parse(formData.get("serviceId"));const status=z.enum(["approved","rejected","pending"]).parse(formData.get("templateStatus"));const note=z.string().trim().max(1000).parse(String(formData.get("templateNote")??""));if(status==="rejected"&&note.length<10)throw new Error("Add a rejection reason of at least 10 characters.");const{user}=await requireRole(["admin"]);const{data:service}=await adminSupabase.from("marketplace_services").select("provider_id,title,is_editable,template_rights_status").eq("id",serviceId).maybeSingle();if(!service?.is_editable)throw new Error("Editable template listing not found.");if(status==="approved"&&service.template_rights_status!=="accepted")throw new Error("The creator must accept the template ownership declaration before approval.");const{error}=await adminSupabase.from("marketplace_services").update({template_review_status:status,template_review_note:note||null,template_reviewed_by:user.id,template_reviewed_at:new Date().toISOString(),status:status==="rejected"?"paused":"published"}).eq("id",serviceId);if(error)throw new Error(error.message);await adminSupabase.from("notifications").insert({user_id:service.provider_id,type:"template_review",title:status==="approved"?"CV template approved":status==="rejected"?"CV template needs changes":"CV template under review",message:status==="approved"?`Your editable template \"${service.title}\" is approved for marketplace sale.`:status==="rejected"?`Your editable template \"${service.title}\" was paused. Reason: ${note}`:`Your editable template \"${service.title}\" is under review.`,href:"/earn-with-jobiverse/dashboard",reference_id:serviceId});refresh();redirect("/admin/marketplace?updated=template");}
