// The OpenNext worker is generated by `npm run cf:build` before Wrangler bundles this entrypoint.
import openNextWorker from "./.open-next/worker.js";

type WorkerEnv = { EMAIL_WORKER_SECRET?: string } & Record<string, unknown>;
type ExecutionContextLike = { waitUntil(promise: Promise<unknown>): void };

export default {
  fetch(request: Request, env: WorkerEnv, context: ExecutionContextLike) {
    return openNextWorker.fetch(request, env, context);
  },
  scheduled(_controller: unknown, env: WorkerEnv, context: ExecutionContextLike) {
    if (!env.EMAIL_WORKER_SECRET) return;
    const request = new Request("https://jobiverse.in/api/internal/jobs/digest", {
      method: "POST",
      headers: { authorization: `Bearer ${env.EMAIL_WORKER_SECRET}` },
    });
    context.waitUntil(openNextWorker.fetch(request, env, context));
  },
};
