// The OpenNext worker is generated by `npm run cf:build` before Wrangler bundles this entrypoint.
import openNextWorker from "./.open-next/worker.js";

type WorkerEnv = { EMAIL_WORKER_SECRET?: string; CRON_SECRET?: string } & Record<string, unknown>;
type ExecutionContextLike = { waitUntil(promise: Promise<unknown>): void };

const worker = {
  fetch(request: Request, env: WorkerEnv, context: ExecutionContextLike) {
    return openNextWorker.fetch(request, env, context);
  },
  scheduled(_controller: unknown, env: WorkerEnv, context: ExecutionContextLike) {
    if (!env.EMAIL_WORKER_SECRET) return;
    const request = new Request("https://jobiverse.in/api/internal/jobs/digest", {
      method: "POST",
      headers: { authorization: `Bearer ${env.EMAIL_WORKER_SECRET}` },
    });
    context.waitUntil(openNextWorker.fetch(request, env, context));
    const reminders = new Request("https://jobiverse.in/api/internal/interviews/reminders", { headers: { authorization: `Bearer ${env.EMAIL_WORKER_SECRET}` } });
    context.waitUntil(openNextWorker.fetch(reminders, env, context));
    if (env.CRON_SECRET) {
      const cleanup = new Request("https://jobiverse.in/api/cron/jobs/cleanup", { headers: { authorization: `Bearer ${env.CRON_SECRET}` } });
      context.waitUntil(openNextWorker.fetch(cleanup, env, context));
    }
  },
};

export default worker;
