import { ArrowDown, BarChart3, CircleDollarSign, MousePointerClick, TrendingUp, UsersRound } from "lucide-react";
import { requireRole } from "@/lib/auth/authorization";
import { adminSupabase } from "@/lib/supabase/admin";

export default async function GrowthAnalyticsPage(){
  await requireRole(["admin"]);
  const [{data:users},{data:companies},{data:requirements},{data:applications},{data:services},{data:offers},{data:orders},{data:payments},{data:consultations}]=await Promise.all([
    adminSupabase.from("users").select("id,role,created_at"),adminSupabase.from("companies").select("id,created_at"),adminSupabase.from("requirements").select("id,status,created_at"),adminSupabase.from("candidate_applications").select("id,status,created_at"),adminSupabase.from("marketplace_services").select("id,status,created_at"),adminSupabase.from("marketplace_offers").select("id,status,created_at"),adminSupabase.from("marketplace_orders").select("id,status,amount,created_at"),adminSupabase.from("payment_attempts").select("id,status,amount,created_at"),adminSupabase.from("consultation_bookings").select("id,status,payment_status,created_at")]);
  const people=users??[];const paid=(payments??[]).filter(item=>["captured","paid"].includes(item.status));
  const funnels=[
    {title:"Employer activation",steps:[["Employer accounts",people.filter(item=>item.role==="employer").length],["Company profiles",companies?.length??0],["Requirements created",requirements?.length??0]]},
    {title:"Candidate activation",steps:[["Candidate accounts",people.filter(item=>item.role==="candidate").length],["Applications submitted",applications?.length??0],["Advanced applications",(applications??[]).filter(item=>!["applied","withdrawn","rejected"].includes(item.status)).length]]},
    {title:"Marketplace conversion",steps:[["Published services",(services??[]).filter(item=>item.status==="published").length],["Negotiations",offers?.length??0],["Paid orders",(orders??[]).filter(item=>!["pending_payment","cancelled"].includes(item.status)).length]]},
    {title:"Consultation conversion",steps:[["Bookings",consultations?.length??0],["Confirmed",(consultations??[]).filter(item=>["confirmed","completed"].includes(item.status)).length],["Completed",(consultations??[]).filter(item=>item.status==="completed").length]]},
  ];
  const metrics=[["Registered users",people.length,UsersRound],["Payments captured",paid.length,MousePointerClick],["Captured value",money(paid.reduce((sum,item)=>sum+Number(item.amount||0),0)),CircleDollarSign],["Completed orders",(orders??[]).filter(item=>item.status==="completed").length,TrendingUp]] as const;
  return <div className="space-y-8"><section className="relative overflow-hidden rounded-[2.5rem] bg-zinc-950 p-9 text-white sm:p-12"><BarChart3/><p className="mt-5 text-xs font-bold uppercase tracking-[.2em] text-zinc-500">Real conversion intelligence</p><h1 className="mt-3 text-4xl font-bold sm:text-5xl">Growth Analytics.</h1><p className="mt-4 max-w-3xl text-zinc-400">Every number below comes from live JobiVerse records. Website visitors and campaign attribution will appear only after an analytics measurement ID is connected.</p></section><section className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{metrics.map(([label,value,Icon])=><article key={label} className="rounded-3xl border border-zinc-200 bg-white p-6"><Icon className="text-zinc-400"/><p className="mt-5 text-sm text-zinc-500">{label}</p><p className="mt-2 text-3xl font-bold">{value}</p></article>)}</section><section className="grid gap-6 xl:grid-cols-2">{funnels.map(funnel=><article key={funnel.title} className="rounded-[2rem] border border-zinc-200 bg-white p-7"><h2 className="text-xl font-bold">{funnel.title}</h2><div className="mt-6 space-y-2">{funnel.steps.map(([label,value],index)=><div key={String(label)}>{index>0&&<ArrowDown className="mx-auto my-2 text-zinc-300" size={16}/>}<div className="flex items-center justify-between rounded-2xl bg-zinc-50 px-5 py-4"><span className="text-sm font-semibold">{label}</span><span className="text-2xl font-bold">{value}</span></div></div>)}</div></article>)}</section><section className="rounded-[2rem] border border-dashed border-zinc-300 bg-white p-7"><p className="text-xs font-bold uppercase tracking-wider text-zinc-400">Visitor attribution</p><h2 className="mt-2 text-2xl font-bold">Ready for analytics connection</h2><p className="mt-3 max-w-3xl text-sm leading-6 text-zinc-500">Connect a privacy-aware analytics provider before launch to unlock landing-page visits, traffic sources, campaign conversion and drop-off reporting. Until then JobiVerse intentionally shows no invented visitor numbers.</p></section></div>;
}
function money(value:number){return new Intl.NumberFormat("en-IN",{style:"currency",currency:"INR",maximumFractionDigits:0}).format(value)}
