import Link from "next/link";
import { ArrowRight, BadgeCheck, BarChart3, BriefcaseBusiness, CalendarDays, Search, UsersRound, WalletCards } from "lucide-react";
const groups=[
  {icon:BriefcaseBusiness,title:"Requirements & free job posting",tag:"Free",items:["Create, edit and publish requirements","Job Quality Assistant and audience targeting","Direct applicant pipeline","3% success fee only after a direct hire joins"]},
  {icon:UsersRound,title:"Unified candidate workspace",tag:"Premium",items:["Direct, recruiter and JobiVerse candidates","Profiles, resumes, notes and comparisons","Talent folders and consent-first details","Shortlist-to-joining status control"]},
  {icon:CalendarDays,title:"Interviews & offers",tag:"Premium",items:["Multiple interview rounds and reminders","Meeting links, feedback and outcomes","Offer terms and candidate responses","Joining and replacement-period visibility"]},
  {icon:UsersRound,title:"Team & recruiter access",tag:"Premium",items:["Master employer controls","Employer and recruiter seats","Requirement-level assignments","Role-based company access"]},
  {icon:Search,title:"Talent Search",tag:"Add-on",items:["Open-to-work talent discovery","Advanced profile filters","Admin-approved access","Secure outreach workflow"]},
  {icon:BarChart3,title:"Reports & hiring intelligence",tag:"Premium",items:["Hiring health and funnel analytics","Requirement performance","Recruiter performance","Source and conversion visibility"]},
  {icon:WalletCards,title:"Billing & accountability",tag:"Included",items:["Plan and seat visibility","Placement fee records","Statements and payment tracking","Clear free, paid and add-on labels"]},
];
export function EmployerFeatureMap(){return <section className="rounded-[2.75rem] border border-violet-100 bg-white p-6 shadow-[0_30px_90px_-55px_rgba(55,30,75,.45)] sm:p-9"><div className="flex flex-wrap items-end justify-between gap-5"><div><p className="text-xs font-black uppercase tracking-[.2em] text-violet-700">Your complete Employer Hub</p><h2 className="mt-3 text-3xl font-semibold tracking-[-.045em] text-zinc-950 sm:text-5xl">Everything JobiVerse can do for your hiring team.</h2><p className="mt-4 max-w-3xl leading-7 text-zinc-600">Explore the full workspace before choosing what to activate. Free, premium and add-on tools are labelled clearly.</p></div><Link href="/employers/demo" className="inline-flex min-h-12 items-center gap-2 rounded-2xl border border-violet-200 bg-violet-50 px-5 font-bold text-violet-950">Try interactive demo <ArrowRight size={16}/></Link></div><div className="mt-8 grid gap-4 md:grid-cols-2 xl:grid-cols-3">{groups.map(({icon:Icon,title,tag,items})=><article key={title} className="rounded-[1.75rem] border border-zinc-200 bg-[#fbfafc] p-6"><div className="flex items-start justify-between gap-3"><span className="grid h-11 w-11 place-items-center rounded-2xl bg-violet-950 text-white"><Icon size={19}/></span><span className="rounded-full bg-white px-3 py-1 text-[10px] font-black uppercase tracking-wider text-violet-800">{tag}</span></div><h3 className="mt-5 text-xl font-bold text-zinc-950">{title}</h3><ul className="mt-4 space-y-3">{items.map(item=><li key={item} className="flex gap-2 text-sm leading-5 text-zinc-600"><BadgeCheck className="mt-0.5 shrink-0 text-violet-700" size={15}/>{item}</li>)}</ul></article>)}</div><div className="mt-6 flex flex-wrap gap-3"><Link href="/plans?audience=employer" className="inline-flex min-h-12 items-center gap-2 rounded-2xl bg-violet-950 px-6 font-bold text-white">View employer plans <ArrowRight size={16}/></Link><Link href="/pricing" className="inline-flex min-h-12 items-center rounded-2xl border border-zinc-200 px-6 font-bold text-zinc-800">Compare pricing</Link></div></section>}
