"use client";

import { useState } from "react";
import { BarChart3, BriefcaseBusiness, CalendarDays, LockKeyhole, Search, Users } from "lucide-react";

const tabs = [
  { id: "requirements", label: "Requirements", icon: BriefcaseBusiness },
  { id: "pipeline", label: "Candidate pipeline", icon: Users },
  { id: "talent", label: "Talent Search", icon: Search },
  { id: "reports", label: "Reports & seats", icon: BarChart3 },
] as const;

export function EmployerWorkspaceDemo() {
  const [tab, setTab] = useState<(typeof tabs)[number]["id"]>("requirements");
  return <div className="overflow-hidden rounded-[2.5rem] border border-zinc-200 bg-white shadow-2xl"><div className="border-b border-zinc-200 bg-zinc-950 p-5 text-white"><div className="flex flex-wrap items-center justify-between gap-4"><div><p className="text-xs font-bold uppercase tracking-[.18em] text-emerald-300">Interactive product demo</p><p className="mt-1 font-semibold">NovaTech · Master Employer Workspace</p></div><span className="rounded-full bg-white/10 px-4 py-2 text-xs font-bold">Illustrative data</span></div><div className="mt-5 flex gap-2 overflow-x-auto pb-1">{tabs.map(({id,label,icon:Icon})=><button key={id} onClick={()=>setTab(id)} className={`flex shrink-0 cursor-pointer items-center gap-2 rounded-xl px-4 py-3 text-sm font-semibold transition ${tab===id?"bg-white text-zinc-950":"bg-white/5 text-zinc-300 hover:bg-white/10"}`}><Icon size={16}/>{label}</button>)}</div></div>
    <div className="min-h-[470px] bg-[#f5f5f3] p-5 sm:p-8">{tab === "requirements" && <Requirements/>}{tab === "pipeline" && <Pipeline/>}{tab === "talent" && <Talent/>}{tab === "reports" && <Reports/>}</div></div>;
}

function Requirements(){return <div><Header eyebrow="Requirement command centre" title="Every role, owner and outcome in one view."/><div className="mt-6 grid gap-4 lg:grid-cols-3">{[
  ["Senior Backend Engineer","12 applicants","Interviewing","Ayesha Khan"],
  ["Growth Marketing Lead","8 applicants","Screening","Rahul Mehta"],
  ["Finance Manager","4 applicants","New","Priya Shah"],
].map(([role,count,status,owner])=><article key={role} className="rounded-2xl border border-zinc-200 bg-white p-5"><div className="flex justify-between gap-3"><BriefcaseBusiness/><span className="rounded-full bg-emerald-50 px-3 py-1 text-xs font-bold text-emerald-700">{status}</span></div><h3 className="mt-5 text-lg font-bold">{role}</h3><p className="mt-2 text-sm text-zinc-500">{count} · Assigned to {owner}</p><div className="mt-5 h-2 rounded-full bg-zinc-100"><div className="h-full w-2/3 rounded-full bg-zinc-950"/></div></article>)}</div></div>}
function Pipeline(){const stages=[["Submitted",14],["Screening",9],["Interview",5],["Offered",2],["Joined",1]];return <div><Header eyebrow="Unified candidate pipeline" title="Direct, recruiter and JobiVerse talent—together."/><div className="mt-6 grid gap-3 sm:grid-cols-5">{stages.map(([stage,total],i)=><article key={String(stage)} className="rounded-2xl border border-zinc-200 bg-white p-5"><p className="text-xs font-bold uppercase tracking-wider text-zinc-400">{stage}</p><p className="mt-3 text-4xl font-bold">{total}</p><div className={`mt-5 h-1.5 rounded-full ${i>2?"bg-emerald-400":"bg-violet-500"}`}/></article>)}</div><div className="mt-5 rounded-2xl border border-zinc-200 bg-white p-5"><div className="grid gap-3 sm:grid-cols-[1.3fr_1fr_1fr_120px]">{["Candidate","Role","Source","Status"].map(x=><p key={x} className="text-xs font-bold uppercase text-zinc-400">{x}</p>)}{[["Aarohi Verma","Backend Engineer","Recruiter","Interview"],["Kabir Joshi","Growth Lead","Direct apply","Screening"],["Meera Iyer","Finance Manager","JobiVerse","Submitted"]].flatMap(row=>row.map((x,i)=><p key={`${row[0]}-${i}`} className="border-t border-zinc-100 pt-3 text-sm font-semibold">{x}</p>))}</div></div></div>}
function Talent(){return <div><Header eyebrow="Premium Talent Search" title="Search only open-to-work JobiVerse Cards."/><div className="mt-6 grid gap-5 lg:grid-cols-[260px_1fr]"><aside className="rounded-2xl bg-zinc-950 p-5 text-white"><Search/><p className="mt-4 font-bold">Smart filters</p>{["Role & skills","Location","Experience","Notice period","Salary range"].map(x=><div key={x} className="mt-3 rounded-xl bg-white/10 px-4 py-3 text-sm text-zinc-300">{x}</div>)}</aside><div className="grid gap-4 sm:grid-cols-2">{[["Riya Kapoor","Full Stack Developer","6 yrs · Mumbai","React, Node.js, AWS"],["Arjun Nair","Data Engineer","4 yrs · Bengaluru","Python, SQL, Spark"]].map(([name,role,meta,skills])=><article key={name} className="relative overflow-hidden rounded-2xl border border-zinc-200 bg-white p-6"><div className="absolute right-5 top-5 rounded-full bg-emerald-50 px-3 py-1 text-xs font-bold text-emerald-700">Open to work</div><div className="grid h-12 w-12 place-items-center rounded-2xl bg-violet-700 font-bold text-white">{name.split(" ").map(n=>n[0]).join("")}</div><h3 className="mt-5 text-xl font-bold">{name}</h3><p className="mt-1 font-semibold text-zinc-600">{role}</p><p className="mt-3 text-sm text-zinc-500">{meta}</p><p className="mt-4 rounded-xl bg-zinc-50 p-3 text-sm">{skills}</p></article>)}</div></div></div>}
function Reports(){return <div><Header eyebrow="Hiring intelligence" title="Know what is working before hiring slows down."/><div className="mt-6 grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{[["Requirement fulfilment","68%"],["Interview conversion","42%"],["Average time-to-hire","21 days"],["Team seats","4 / 6"]].map(([label,value])=><article key={label} className="rounded-2xl border border-zinc-200 bg-white p-5"><p className="text-xs font-bold uppercase text-zinc-400">{label}</p><p className="mt-4 text-3xl font-bold">{value}</p></article>)}</div><div className="mt-5 grid gap-5 lg:grid-cols-[1fr_300px]"><div className="rounded-2xl border border-zinc-200 bg-white p-6"><p className="font-bold">Recruiter performance</p>{[["Ayesha",82],["Rahul",71],["Priya",64]].map(([name,value])=><div key={String(name)} className="mt-5"><div className="flex justify-between text-sm"><span>{name}</span><strong>{value}%</strong></div><div className="mt-2 h-2 rounded-full bg-zinc-100"><div className="h-full rounded-full bg-violet-600" style={{width:`${value}%`}}/></div></div>)}</div><div className="rounded-2xl bg-amber-50 p-6 text-amber-950"><LockKeyhole/><p className="mt-4 font-bold">Controlled access</p><p className="mt-2 text-sm leading-6">Master employers control seats, permissions and company-wide visibility.</p><p className="mt-5 flex items-center gap-2 text-sm font-semibold"><CalendarDays size={16}/>Date-wise reports</p></div></div></div>}
function Header({eyebrow,title}:{eyebrow:string;title:string}){return <div><p className="text-xs font-bold uppercase tracking-[.18em] text-violet-700">{eyebrow}</p><h2 className="mt-2 text-3xl font-semibold tracking-[-.035em]">{title}</h2></div>}

