import Link from "next/link";
import { ArrowRight, BadgeCheck, Blocks, BriefcaseBusiness, Building2, ChartNoAxesCombined, Compass, Crown, Headphones, Layers3, Settings2, Sparkles, UsersRound, WalletCards } from "lucide-react";

type Props={companyName?:string|null;industry?:string|null;activeRequirements:number;candidates:number;coreActive:boolean};
const worlds=[
  {icon:Blocks,eyebrow:"Build for your organisation",title:"Custom Operations Portal",text:"Choose industry modules and describe the workflows, records, approvals and dashboards your organisation needs.",href:"/employers/custom-portal",cta:"Design my portal",tone:"violet"},
  {icon:BriefcaseBusiness,eyebrow:"Recruitment & talent",title:"Hiring Workspace",text:"Publish roles, manage applicants, interviews, offers and joining when your organisation needs to hire.",href:"/employers/requirements",cta:"Open hiring workspace",tone:"emerald"},
  {icon:Crown,eyebrow:"For consulting firms",title:"Premium Consulting Hub",text:"A ready-made multi-client workspace for recruitment consultancies and staffing agencies, with demo and scoped pricing.",href:"/employers/premium-hub",cta:"Explore consulting hub",tone:"amber"},
  {icon:UsersRound,eyebrow:"People & controlled access",title:"Organisation Team",text:"Maintain your company identity, master-employer controls and sub-employer seats for trusted organisation team members.",href:"/employers/team",cta:"Manage organisation",tone:"blue"},
  {icon:Compass,eyebrow:"Only for consulting agencies",title:"Business Services",text:"Access employer consultations, brand support, managed hiring and marketplace services without cluttering your core workspace.",href:"/marketplace?audience=employer",cta:"Explore services",tone:"fuchsia"},
  {icon:WalletCards,eyebrow:"Only for consulting agencies",title:"Plans & Billing",text:"Understand free access, premium unlocks, add-ons, statements and company-level commercials clearly.",href:"/plans?audience=employer",cta:"View plans",tone:"zinc"},
] as const;
const toneClasses={violet:"bg-violet-100 text-violet-900",emerald:"bg-emerald-100 text-emerald-900",amber:"bg-amber-100 text-amber-900",blue:"bg-blue-100 text-blue-900",fuchsia:"bg-fuchsia-100 text-fuchsia-900",zinc:"bg-zinc-200 text-zinc-900"};

export function EmployerCommandCenter({companyName,industry,activeRequirements,candidates,coreActive}:Props){return <div className="space-y-8">
  <section className="jv-brand-gradient relative overflow-hidden rounded-[3rem] p-8 text-white shadow-2xl sm:p-12 lg:p-14"><div className="pointer-events-none absolute -right-24 -top-24 h-80 w-80 rounded-full border border-white/10"/><div className="pointer-events-none absolute bottom-0 left-1/3 h-52 w-52 rounded-full bg-violet-400/10 blur-3xl"/><div className="relative grid gap-10 lg:grid-cols-[1fr_.72fr] lg:items-end"><div><p className="flex items-center gap-2 text-xs font-black uppercase tracking-[.22em] text-violet-200"><Building2 size={15}/> Employer Universe</p><h1 className="mt-5 max-w-4xl text-5xl font-semibold leading-[.95] tracking-[-.055em] text-white sm:text-7xl">Build the workspace<br/>your organisation needs.</h1><p className="mt-6 max-w-3xl text-lg leading-8 text-zinc-300">JobiVerse is more than a hiring dashboard. Choose a focused path for operations, people, recruitment, consulting services or business growth—without forcing every tool into one screen.</p></div><div className="rounded-[2rem] border border-white/15 bg-white/[.08] p-6 backdrop-blur"><p className="text-xs font-black uppercase tracking-[.18em] text-violet-200">Your organisation</p><h2 className="mt-3 text-2xl font-bold text-white">{companyName||"Complete your company workspace"}</h2><p className="mt-2 text-sm text-zinc-300">{industry||"Add your industry and organisation details"}</p><div className="mt-5 flex flex-wrap gap-2"><span className="rounded-full bg-white/10 px-3 py-2 text-xs font-bold">{coreActive?"Premium active":"Free workspace"}</span><span className="rounded-full bg-white/10 px-3 py-2 text-xs font-bold">{activeRequirements} active roles</span><span className="rounded-full bg-white/10 px-3 py-2 text-xs font-bold">{candidates} candidates</span></div><div className="mt-5 flex flex-wrap gap-4"><Link href="/employers/company" className="inline-flex items-center gap-2 text-sm font-bold text-white">Manage company profile <ArrowRight size={15}/></Link><Link href="/employers/custom-portal/requests" className="inline-flex items-center gap-2 text-sm font-bold text-violet-200">My portal projects <ArrowRight size={15}/></Link></div></div></div></section>

  <section><div className="flex flex-wrap items-end justify-between gap-5"><div><p className="text-xs font-black uppercase tracking-[.2em] text-violet-700">Choose what you want to do</p><h2 className="mt-2 text-4xl font-semibold tracking-[-.045em] text-zinc-950 sm:text-5xl">Six focused business workspaces.</h2></div><p className="max-w-xl text-sm leading-6 text-zinc-600">Each path has its own purpose. Open only what is relevant to your organisation today.</p></div><div className="mt-7 grid gap-5 md:grid-cols-2 xl:grid-cols-3">{worlds.map(({icon:Icon,eyebrow,title,text,href,cta,tone},index)=><article key={title} className="group relative overflow-hidden rounded-[2.25rem] border border-violet-100 bg-white p-7 shadow-[0_25px_70px_-50px_rgba(55,30,75,.55)] transition hover:-translate-y-1 hover:shadow-xl"><div className="flex items-start justify-between gap-4"><span className={`grid h-12 w-12 place-items-center rounded-2xl ${toneClasses[tone]}`}><Icon size={22}/></span><span className="text-xs font-black text-violet-200">0{index+1}</span></div><p className="mt-6 text-xs font-black uppercase tracking-[.16em] text-violet-700">{eyebrow}</p><h3 className="mt-2 text-2xl font-bold tracking-[-.03em] text-zinc-950">{title}</h3><p className="mt-3 min-h-20 text-sm leading-6 text-zinc-600">{text}</p><Link href={href} className="mt-6 inline-flex items-center gap-2 text-sm font-black text-violet-950">{cta}<ArrowRight className="transition group-hover:translate-x-1" size={16}/></Link></article>)}</div></section>

  <section className="grid gap-5 lg:grid-cols-[1.15fr_.85fr]"><div className="rounded-[2.5rem] border border-violet-100 bg-gradient-to-br from-violet-50 to-white p-7 sm:p-9"><p className="flex items-center gap-2 text-xs font-black uppercase tracking-[.18em] text-violet-700"><Layers3 size={15}/> What JobiVerse can connect</p><h2 className="mt-3 text-3xl font-semibold tracking-[-.04em] text-zinc-950">One account, multiple outcomes.</h2><div className="mt-6 grid gap-3 sm:grid-cols-2">{["Company identity and controlled team access","Custom industry and operations modules","Recruitment, interviews and joining","Consulting-firm client workflows","Business services and expert support","Plans, billing and performance visibility"].map(item=><p key={item} className="flex gap-3 rounded-2xl bg-white p-4 text-sm font-semibold text-zinc-700"><BadgeCheck className="shrink-0 text-violet-700" size={17}/>{item}</p>)}</div></div><div className="rounded-[2.5rem] bg-zinc-950 p-7 text-white sm:p-9"><Sparkles className="text-violet-300"/><p className="mt-5 text-xs font-black uppercase tracking-[.18em] text-violet-300">Need direction?</p><h2 className="mt-3 text-3xl font-semibold tracking-[-.04em]">Tell us the outcome, not the software.</h2><p className="mt-4 text-sm leading-6 text-zinc-400">JobiVerse can help you choose between the standard Employer Hub, consulting workspace or a fully customised portal.</p><div className="mt-6 flex flex-col gap-3"><Link href="/contact" className="inline-flex min-h-12 items-center justify-center gap-2 rounded-2xl bg-white px-5 font-bold text-zinc-950"><Headphones size={17}/> Talk to JobiVerse</Link><Link href="/guides/employer" className="inline-flex min-h-12 items-center justify-center gap-2 rounded-2xl border border-white/15 px-5 font-bold"><Settings2 size={17}/> Employer guide</Link></div></div></section>
</div>}
