export type CreatorServiceAudience = "professional" | "student" | "employer";
export type CreatorServiceOption = { title: string; description: string };

export const creatorServiceGroups: Array<{ audience: CreatorServiceAudience; label: string; description: string; services: CreatorServiceOption[] }> = [
  { audience: "professional", label: "Professional Services", description: "Career growth, profile building and transition support.", services: [
    { title: "Editable CV Template", description: "Original editable DOCX or PPTX CV templates." }, { title: "Resume Writing", description: "Professional ATS-ready resumes from scratch." }, { title: "Resume Review & Optimization", description: "Expert review and improvement of existing resumes." }, { title: "Cover Letter Writing", description: "Role-specific cover letters with compelling positioning." }, { title: "LinkedIn Profile Optimization", description: "Stronger visibility, credibility and recruiter discovery." }, { title: "Portfolio Building", description: "Premium portfolios for projects and achievements." }, { title: "Career Guidance", description: "Personalized role selection and practical career planning." }, { title: "Career Transition Consulting", description: "Plans for moving into a new role or industry." }, { title: "Interview Preparation", description: "Structured preparation for upcoming interviews." }, { title: "Mock Interview", description: "Role-specific practice with actionable feedback." }, { title: "Salary Negotiation Coaching", description: "Preparation for compensation and offer conversations." }, { title: "Skill Gap Analysis", description: "Focused assessment and skill-development roadmap." }, { title: "Industry Mentorship", description: "One-to-one guidance from experienced professionals." }, { title: "Leadership Coaching", description: "Support for managers and senior professionals." }, { title: "Personal Branding", description: "A consistent and credible professional identity." },
  ]},
  { audience: "student", label: "Student & Graduate Services", description: "First-job readiness, direction and employability support.", services: [
    { title: "Student Resume Building", description: "Strong first resumes for limited experience." }, { title: "Fresher Resume Review", description: "Improve projects, skills and ATS readiness." }, { title: "Career Discovery Session", description: "Explore career paths based on strengths." }, { title: "First Job Preparation", description: "A complete strategy for entering the workforce." }, { title: "Campus Interview Preparation", description: "Aptitude, HR and placement interview practice." }, { title: "Fresher Mock Interview", description: "Confidence through realistic interview practice." }, { title: "Internship Guidance", description: "Plan, search and prepare for valuable internships." }, { title: "Project & Portfolio Guidance", description: "Present academic and personal projects professionally." }, { title: "Skill Roadmap", description: "A practical learning plan for a target role." }, { title: "Employability Assessment", description: "Evaluate job readiness and improvement areas." }, { title: "Study & Course Guidance", description: "Choose courses aligned with career outcomes." }, { title: "Communication Coaching", description: "Improve professional and interview communication." }, { title: "Personal Mentorship", description: "Ongoing guidance during early career decisions." },
  ]},
  { audience: "employer", label: "Employer Services", description: "Specialized hiring, screening and people advisory support.", services: [
    { title: "Job Description Writing", description: "Clear, market-ready job descriptions." }, { title: "Hiring Consultation", description: "Requirement, process and talent strategy support." }, { title: "Candidate Screening", description: "Profile evaluation against role requirements." }, { title: "Technical Interview Support", description: "Structured technical interview support." }, { title: "HR Interview Support", description: "Behavioral and culture-fit assessment." }, { title: "Interview Framework Design", description: "Consistent scorecards and evaluation criteria." }, { title: "Recruitment Process Audit", description: "Review and improve the hiring workflow." }, { title: "Talent Market Mapping", description: "Talent, competitor and market intelligence." }, { title: "Compensation Benchmarking", description: "Realistic and competitive salary ranges." }, { title: "Employer Branding Consultation", description: "Improve candidate perception of the organization." }, { title: "Bulk Hiring Support", description: "Structured high-volume hiring execution." }, { title: "Executive Search Consulting", description: "Leadership and specialized hiring advisory." },
  ]},
];
