import { expect, test, type Page } from "@playwright/test";

type Role="candidate"|"student"|"employer"|"recruiter"|"creator"|"admin";
function hasAccount(role:Role){const prefix=`TEST_${role.toUpperCase()}`;return Boolean(process.env[`${prefix}_EMAIL`]&&process.env[`${prefix}_PASSWORD`])}
function account(role:Role){const prefix=`TEST_${role.toUpperCase()}`;const email=process.env[`${prefix}_EMAIL`];const password=process.env[`${prefix}_PASSWORD`];if(!email||!password)throw new Error(`${prefix}_EMAIL and ${prefix}_PASSWORD must be configured.`);return{email,password}}
async function login(page:Page,role:Role,expected:RegExp){const credentials=account(role);await page.goto(`/login/${role}`);const privacyChoice=page.getByRole("button",{name:"Essential only"});const privacyVisible=await privacyChoice.waitFor({state:"visible",timeout:5_000}).then(()=>true).catch(()=>false);if(privacyVisible)await privacyChoice.click();await page.getByPlaceholder("Email address").fill(credentials.email);await page.getByPlaceholder("Password").fill(credentials.password);await page.waitForTimeout(1500);for(let attempt=0;attempt<3;attempt++){await page.getByRole("button",{name:"Continue"}).click();const moved=await page.waitForURL(expected,{timeout:25_000}).then(()=>true).catch(()=>false);if(moved){await expect(page.locator("body")).not.toContainText(/Application error|Internal Server Error|Runtime Error|Worker exceeded resource limits/i);return}const error=await page.locator('[role="alert"]').filter({hasText:/\S/}).textContent().catch(()=>null);if(error&&!/unexpected response|temporar|try again/i.test(error))throw new Error(`${role} login failed: ${error}`);await page.waitForTimeout(2_000)}throw new Error(`${role} login did not redirect after three attempts.`)}

test.describe("Public platform smoke coverage",()=>{
  for(const route of ["/","/services","/students","/candidates","/employers","/about","/contact","/marketplace"]){test(`${route} renders without a runtime failure`,async({page})=>{await page.goto(route);await expect(page.locator("body")).not.toContainText(/Application error|Internal Server Error|Runtime Error/i);await expect(page.locator("main").last()).toBeVisible()})}
  test("employer marketplace filter hides unrelated audiences",async({page})=>{await page.goto("/marketplace?audience=employer");await expect(page.getByText("For Employers",{exact:true})).toBeVisible();await expect(page.getByText("For Professionals",{exact:true})).toHaveCount(0);await expect(page.getByText("For Students & Graduates",{exact:true})).toHaveCount(0)})
  test("SEO endpoints are available",async({request})=>{for(const route of ["/robots.txt","/sitemap.xml","/manifest.webmanifest"]){const response=await request.get(route);expect(response.ok(),`${route} should respond successfully`).toBeTruthy()}})
  test("PWA manifest, service worker and offline fallback are available",async({request,page})=>{const manifestResponse=await request.get("/manifest.webmanifest");expect(manifestResponse.ok()).toBeTruthy();const manifest=await manifestResponse.json();expect(manifest).toMatchObject({name:"JobiVerse - Hiring & Career Platform",display:"standalone",scope:"/"});expect(manifest.icons).toEqual(expect.arrayContaining([expect.objectContaining({sizes:"192x192"}),expect.objectContaining({sizes:"512x512"})]));const worker=await request.get("/sw.js");expect(worker.ok()).toBeTruthy();expect(await worker.text()).toContain("jobiverse-pwa-v2");await page.goto("/offline");await expect(page.getByRole("heading",{name:"JobiVerse will reconnect shortly."})).toBeVisible()})
  test("unknown routes use the JobiVerse recovery page",async({page})=>{const response=await page.goto("/this-page-does-not-exist");expect(response?.status()).toBe(404);await expect(page.getByText("This page is not in orbit.")).toBeVisible()})
  test("private data export rejects anonymous access",async({request})=>{const response=await request.get("/api/account/data-export");expect(response.status()).toBe(401)})
  test("analytics remains off before explicit consent",async({page})=>{await page.goto("/");await expect(page.locator('script[src*="googletagmanager"]')).toHaveCount(0)})
});

test.describe("Role workspace regression coverage",()=>{
  test.describe.configure({timeout:240_000});
  test("student opens dedicated dashboard and fresh opportunities",async({page})=>{test.skip(!hasAccount("student"),"Student test credentials are not configured.");await login(page,"student",/\/students\/dashboard(?:[?#]|$)/);await expect(page.getByText("Student Universe").first()).toBeVisible();await page.goto("/students/jobs");await expect(page.locator("main").last()).toBeVisible()});
  test("candidate opens dashboard, jobs and career activity",async({page})=>{test.skip(!hasAccount("candidate"),"Candidate test credentials are not configured.");await login(page,"candidate",/\/candidates\/dashboard(?:[?#]|$)/);await expect(page.getByText("Talent workspace")).toBeVisible();await page.goto("/candidates/jobs");await expect(page).toHaveURL(/\/jobs(?:[?#]|$)/);await expect(page.locator("main").last()).toBeVisible();await page.goto("/candidates/applications");await expect(page.getByRole("heading",{name:"Career activity."})).toBeVisible()});
  test("employer retains employer navigation on filtered services",async({page})=>{test.skip(!hasAccount("employer"),"Employer test credentials are not configured.");await login(page,"employer",/\/employers\/(?:dashboard|company)(?:[?#]|$)/);await page.goto("/employers/dashboard");await expect(page.getByRole("heading",{name:"Six focused business workspaces."})).toBeVisible();await page.goto("/employers/custom-portal/requests");await expect(page.getByText("DEMO-OPS-001",{exact:true})).toBeVisible();await page.getByRole("link",{name:/DEMO-OPS-001/}).click();await expect(page).toHaveURL(/\/employers\/custom-portal\/requests\/[^/?#]+/);await expect(page.getByRole("heading",{name:"Proposal JOV-DEMO-001"})).toBeVisible();await expect(page.locator("strong").filter({hasText:"Annual access"})).toContainText("₹4,999/year");await page.goto("/marketplace?audience=employer");await expect(page.getByRole("link",{name:"Dashboard",exact:true})).toBeVisible();await expect(page.getByRole("link",{name:"Employer Guide",exact:true})).toBeVisible();await expect(page.getByText("For Employers",{exact:true})).toBeVisible();await expect(page.getByText("For Professionals",{exact:true})).toHaveCount(0)});
  test("recruiter reaches its command center and candidates workspace",async({page})=>{test.skip(!hasAccount("recruiter"),"Recruiter test credentials are not configured.");await login(page,"recruiter",/^https?:\/\/[^/]+\/recruiter(?:\/)?(?:[?#].*)?$/);await expect(page.getByText("Recruiter command center")).toBeVisible();await page.goto("/recruiter/candidates");await expect(page.locator("main").last()).toBeVisible()});
  test("creator reaches service and earnings workspaces",async({page})=>{test.skip(!hasAccount("creator"),"Creator test credentials are not configured.");await login(page,"creator",/\/earn-with-jobiverse\/dashboard(?:[?#]|$)/);await expect(page.getByText("Creator workspace").first()).toBeVisible();await page.goto("/earn-with-jobiverse/dashboard/earnings");await expect(page.getByRole("heading",{name:"Earnings & payouts."})).toBeVisible()});
  test("admin reaches analytics and template moderation",async({page})=>{test.skip(!hasAccount("admin"),"Admin test credentials are not configured.");await login(page,"admin",/^https?:\/\/[^/]+\/admin(?:\/)?(?:[?#].*)?$/);await page.goto("/admin/custom-portals");await expect(page.getByText("DEMO-OPS-001",{exact:true})).toBeVisible();const studioLink=page.locator("article").filter({hasText:"DEMO-OPS-001"}).getByRole("link",{name:/Open complete project studio/});const studioHref=await studioLink.getAttribute("href");expect(studioHref).toBeTruthy();await page.goto(studioHref!);await expect(page.getByPlaceholder("Proposal number")).toHaveValue("JOV-DEMO-001");await page.goto("/admin/companies");await expect(page.getByRole("heading",{name:"Company Management"})).toBeVisible();await page.goto("/admin/analytics");await expect(page.getByRole("heading",{name:"Hiring Analytics."})).toBeVisible();await page.goto("/admin/templates");await expect(page.getByRole("heading",{name:"CV Template Center"})).toBeVisible()});
});

test.describe("Access-control smoke coverage",()=>{
  test("anonymous user cannot stay on protected workspaces",async({page})=>{test.setTimeout(120_000);for(const route of ["/admin/finance","/employers/dashboard","/recruiter","/candidates/dashboard","/earn-with-jobiverse/dashboard","/employers/requirements/new","/earn-with-jobiverse/dashboard/services/new","/candidates/interview-prep","/hiring/applications/00000000-0000-0000-0000-000000000000"]){await page.goto(route,{waitUntil:"domcontentloaded"}).catch(()=>null);await expect(page).not.toHaveURL(new RegExp(`${route.replaceAll("/","\\/")}$`))}})
});
