import Link from "next/link";
import { notFound } from "next/navigation";
import { ArrowLeft, BadgeCheck, BriefcaseBusiness, Building2, ExternalLink, GraduationCap, MapPin, ShieldCheck, UsersRound } from "lucide-react";

import ApplyButton from "@/components/candidate/ApplyButton";
import { ReportJobForm } from "@/components/candidate/ReportJobForm";
import { SaveJobButton } from "@/components/candidate/SaveJobButton";
import { requireRole } from "@/lib/auth/authorization";
import { adminSupabase } from "@/lib/supabase/admin";

export default async function CandidateJobDetailPage({params}:{params:Promise<{id:string}>}) {
  const {id}=await params;const{supabase,user}=await requireRole(["candidate"]);
  const[{data:job},{data:application},{data:saved},{data:profile}]=await Promise.all([
    adminSupabase.from("requirements").select("id,job_title,department,employment_type,work_mode,experience,vacancies,budget_ctc,location,notice_period,primary_skills,education,job_description,status,is_public,published_at,company_id,employer_id,companies(company_name,is_verified,industry,website,location,description,company_size)").eq("id",id).eq("is_public",true).not("status","in",'("Closed","Cancelled")').maybeSingle(),
    supabase.from("candidate_applications").select("id").eq("candidate_user_id",user.id).eq("requirement_id",id).maybeSingle(),
    supabase.from("candidate_saved_jobs").select("id").eq("candidate_user_id",user.id).eq("requirement_id",id).maybeSingle(),
    supabase.from("candidate_profiles").select("resume_path,profile_completion,phone,current_location,total_experience,current_company,current_ctc,expected_ctc,notice_period,primary_skills,linkedin").eq("user_id",user.id).maybeSingle(),
  ]);
  if(!job)notFound();const relatedCompany=job.companies?.[0]??null;const{data:fallbackCompany}=relatedCompany?{data:null}:await adminSupabase.from("companies").select("company_name,is_verified,industry,website,location,description,company_size").eq("owner_id",job.employer_id).maybeSingle();const company=relatedCompany??fallbackCompany;const{data:identity}=await supabase.from("users").select("full_name,email").eq("id",user.id).maybeSingle();
  return <main className="min-h-screen bg-[#f5f5f3] px-5 pb-24 pt-36 sm:px-8"><div className="mx-auto max-w-6xl"><Link href="/candidates/jobs" className="inline-flex items-center gap-2 text-sm font-semibold text-zinc-600"><ArrowLeft size={16}/>All active jobs</Link>
    <section className="mt-7 overflow-hidden rounded-[2.75rem] bg-zinc-950 p-8 text-white sm:p-12"><div className="flex flex-wrap items-start justify-between gap-5"><div><div className="flex flex-wrap items-center gap-2 text-sm text-zinc-400"><span>{company?.company_name??"Confidential company"}</span>{company?.is_verified&&<span className="inline-flex items-center gap-1 rounded-full bg-emerald-400/15 px-3 py-1 text-xs font-semibold text-emerald-300"><BadgeCheck size={13}/>Verified employer</span>}</div><h1 className="mt-4 text-4xl font-semibold tracking-[-.04em] sm:text-6xl">{job.job_title}</h1><p className="mt-5 flex flex-wrap gap-x-5 gap-y-2 text-sm text-zinc-400"><span className="inline-flex items-center gap-2"><MapPin size={15}/>{job.location||"India"}</span><span>{job.work_mode||"Flexible"}</span><span>{job.employment_type||"Employment type not specified"}</span></p></div><span className="rounded-full bg-white/10 px-4 py-2 text-xs font-bold uppercase text-zinc-200">Actively hiring</span></div></section>
    <div className="mt-7 grid gap-6 lg:grid-cols-[1fr_340px]"><div className="space-y-6"><section className="rounded-[2rem] border border-zinc-200 bg-white p-7"><h2 className="text-2xl font-bold">Role overview</h2><div className="mt-6 grid gap-3 sm:grid-cols-2 lg:grid-cols-3"><Detail label="Experience" value={job.experience}/><Detail label="Openings" value={String(job.vacancies||1)}/><Detail label="Budget CTC" value={job.budget_ctc}/><Detail label="Department" value={job.department}/><Detail label="Notice period" value={job.notice_period}/><Detail label="Education" value={job.education}/></div></section>
      <section className="rounded-[2rem] border border-zinc-200 bg-white p-7"><h2 className="text-2xl font-bold">Complete job description</h2><p className="mt-5 whitespace-pre-wrap leading-8 text-zinc-600">{job.job_description||"The employer will share additional role details during the hiring process."}</p></section>
      <section className="rounded-[2rem] border border-zinc-200 bg-white p-7"><h2 className="text-2xl font-bold">Essential skills</h2><p className="mt-4 whitespace-pre-wrap rounded-2xl bg-zinc-50 p-5 leading-7 text-zinc-600">{job.primary_skills||"Skills are described in the complete job description."}</p></section>
      <section className="rounded-[2rem] border border-zinc-200 bg-white p-7"><div className="flex items-center gap-3"><Building2/><h2 className="text-2xl font-bold">About the employer</h2></div><div className="mt-5 flex flex-wrap items-center gap-2"><p className="text-xl font-semibold">{company?.company_name??"Confidential company"}</p>{company?.is_verified&&<BadgeCheck size={17} className="text-emerald-600"/>}</div>{company?.description&&<p className="mt-4 leading-7 text-zinc-600">{company.description}</p>}<div className="mt-5 flex flex-wrap gap-4 text-sm text-zinc-500"><span>{company?.industry||"Industry not specified"}</span><span>{company?.company_size||"Company size not specified"}</span><span>{company?.location||"Location not specified"}</span>{company?.website&&<a href={normalizeUrl(company.website)} target="_blank" rel="noreferrer" className="inline-flex items-center gap-1 font-semibold underline">Company website<ExternalLink size={13}/></a>}</div></section></div>
      <aside className="space-y-5 lg:sticky lg:top-32 lg:self-start"><section className="rounded-[2rem] border border-zinc-200 bg-white p-6 shadow-xl"><p className="text-xs font-bold uppercase tracking-wider text-zinc-400">Interested in this role?</p><div className="mt-5 space-y-3"><ApplyButton requirementId={job.id} applied={Boolean(application)} hasResume={Boolean(profile?.resume_path)} initialData={{fullName:identity?.full_name??"",email:identity?.email??user.email??"",phone:profile?.phone??"",currentLocation:profile?.current_location??"",totalExperience:profile?.total_experience??"",currentCompany:profile?.current_company??"",currentCtc:profile?.current_ctc??"",expectedCtc:profile?.expected_ctc??"",noticePeriod:profile?.notice_period??"",primarySkills:profile?.primary_skills??"",linkedin:profile?.linkedin??""}}/><SaveJobButton requirementId={job.id} saved={Boolean(saved)}/></div><p className="mt-4 text-xs leading-5 text-zinc-400">Review your application details before submitting them to the hiring workflow.</p></section><section className="rounded-[2rem] bg-zinc-950 p-6 text-white"><ShieldCheck/><h2 className="mt-4 font-bold">Candidate safety</h2><p className="mt-2 text-sm leading-6 text-zinc-400">Never pay for an application or interview. Report suspicious requests privately.</p></section><ReportJobForm requirementId={job.id}/></aside></div>
  </div></main>;
}

function Detail({label,value}:{label:string;value?:string|null}){return <div className="rounded-xl bg-zinc-50 p-4"><p className="text-[10px] font-bold uppercase tracking-wider text-zinc-400">{label}</p><p className="mt-1 font-semibold text-zinc-700">{value||"Not specified"}</p></div>}
function normalizeUrl(value:string){return /^https?:\/\//i.test(value)?value:`https://${value}`}
