import Link from "next/link";
import { ArrowLeft, BriefcaseBusiness, FileText, MessageSquareText } from "lucide-react";
import { notFound } from "next/navigation";
import { adminSupabase } from "@/lib/supabase/admin";
import { requireRole } from "@/lib/auth/authorization";
import { respondToEmploymentOffer, sendApplicationMessage, sendEmploymentOffer } from "./actions";
import { PrintButton } from "@/components/billing/print-button";

export const dynamic = "force-dynamic";

export default async function HiringApplicationWorkspace({ params }: { params: Promise<{ id: string }> }) {
  const { id } = await params;
  const { user, profile } = await requireRole(["candidate", "employer", "admin"]);
  const { data: application } = await adminSupabase.from("candidate_applications").select("id,candidate_user_id,applicant_name,status,requirements(id,job_title,location,employer_id,companies(company_name))").eq("id", id).maybeSingle();
  if (!application) notFound();
  const requirement = Array.isArray(application.requirements) ? application.requirements[0] : application.requirements;
  const allowed = profile.role === "admin" || application.candidate_user_id === user.id || requirement?.employer_id === user.id;
  if (!allowed) notFound();
  const [{ data: messages }, { data: offer }] = await Promise.all([
    adminSupabase.from("application_messages").select("id,sender_id,body,attachment_url,attachment_name,created_at,users(full_name,email)").eq("application_id", id).order("created_at"),
    adminSupabase.from("employment_offers").select("id,annual_ctc,work_location,joining_date,terms,status,candidate_response,counter_annual_ctc,sent_at,responded_at").eq("application_id", id).maybeSingle(),
  ]);
  const isCandidate = application.candidate_user_id === user.id;
  const isEmployer = requirement?.employer_id === user.id;
  const currency = new Intl.NumberFormat("en-IN", { style: "currency", currency: "INR", maximumFractionDigits: 0 });
  return <main className="min-h-screen bg-[#f5f5f3] px-5 pb-24 pt-36 sm:px-8"><div className="mx-auto max-w-6xl">
    <Link href={isCandidate ? "/candidates/applications" : "/employers/external-applicants"} className="inline-flex items-center gap-2 text-sm font-semibold text-zinc-600"><ArrowLeft size={16}/>Back</Link>
    <section className="mt-7 rounded-[2.75rem] bg-zinc-950 p-8 text-white sm:p-12"><BriefcaseBusiness/><p className="mt-5 text-xs font-bold uppercase tracking-[.18em] text-zinc-500">Hiring collaboration workspace</p><h1 className="mt-3 text-4xl font-semibold">{requirement?.job_title || "Application"}</h1><p className="mt-3 text-zinc-400">{requirement?.companies?.[0]?.company_name || "Employer"} · {application.applicant_name || "Candidate"} · {application.status}</p></section>
    <div className="mt-7 grid gap-6 lg:grid-cols-[1fr_420px]">
      <section className="rounded-[2rem] border border-zinc-200 bg-white p-6"><div className="flex items-center gap-3"><MessageSquareText/><div><p className="text-xs font-bold uppercase tracking-wider text-zinc-400">Application conversation</p><h2 className="text-2xl font-semibold">Keep decisions attached to the role</h2></div></div><div className="mt-6 max-h-[560px] space-y-3 overflow-y-auto">{messages?.length ? messages.map((message:any)=><article key={message.id} className={`max-w-[88%] rounded-2xl p-4 ${message.sender_id===user.id?"ml-auto bg-zinc-950 text-white":"bg-zinc-100"}`}><p className="text-xs font-bold opacity-60">{message.users?.full_name||message.users?.email||"Participant"}</p><p className="mt-2 whitespace-pre-wrap text-sm leading-6">{message.body}</p>{message.attachment_url&&<a href={message.attachment_url} target="_blank" rel="noreferrer" className="mt-3 inline-flex items-center gap-2 text-xs font-semibold underline"><FileText size={13}/>{message.attachment_name||"Open attachment"}</a>}<time className="mt-2 block text-[10px] opacity-50">{new Date(message.created_at).toLocaleString("en-IN")}</time></article>) : <p className="py-12 text-center text-sm text-zinc-400">No messages yet.</p>}</div>{profile.role!=="admin"&&<form action={sendApplicationMessage} className="mt-6 border-t pt-5"><input type="hidden" name="applicationId" value={id}/><textarea name="body" required maxLength={3000} rows={3} placeholder="Write an application update" className="w-full rounded-2xl border p-4"/><div className="mt-3 grid gap-3 sm:grid-cols-2"><input name="attachmentUrl" type="url" placeholder="Optional document link" className="rounded-xl border px-4 py-3 text-sm"/><input name="attachmentName" placeholder="Document name" className="rounded-xl border px-4 py-3 text-sm"/></div><button className="mt-3 rounded-xl bg-zinc-950 px-6 py-3 text-sm font-semibold text-white">Send message</button></form>}</section>
      <section className="rounded-[2rem] border border-zinc-200 bg-white p-6"><p className="text-xs font-bold uppercase tracking-wider text-zinc-400">Offer letter workspace</p><div className="flex flex-wrap items-center justify-between gap-3"><h2 className="mt-2 text-2xl font-semibold">Offer, response and negotiation</h2>{offer&&<PrintButton label="Download / print offer"/>}</div>{offer?<div className="mt-5 space-y-3"><Info label="Status" value={String(offer.status).replaceAll("_"," ")}/><Info label="Annual CTC" value={currency.format(offer.annual_ctc)}/><Info label="Joining date" value={offer.joining_date?new Date(`${offer.joining_date}T00:00:00`).toLocaleDateString("en-IN"):"To be agreed"}/><Info label="Work location" value={offer.work_location||"To be agreed"}/>{offer.terms&&<p className="rounded-2xl bg-zinc-50 p-4 text-sm leading-6 text-zinc-700">{offer.terms}</p>}{offer.counter_annual_ctc&&<Info label="Candidate counter" value={currency.format(offer.counter_annual_ctc)}/>} {offer.candidate_response&&<p className="rounded-2xl border p-4 text-sm">{offer.candidate_response}</p>}</div>:<p className="mt-5 text-sm text-zinc-500">No offer has been issued yet.</p>}
        {isEmployer&&<form action={sendEmploymentOffer} className="mt-6 space-y-3 border-t pt-5"><input type="hidden" name="applicationId" value={id}/><input name="annualCtc" required type="number" min={1} placeholder="Annual CTC" defaultValue={offer?.annual_ctc??""} className="h-12 w-full rounded-xl border px-4"/><input name="workLocation" placeholder="Work location" defaultValue={offer?.work_location??requirement?.location??""} className="h-12 w-full rounded-xl border px-4"/><input name="joiningDate" type="date" defaultValue={offer?.joining_date??""} className="h-12 w-full rounded-xl border px-4"/><textarea name="terms" maxLength={5000} rows={4} placeholder="Offer terms, probation, notice and benefits" defaultValue={offer?.terms??""} className="w-full rounded-xl border p-4"/><button className="w-full rounded-xl bg-zinc-950 px-5 py-3 font-semibold text-white">{offer?"Update and resend offer":"Send offer"}</button></form>}
        {isCandidate&&offer&&!["accepted","declined"].includes(offer.status)&&<form action={respondToEmploymentOffer} className="mt-6 space-y-3 border-t pt-5"><input type="hidden" name="applicationId" value={id}/><textarea name="response" maxLength={3000} rows={3} placeholder="Optional response or negotiation note" className="w-full rounded-xl border p-4"/><input name="counterAnnualCtc" type="number" min={1} placeholder="Counter annual CTC (for negotiation)" className="h-12 w-full rounded-xl border px-4"/><div className="grid grid-cols-3 gap-2"><button name="decision" value="accepted" className="rounded-xl bg-emerald-600 px-3 py-3 text-sm font-semibold text-white">Accept</button><button name="decision" value="countered" className="rounded-xl bg-amber-500 px-3 py-3 text-sm font-semibold text-white">Negotiate</button><button name="decision" value="declined" className="rounded-xl bg-red-600 px-3 py-3 text-sm font-semibold text-white">Decline</button></div></form>}
      </section>
    </div>
  </div></main>;
}

function Info({label,value}:{label:string;value:string}){return <div className="rounded-2xl bg-zinc-50 p-4"><p className="text-[10px] font-bold uppercase tracking-wider text-zinc-400">{label}</p><p className="mt-2 font-semibold capitalize">{value}</p></div>}

