import { Gift, Share2, UsersRound } from "lucide-react";
import { redirect } from "next/navigation";
import { createServerSupabaseClient } from "@/lib/supabase/server";
import { ReferralShareActions } from "@/components/referrals/copy-referral-link";

export default async function ReferralsPage(){
  const supabase=await createServerSupabaseClient();const{data:{user}}=await supabase.auth.getUser();if(!user)redirect("/login/candidate?next=/referrals");
  const[{data:profile},{data:referrals}]=await Promise.all([supabase.from("referral_profiles").select("referral_code,successful_referrals,reward_balance").eq("user_id",user.id).single(),supabase.from("referrals").select("id,status,reward_amount,created_at").eq("referrer_id",user.id).order("created_at",{ascending:false})]);
  const origin=process.env.NEXT_PUBLIC_SITE_URL||"http://localhost:3000";const link=`${origin}/signup?role=candidate&ref=${profile?.referral_code??""}`;
  return <main className="min-h-screen bg-[#f5f5f3] px-5 pb-24 pt-36 sm:px-8"><div className="mx-auto max-w-6xl"><section className="rounded-[2.75rem] bg-zinc-950 p-8 text-white sm:p-12"><Gift/><p className="mt-5 text-xs font-bold uppercase tracking-[.2em] text-zinc-500">JobiVerse referrals</p><h1 className="mt-3 text-4xl font-semibold sm:text-6xl">Grow the universe together.</h1><p className="mt-4 max-w-2xl text-zinc-400">Invite genuine professionals and students. Rewards activate only against published referral campaigns and verified qualifying actions.</p></section><section className="mt-7 grid gap-4 sm:grid-cols-3"><Metric icon={<UsersRound/>} label="Invited signups" value={referrals?.length??0}/><Metric icon={<Gift/>} label="Qualified referrals" value={profile?.successful_referrals??0}/><Metric icon={<Share2/>} label="Confirmed rewards" value={`₹${Number(profile?.reward_balance??0).toLocaleString("en-IN")}`}/></section><section className="mt-6 rounded-[2rem] border border-zinc-200 bg-white p-7"><h2 className="text-2xl font-bold">Your unique referral link</h2><p className="mt-2 text-sm text-zinc-500">Share it personally-spam, self-referrals and duplicate accounts are not eligible.</p><div className="mt-5 grid gap-3 lg:grid-cols-[1fr_auto]"><input readOnly value={link} className="h-13 min-w-0 rounded-xl border border-zinc-200 bg-zinc-50 px-4 text-sm"/><ReferralShareActions value={link}/></div><p className="mt-3 text-xs text-zinc-400">Code: {profile?.referral_code}</p></section><section className="mt-6 rounded-[2rem] border border-zinc-200 bg-white p-7"><h2 className="text-2xl font-bold">Referral activity</h2><div className="mt-5 space-y-3">{referrals?.length?referrals.map(item=><div key={item.id} className="flex items-center justify-between rounded-2xl bg-zinc-50 p-4"><div><p className="font-semibold capitalize">{item.status.replaceAll("_"," ")}</p><p className="mt-1 text-xs text-zinc-500">{new Date(item.created_at).toLocaleDateString("en-IN")}</p></div><span className="font-bold">₹{Number(item.reward_amount).toLocaleString("en-IN")}</span></div>):<p className="rounded-2xl border border-dashed p-10 text-center text-sm text-zinc-500">No referred signups yet.</p>}</div></section></div></main>;
}
function Metric({icon,label,value}:{icon:React.ReactNode;label:string;value:string|number}){return <article className="rounded-3xl border border-zinc-200 bg-white p-6">{icon}<p className="mt-5 text-sm text-zinc-500">{label}</p><p className="mt-2 text-3xl font-bold">{value}</p></article>}
