import type { Metadata } from "next";
import Link from "next/link";
import { notFound } from "next/navigation";
import { ArrowRight, BriefcaseBusiness, MapPin, ShieldCheck } from "lucide-react";

import { JOB_CITY_LANDINGS, JOB_ROLE_LANDINGS, getCityLanding } from "@/lib/jobs/seo-landings";

type Props={params:Promise<{city:string}>};
export function generateStaticParams(){return JOB_CITY_LANDINGS.map(item=>({city:item.slug}))}
export async function generateMetadata({params}:Props):Promise<Metadata>{const item=getCityLanding((await params).city);if(!item)return{};return{title:`Jobs in ${item.name} | JobiVerse`,description:`Explore current jobs in ${item.name} across technology, business, healthcare and more on JobiVerse.`,alternates:{canonical:`/jobs/in/${item.slug}`}}}
export default async function CityJobsLanding({params}:Props){const item=getCityLanding((await params).city);if(!item)notFound();const schema={"@context":"https://schema.org","@type":"CollectionPage",name:`Jobs in ${item.name}`,description:item.summary,url:`https://www.jobiverse.in/jobs/in/${item.slug}`};return <Landing title={`Jobs in ${item.name}`} eyebrow="City opportunity guide" summary={item.summary} browseHref={`/jobs?location=${encodeURIComponent(item.name)}`} schema={schema}><h2 className="text-3xl font-bold">Popular career paths in {item.name}</h2><div className="mt-5 grid gap-3 sm:grid-cols-2 lg:grid-cols-4">{JOB_ROLE_LANDINGS.map(role=><Link key={role.slug} href={`/jobs?q=${encodeURIComponent(role.query)}&location=${encodeURIComponent(item.name)}&sector=${role.sector}`} className="rounded-2xl border border-zinc-200 bg-white p-5 font-semibold transition hover:-translate-y-1 hover:shadow-lg">{role.name}<ArrowRight className="mt-5 text-zinc-400" size={17}/></Link>)}</div></Landing>}

function Landing({title,eyebrow,summary,browseHref,schema,children}:{title:string;eyebrow:string;summary:string;browseHref:string;schema:object;children:React.ReactNode}){return <main className="min-h-screen bg-[#f5f5f3] px-5 pb-24 pt-36 sm:px-8"><script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify(schema).replace(/</g,"\\u003c")}}/><div className="mx-auto max-w-6xl"><section className="overflow-hidden rounded-[3rem] bg-gradient-to-br from-zinc-950 via-zinc-900 to-violet-950 p-9 text-white sm:p-14"><p className="text-xs font-bold uppercase tracking-[.2em] text-violet-300">{eyebrow}</p><h1 className="mt-5 text-5xl font-semibold tracking-[-.055em] sm:text-7xl">{title}</h1><p className="mt-6 max-w-3xl text-lg leading-8 text-zinc-300">{summary}</p><Link href={browseHref} className="mt-8 inline-flex items-center gap-2 rounded-2xl bg-white px-6 py-4 font-bold text-zinc-950">Browse live opportunities<ArrowRight size={17}/></Link></section><section className="mt-8 grid gap-4 sm:grid-cols-3">{[[MapPin,"Location-aware search"],[BriefcaseBusiness,"Direct + partner roles"],[ShieldCheck,"Clear source attribution"]].map(([Icon,label]:any)=><div key={label} className="rounded-2xl border border-zinc-200 bg-white p-5"><Icon/><p className="mt-4 font-bold">{label}</p></div>)}</section><section className="mt-12">{children}</section></div></main>}

