import Link from "next/link";
import { ArrowLeft, Crown, FileText } from "lucide-react";
import { requireRole } from "@/lib/auth/authorization";
import ResumeStudio from "@/components/candidate/ResumeStudio";
import ResumeTemplateCatalog from "@/components/candidate/ResumeTemplateCatalog";
import { ResumeVersionHistory } from "@/components/candidate/ResumeVersionHistory";

export default async function CandidateResumePage({searchParams}:{searchParams:Promise<{updated?:string}>}) {
  const{updated}=await searchParams;const { supabase, user } = await requireRole(["candidate"]);
  const[{data:profile},{data:versions},{data:purchases}]=await Promise.all([supabase.from("candidate_profiles").select("resume_path").eq("user_id",user.id).maybeSingle(),supabase.from("candidate_resume_versions").select("id,storage_path,file_name,label,size_bytes,source,is_current,created_at").eq("candidate_user_id",user.id).order("created_at",{ascending:false}),supabase.from("resume_purchases").select("template_id").eq("user_id",user.id).order("created_at",{ascending:false})]);
  const { data: signedResume } = profile?.resume_path ? await supabase.storage.from("candidate-resumes").createSignedUrl(profile.resume_path, 3600) : { data: null };
  const versionsWithUrls=await Promise.all((versions??[]).map(async version=>{const{data}=await supabase.storage.from("candidate-resumes").createSignedUrl(version.storage_path,3600);return{...version,url:data?.signedUrl??null}}));
  const success=updated==="restored"?"Resume version restored and set as current.":updated==="renamed"?"Resume version renamed successfully.":updated==="duplicated"?"Resume version duplicated successfully.":null;
  return <main className="relative min-h-screen overflow-hidden bg-[#f5f5f3] px-5 pb-24 pt-36 sm:px-8"><div className="pointer-events-none absolute inset-0 bg-[radial-gradient(circle_at_10%_8%,white,transparent_27%),radial-gradient(circle_at_90%_18%,rgba(99,102,241,.12),transparent_24%)]"/><div className="relative mx-auto max-w-7xl"><Link href="/candidates/dashboard" className="inline-flex items-center gap-2 rounded-full border border-black/10 bg-white/80 px-4 py-2 text-sm font-medium text-zinc-700"><ArrowLeft size={16}/>Candidate Dashboard</Link><section className="my-8 rounded-[2.75rem] bg-gradient-to-br from-zinc-950 via-zinc-900 to-zinc-700 p-8 text-white shadow-2xl sm:p-12"><div className="flex items-end justify-between gap-8"><div><p className="text-xs font-bold uppercase tracking-[.22em] text-zinc-400">Resume Studio & Services</p><h1 className="mt-4 text-4xl font-semibold tracking-[-.045em] sm:text-6xl">Your career story,<br/><span className="text-zinc-400">professionally presented.</span></h1><p className="mt-5 max-w-2xl text-zinc-300">Manage your current CV, preserve every version and choose from handcrafted designs.</p></div><FileText className="hidden text-zinc-500 sm:block" size={72}/></div></section>{success&&<div className="mb-7 rounded-2xl border border-emerald-200 bg-emerald-50 p-4 text-sm font-semibold text-emerald-800">{success}</div>}<div className="grid gap-7 lg:grid-cols-[.9fr_1.1fr]"><ResumeStudio hasResume={Boolean(profile?.resume_path)} resumeUrl={signedResume?.signedUrl}/><div className="rounded-[2rem] bg-zinc-950 p-8 text-white shadow-2xl"><div className="flex items-center gap-3"><Crown className="text-zinc-400"/><div><p className="text-xs font-bold uppercase tracking-[.18em] text-zinc-500">Premium services</p><h2 className="mt-1 text-2xl font-semibold">Crafted beyond templates.</h2></div></div><p className="mt-5 leading-7 text-zinc-400">Professional writing, ATS-focused formatting and role-specific resume transformations will launch here.</p><span className="mt-7 inline-flex rounded-full border border-zinc-700 px-4 py-2 text-xs font-bold uppercase tracking-[.17em] text-zinc-300">Coming Soon</span></div></div><ResumeVersionHistory versions={versionsWithUrls}/><ResumeTemplateCatalog compact ownedTemplateIds={(purchases??[]).map(item=>item.template_id)}/></div></main>;
}
