import Link from "next/link";
import { redirect } from "next/navigation";
import { ArrowLeft, ShieldAlert } from "lucide-react";
import { createServerSupabaseClient } from "@/lib/supabase/server";
import { requestOrderRefund } from "./actions";

export default async function RefundRequestPage({params}:{params:Promise<{id:string}>}){const{id}=await params;const supabase=await createServerSupabaseClient();const{data:{user}}=await supabase.auth.getUser();if(!user)redirect(`/login/candidate?next=/marketplace/orders/${id}/refund`);const{data:order}=await supabase.from("marketplace_orders").select("id,amount,status,payout_status,service_title,marketplace_services(title)").eq("id",id).eq("customer_id",user.id).maybeSingle();if(!order)redirect("/marketplace/orders");const{data:existing}=await supabase.from("marketplace_refund_requests").select("status,reason,requested_at").eq("order_id",id).in("status",["requested","approved","gateway_pending","processed"]).maybeSingle();const service=Array.isArray(order.marketplace_services)?order.marketplace_services[0]:order.marketplace_services;return <main className="min-h-screen bg-[#f5f5f3] px-5 pb-24 pt-36 sm:px-8"><div className="mx-auto max-w-3xl"><Link href={`/marketplace/orders/${id}`} className="inline-flex items-center gap-2 text-sm font-semibold text-zinc-600"><ArrowLeft size={16}/>Back to order</Link><section className="mt-8 rounded-[2.75rem] bg-zinc-950 p-8 text-white sm:p-12"><ShieldAlert/><p className="mt-5 text-xs font-bold uppercase tracking-[.18em] text-zinc-500">Customer protection</p><h1 className="mt-3 text-4xl font-semibold">Request a refund.</h1><p className="mt-4 text-zinc-400">{service?.title??order.service_title??"Service order"} | INR {Number(order.amount).toLocaleString("en-IN")}</p></section>{existing?<section className="mt-7 rounded-[2rem] border border-amber-200 bg-amber-50 p-7"><h2 className="text-xl font-semibold">Refund {existing.status.replaceAll("_"," ")}</h2><p className="mt-3 text-sm text-zinc-600">{existing.reason}</p><p className="mt-3 text-xs text-zinc-500">Requested {new Date(existing.requested_at).toLocaleString("en-IN")}</p></section>:<form action={requestOrderRefund} className="mt-7 rounded-[2rem] border border-zinc-200 bg-white p-7"><input type="hidden" name="orderId" value={id}/><h2 className="text-2xl font-semibold">Tell us what happened</h2><p className="mt-2 text-sm leading-6 text-zinc-500">JobiVerse will review the order status, delivery and messages before approving. Approved Razorpay refunds may take 5-7 working days.</p><textarea name="reason" required minLength={10} maxLength={1000} rows={6} placeholder="Explain why you are requesting a refund" className="mt-6 w-full rounded-2xl border border-zinc-200 p-4 outline-none focus:border-zinc-500"/><button className="mt-4 cursor-pointer rounded-xl bg-zinc-950 px-6 py-3 text-sm font-semibold text-white">Submit refund request</button></form>}</div></main>}




