import { LegalDocument, type LegalSection } from "@/components/legal/legal-document";

const sections: LegalSection[] = [
  {title:"Who we are",content:<p>JobiVerse is operated as a proprietorship under the legal name MOHAMMAD AMIR MOHAMMAD ASLAM ANSARI, trade name JobiVerse, from Room No. 25, Plot No. 70, Malad (W), Mumbai, Maharashtra 400095, India. This policy applies to visitors, candidates, employers, recruiters, creators and customers using JobiVerse.</p>},
  {title:"Information we collect",content:<><p>We collect account and contact details; resumes, education, skills, employment and compensation information; employer and hiring-requirement details; creator profiles, service listings, tax and payout information; orders, negotiations, billing details, GSTIN where supplied, payments, refunds and receipts; interviews, applications, messages, files, reviews, reports and support requests.</p><p>We also receive security and technical information such as authentication events, device/browser data, IP-derived logs, cookies and platform activity needed to operate and protect the service. Payment-card credentials are handled by the payment gateway and are not intended to be stored by JobiVerse.</p></>},
  {title:"Why we use information",content:<p>We process information to create and secure accounts; provide recruitment, career and marketplace services; match candidates and roles; coordinate interviews and hiring; deliver purchases; process payments, refunds and creator payouts; issue billing records; prevent fraud and abuse; provide support and notifications; comply with law; and improve platform reliability. Optional marketing communication follows the preferences available in your account.</p>},
  {title:"How information is shared",content:<p>Candidate information may be shared with relevant employers and authorized recruiters for genuine hiring workflows. Marketplace information is shared between the customer, selected creator and JobiVerse to fulfil an order. Public creator listings, profile names, photos, ratings and reviews may be visible to visitors. We may use contracted providers for hosting, database, authentication, storage, payments, email, analytics and security, subject to appropriate access controls. We do not state that personal data is sold.</p>},
  {title:"AI-assisted features",content:<p>Paid AI features are currently marked Coming Soon. Before activation, JobiVerse will disclose the provider, purpose, relevant data flow and controls. Users should not submit confidential third-party information unless authorized. AI output may be incomplete or inaccurate and will not replace professional judgment.</p>},
  {title:"Retention and deletion",content:<p>We retain information only for the period reasonably needed for the service, security, dispute handling, accounting, tax and legal obligations. Different records require different periods: active recruitment records, order evidence, invoices and transaction records may not share the same deletion schedule. A deletion request may not remove information that must be retained by law, required to resolve a dispute, or contained in protected audit and financial records.</p>},
  {title:"Security",content:<p>JobiVerse uses authentication, role-based access, database row-level security, private storage where appropriate, signed file access, server-side secrets and operational logging. No internet service can promise absolute security. Users must protect their credentials and promptly report suspicious access.</p>},
  {title:"Your choices and requests",content:<p>You may update profile and notification preferences in your account and may request access, correction, deletion, withdrawal of consent where applicable, or grievance review by contacting JobiVerse. We may verify identity before acting and will explain when a request cannot be completed due to security, contractual or legal requirements.</p>},
  {title:"Children and student users",content:<p>JobiVerse includes services for students and recent graduates but is not designed for unsupervised use by children. A user who is below the legally applicable age should use the platform only with valid parent or guardian involvement and should not purchase services independently.</p>},
  {title:"Cookies and external links",content:<p>Essential cookies support authentication, session continuity and security. Optional analytics or advertising cookies should not be activated without appropriate notice and controls. JobiVerse may link to third-party websites; their privacy practices are governed by their own policies.</p>},
  {title:"Grievance and contact",content:<p>Privacy and grievance requests can be sent to jobiverse@outlook.com or +91 77388 32231. Include your registered email, the nature of the request and relevant order or application reference. We may update this policy as the platform or law changes and will publish the revised effective date.</p>},
];

export default function PrivacyPolicyPage(){return <LegalDocument title="Privacy Policy" description="How JobiVerse handles personal data across recruitment, careers, marketplace services and platform operations." sections={sections}/>;}
