import Link from "next/link";
import { ArrowRight, Bot, CalendarDays, GraduationCap, Handshake, IdCard, Sparkles, UsersRound } from "lucide-react";
const experiences=[
  {title:"Personal Consultations",text:"Book focused career, resume, interview or employer guidance.",href:"/consultations",icon:Handshake,label:"Book guidance"},
  {title:"Events & Workshops",text:"Discover webinars, career clinics, hiring drives and practical sessions.",href:"/events",icon:CalendarDays,label:"See upcoming events"},
  {title:"Campus Connect",text:"Structured employability and placement partnerships for institutions.",href:"/campus-partnerships",icon:GraduationCap,label:"Partner with JobiVerse"},
  {title:"JobiVerse Card",text:"Create one shareable identity for skills, work and credentials.",href:"/login/candidate?next=%2Fcareer-passport",icon:IdCard,label:"Build your card"},
  {title:"Plans",text:"Choose optional career acceleration or employer hiring support.",href:"/plans",icon:Sparkles,label:"Explore plans"},
  {title:"Referrals",text:"Invite genuine professionals and track eligible referral activity.",href:"/referrals",icon:UsersRound,label:"Open referrals"},
  {title:"Responsible AI",text:"Understand upcoming AI tools, safeguards and human-review boundaries.",href:"/ai",icon:Bot,label:"Explore AI"},
];
export function ExploreJobiVerse(){return <section className="bg-[#f6f6f3] px-5 py-24 sm:px-8"><div className="mx-auto max-w-[1450px]"><div className="grid gap-8 rounded-[3rem] bg-zinc-950 p-7 text-white shadow-2xl sm:p-12 lg:grid-cols-[.7fr_1.3fr]"><div className="lg:sticky lg:top-32 lg:self-start"><p className="text-xs font-bold uppercase tracking-[.2em] text-zinc-500">Explore the JobiVerse</p><h2 className="mt-5 text-4xl font-semibold tracking-[-.05em] sm:text-6xl">More than jobs.<br/><span className="text-zinc-500">A complete ecosystem.</span></h2><p className="mt-6 max-w-xl leading-7 text-zinc-400">Every new JobiVerse experience is available from one visible place. Explore as a professional, student, employer or institution.</p></div><div className="grid gap-3 md:grid-cols-2">{experiences.map(({title,text,href,icon:Icon,label},index)=><Link key={title} href={href} className={`group rounded-[2rem] border p-6 transition hover:-translate-y-1 ${index===0?"border-white/70 bg-white text-zinc-950 hover:border-white hover:bg-zinc-100 md:col-span-2":"border-white/10 bg-white/[.04] hover:border-white/25 hover:bg-white/[.08]"}`}><div className="flex items-start justify-between"><span className={`grid h-12 w-12 place-items-center rounded-2xl ${index===0?"bg-zinc-950 text-white":"bg-white/10"}`}><Icon size={21}/></span><ArrowRight className="transition group-hover:translate-x-1" size={18}/></div><h3 className="mt-6 text-xl font-bold">{title}</h3><p className={`mt-3 text-sm leading-6 ${index===0?"text-zinc-600":"text-zinc-400"}`}>{text}</p><p className="mt-5 text-xs font-bold uppercase tracking-wider">{label}</p></Link>)}</div></div></div></section>}
