"use client";

import Link from "next/link";
import { motion } from "framer-motion";
import { CountUp } from "@/components/motion/count-up";
import { WorkflowAnimation } from "@/components/motion/workflow-animation";
import { UniverseMotionPreview } from "@/components/motion/universe-motion-preview";
import { ArrowRight, BadgeCheck, BarChart3, BriefcaseBusiness, Building2, CalendarDays, CircleDollarSign, FileText, GraduationCap, IdCard, MessageSquareText, Palette, Search, ShieldCheck, Sparkles, Target, UsersRound, WalletCards } from "lucide-react";

const gateways = [
  { title: "Professionals", label: "Move your career forward", href: "/candidates", icon: UsersRound },
  { title: "Students", label: "Build your first career", href: "/students", icon: GraduationCap },
  { title: "Employers", label: "Build the right team", href: "/employers", icon: Building2 },
  { title: "Creators", label: "Turn expertise into income", href: "/earn-with-jobiverse", icon: Palette },
];

const professionalFeatures = ["Job discovery, filters and comparison", "JobiVerse Card and Open to Work", "Applications, interviews and offers", "Resume Studio, alerts and career support"];
const studentFeatures = ["Student profile for academics and projects", "Freshers, internships and graduate jobs", "First resume and interview preparation", "Campus programmes and career services"];
const employerFeatures = ["Company workspace and quality requirements", "Direct, recruiter and JobiVerse candidates", "Interview calendar and offer workflow", "Team seats, reports and paid Talent Search"];
const creatorFeatures = ["Career services and template storefront", "Offers, orders, delivery and revisions", "Sessions, availability and customer messages", "Earnings ledger, payouts and statements"];

function FeatureList({items,dark=false}:{items:string[];dark?:boolean}) { return <div className="mt-8 grid gap-3 sm:grid-cols-2">{items.map(item=><div key={item} className={`flex items-start gap-3 rounded-2xl p-4 text-sm leading-6 ${dark?"border border-white/10 bg-white/[.06] text-zinc-300":"border border-violet-100 bg-white text-zinc-700"}`}><BadgeCheck className={`mt-0.5 shrink-0 ${dark?"text-violet-300":"text-violet-700"}`} size={17}/>{item}</div>)}</div> }

export function UniverseHome() {
  return <>
    <section className="bg-[#f8f6fa] px-5 pb-16 pt-28 sm:px-8">
      <div className="jv-brand-gradient jv-noise relative mx-auto max-w-[1450px] overflow-hidden rounded-[3rem] px-7 py-20 text-white shadow-[0_45px_120px_-45px_rgba(38,20,52,.82)] sm:px-12 lg:px-16 lg:py-24">
        <div className="jv-hero-orb pointer-events-none absolute left-[8%] top-[12%] h-44 w-44 rounded-full border border-violet-300/20 bg-violet-500/5"/><div className="pointer-events-none absolute -right-36 -top-40 h-[34rem] w-[34rem] rounded-full border border-white/10"/><div className="pointer-events-none absolute right-8 top-8 h-64 w-64 rounded-full bg-violet-500/10 blur-3xl"/>
        <div className="relative z-10 mx-auto max-w-5xl text-center"><span className="inline-flex items-center gap-2 rounded-full border border-white/15 bg-white/10 px-4 py-2 text-xs font-bold uppercase tracking-[.18em] text-violet-100"><Sparkles size={15}/> Welcome to JobiVerse</span><motion.h1 initial={{opacity:0,y:20}} animate={{opacity:1,y:0}} className="mt-7 text-5xl font-semibold leading-[.92] tracking-[-.06em] sm:text-7xl lg:text-8xl">Four universes.<br/><span className="text-violet-300">Four ways to grow.</span></motion.h1><p className="mt-7 max-w-3xl text-lg leading-8 text-zinc-300 sm:text-xl">Choose the universe built around your next outcome. Every space has its own tools, workflow and dashboard—not one generic experience for everyone.</p></div>
        <div className="relative z-10 mt-12 grid gap-3 md:grid-cols-2 xl:grid-cols-4">{gateways.map(({title,label,href,icon:Icon},index)=><motion.a key={title} href={href} initial={{opacity:0,y:18}} animate={{opacity:1,y:0}} transition={{delay:.12+index*.06}} className="jv-universe-gateway jv-spotlight group flex min-h-44 flex-col justify-between rounded-[2rem] border border-white/15 bg-white/[.08] p-6 backdrop-blur-xl transition hover:-translate-y-1 hover:border-violet-200/40 hover:bg-white/[.14]"><div className="flex items-start justify-between"><span className="grid h-11 w-11 place-items-center rounded-2xl bg-white text-violet-950"><Icon size={21}/></span><span className="text-xs font-black text-white/25">0{index+1}</span></div><div><UniverseMotionPreview type={(["professional","student","employer","creator"] as const)[index]}/><h2 className="mt-5 text-2xl font-black">{title}</h2><p className="mt-1 text-sm text-violet-200">{label}</p><span className="mt-4 inline-flex items-center gap-2 text-xs font-bold uppercase tracking-wider text-zinc-400">Enter universe<ArrowRight size={13} className="transition group-hover:translate-x-1"/></span></div></motion.a>)}</div>
      </div>
    </section>

    <section data-universe-tone="professional" id="professionals" className="scroll-mt-28 bg-[#f8f6fa] px-5 py-20 sm:px-8"><div className="mx-auto grid max-w-[1450px] gap-10 lg:grid-cols-[1.02fr_.98fr] lg:items-center"><div><span className="inline-flex items-center gap-2 rounded-full bg-violet-100 px-4 py-2 text-xs font-black uppercase tracking-[.18em] text-violet-800"><UsersRound size={15}/> Professional Universe</span><h2 className="mt-6 text-5xl font-semibold leading-[.95] tracking-[-.055em] sm:text-7xl">Your career deserves<br/><span className="text-violet-700">its own command centre.</span></h2><p className="mt-6 max-w-2xl text-lg leading-8 text-zinc-600">Build a credible professional identity, discover relevant roles and keep applications, interviews, offers and career growth connected.</p><FeatureList items={professionalFeatures}/><div className="mt-8 flex flex-wrap gap-3"><Link href="/candidates" className="jv-magnetic jv-brand-gradient inline-flex items-center gap-2 rounded-2xl px-6 py-4 font-bold text-white">Explore Professional Universe<ArrowRight size={17}/></Link><Link href="/login/candidate" className="rounded-2xl border border-violet-100 bg-white px-6 py-4 font-bold">Professional login</Link></div></div><div className="relative overflow-hidden rounded-[3rem] border border-violet-100 bg-white p-6 shadow-[0_35px_100px_-55px_rgba(55,30,75,.7)] sm:p-8"><div className="jv-brand-gradient rounded-[2.25rem] p-7 text-white"><div className="flex items-center justify-between"><div><p className="text-xs font-bold uppercase tracking-[.16em] text-violet-200">Career cockpit</p><h3 className="mt-2 text-3xl font-bold">Your next move</h3></div><IdCard size={38} className="text-violet-300"/></div><div className="mt-7 grid grid-cols-3 gap-3">{[["Profile","82%"],["Applications","12"],["Interviews","3"]].map(([label,value])=><div key={label} className="rounded-2xl bg-white/10 p-4"><p className="text-2xl font-black"><AnimatedMetric value={value}/></p><p className="mt-1 text-[10px] uppercase tracking-wider text-zinc-400">{label}</p></div>)}</div></div><div className="mt-4 grid gap-3 sm:grid-cols-2"><Preview icon={Search} title="Opportunity feed" text="Matched jobs, saves and alerts"/><Preview icon={FileText} title="Resume Studio" text="Versions, builder and templates"/><Preview icon={CalendarDays} title="Application Health" text="Interviews, offers and follow-ups"/><Preview icon={BarChart3} title="Card analytics" text="Visibility and profile insights"/></div></div></div></section>

    <section data-universe-tone="student" id="students" className="scroll-mt-28 bg-white px-5 py-24 sm:px-8"><div className="mx-auto grid max-w-[1450px] gap-10 lg:grid-cols-[.95fr_1.05fr] lg:items-center"><div className="order-2 rounded-[3rem] border border-violet-100 bg-[#faf8fc] p-6 sm:p-8 lg:order-1"><div className="grid gap-4 sm:grid-cols-2"><PreviewLarge icon={GraduationCap} title="Academic profile" text="College, degree, semester, CGPA and specialization."/><PreviewLarge icon={BriefcaseBusiness} title="Fresh opportunities" text="Internships, graduate, trainee and first-job collections."/><PreviewLarge icon={FileText} title="First resume" text="Projects, skills and education turned into potential."/><PreviewLarge icon={Target} title="Career readiness" text="Interview preparation, guidance and campus support."/></div><div className="jv-brand-gradient mt-4 rounded-[2rem] p-6 text-white"><p className="text-xs font-bold uppercase tracking-[.16em] text-violet-200">Designed to grow with you</p><p className="mt-3 text-xl font-bold">Student today. Professional tomorrow. Same career foundation.</p></div></div><div className="order-1 lg:order-2"><span className="inline-flex items-center gap-2 rounded-full bg-violet-100 px-4 py-2 text-xs font-black uppercase tracking-[.18em] text-violet-800"><GraduationCap size={15}/> Student Universe</span><h2 className="mt-6 text-5xl font-semibold leading-[.95] tracking-[-.055em] sm:text-7xl">Potential is more than<br/><span className="text-violet-700">past experience.</span></h2><p className="mt-6 max-w-2xl text-lg leading-8 text-zinc-600">Show academics, projects and early achievements. Discover fresher-friendly opportunities and prepare for the first move with less professional clutter.</p><FeatureList items={studentFeatures}/><div className="mt-8 flex flex-wrap gap-3"><Link href="/students" className="jv-brand-gradient inline-flex items-center gap-2 rounded-2xl px-6 py-4 font-bold text-white">Explore Student Universe<ArrowRight size={17}/></Link><Link href="/login/student" className="rounded-2xl border border-violet-100 bg-white px-6 py-4 font-bold">Student login</Link></div></div></div></section>

    <section data-universe-tone="employer" id="employers" className="scroll-mt-28 bg-[#f8f6fa] px-5 py-24 sm:px-8"><div className="jv-brand-gradient mx-auto max-w-[1450px] overflow-hidden rounded-[3rem] p-8 text-white sm:p-12 lg:p-16"><div className="grid gap-12 lg:grid-cols-[.92fr_1.08fr] lg:items-center"><div><span className="inline-flex items-center gap-2 rounded-full border border-white/15 bg-white/10 px-4 py-2 text-xs font-black uppercase tracking-[.18em] text-violet-200"><Building2 size={15}/> Employer Universe</span><h2 className="mt-6 text-5xl font-semibold leading-[.95] tracking-[-.055em] sm:text-7xl">From open role<br/><span className="text-violet-300">to successful joining.</span></h2><p className="mt-6 max-w-2xl text-lg leading-8 text-zinc-300">Give hiring teams one accountable workspace for requirements, candidate sources, recruiter collaboration, interviews, offers and reports.</p><FeatureList items={employerFeatures} dark/><div className="mt-8 flex flex-wrap gap-3"><Link href="/employers" className="inline-flex items-center gap-2 rounded-2xl bg-white px-6 py-4 font-bold text-zinc-950">Explore Employer Universe<ArrowRight size={17}/></Link><Link href="/login/employer" className="rounded-2xl border border-white/15 bg-white/10 px-6 py-4 font-bold">Employer login</Link></div></div><div className="rounded-[2.5rem] border border-white/15 bg-white/[.07] p-6 backdrop-blur-xl sm:p-8"><div className="flex items-center justify-between"><div><p className="text-xs font-bold uppercase tracking-[.16em] text-violet-200">Hiring command centre</p><h3 className="mt-2 text-3xl font-bold">Product Designer</h3></div><span className="rounded-full bg-emerald-400/15 px-3 py-1 text-xs font-bold text-emerald-300">Open</span></div><div className="mt-7 grid grid-cols-4 gap-2">{[["Applied","48"],["Review","14"],["Interview","6"],["Offer","2"]].map(([label,value])=><div key={label} className="rounded-2xl border border-white/10 bg-black/15 p-3 text-center"><p className="text-2xl font-black"><AnimatedMetric value={value}/></p><p className="mt-1 text-[9px] uppercase tracking-wider text-zinc-500">{label}</p></div>)}</div><WorkflowAnimation type="employer"/><div className="mt-4 space-y-3">{["Unified candidate pipeline","Interview calendar and feedback","Offer and joining tracker"].map((item,index)=><div key={item} className="flex items-center justify-between rounded-2xl border border-white/10 bg-white/[.06] p-4"><span className="flex items-center gap-3 text-sm font-semibold"><span className="grid h-8 w-8 place-items-center rounded-lg bg-white/10 text-xs">0{index+1}</span>{item}</span><ArrowRight size={15} className="text-zinc-500"/></div>)}</div></div></div></div></section>

    <section data-universe-tone="creator" id="creators" className="scroll-mt-28 bg-white px-5 py-24 sm:px-8"><div className="mx-auto grid max-w-[1450px] gap-10 lg:grid-cols-[1.02fr_.98fr] lg:items-center"><div><span className="inline-flex items-center gap-2 rounded-full bg-violet-100 px-4 py-2 text-xs font-black uppercase tracking-[.18em] text-violet-800"><Palette size={15}/> Creator Universe</span><h2 className="mt-6 text-5xl font-semibold leading-[.95] tracking-[-.055em] sm:text-7xl">Expertise becomes<br/><span className="text-violet-700">a real business.</span></h2><p className="mt-6 max-w-2xl text-lg leading-8 text-zinc-600">Create a trusted storefront for career services and original templates, then manage customer work from offer to payout.</p><FeatureList items={creatorFeatures}/><div className="mt-8 flex flex-wrap gap-3"><Link href="/earn-with-jobiverse" className="jv-brand-gradient inline-flex items-center gap-2 rounded-2xl px-6 py-4 font-bold text-white">Explore Creator Universe<ArrowRight size={17}/></Link><Link href="/login/creator" className="rounded-2xl border border-violet-100 bg-white px-6 py-4 font-bold">Creator login</Link></div></div><div className="relative rounded-[3rem] border border-violet-100 bg-[#faf8fc] p-7 sm:p-9"><div className="jv-brand-gradient rounded-[2.25rem] p-7 text-white"><div className="flex items-center justify-between"><div><p className="text-xs font-bold uppercase tracking-[.16em] text-violet-200">Creator studio</p><h3 className="mt-2 text-3xl font-bold">Your business</h3></div><CircleDollarSign size={40} className="text-violet-300"/></div><div className="mt-7 grid grid-cols-3 gap-3">{[["Orders","18"],["Active","5"],["Earnings","₹24k"]].map(([label,value])=><div key={label} className="rounded-2xl bg-white/10 p-4"><p className="text-xl font-black"><AnimatedMetric value={value}/></p><p className="mt-1 text-[9px] uppercase tracking-wider text-zinc-400">{label}</p></div>)}</div><WorkflowAnimation type="creator"/></div><div className="mt-4 grid gap-3 sm:grid-cols-2"><Preview icon={MessageSquareText} title="Offers" text="Accept, decline or counter"/><Preview icon={BriefcaseBusiness} title="Orders" text="Deliveries and revisions"/><Preview icon={CalendarDays} title="Sessions" text="Availability and bookings"/><Preview icon={WalletCards} title="Payouts" text="Balances and statements"/></div></div></div></section>

    <section className="bg-[#f8f6fa] px-5 pb-24 pt-12 sm:px-8"><div className="jv-brand-gradient mx-auto max-w-[1200px] rounded-[3rem] p-8 text-center text-white sm:p-14"><ShieldCheck className="mx-auto text-violet-300" size={32}/><p className="mt-6 text-xs font-bold uppercase tracking-[.2em] text-violet-200">One standard across every Universe</p><h2 className="mt-4 text-4xl font-semibold tracking-[-.05em] sm:text-6xl">Focused experiences. Shared trust.</h2><p className="mx-auto mt-6 max-w-2xl text-lg leading-8 text-zinc-300">Clear access, consent-first visibility, protected workflows and honest free/paid labels—regardless of which Universe you enter.</p><div className="mt-9 flex flex-wrap justify-center gap-3"><Link href="/guides/features" className="inline-flex items-center gap-2 rounded-2xl bg-white px-6 py-4 font-bold text-zinc-950">See complete feature guide<ArrowRight size={17}/></Link><Link href="/about" className="rounded-2xl border border-white/15 bg-white/10 px-6 py-4 font-bold">About JobiVerse</Link></div></div></section>
  </>;
}

function AnimatedMetric({value}:{value:string}) { const match=value.match(/(\d+)/); if(!match)return <>{value}</>; const number=Number(match[1]); return <CountUp value={number} prefix={value.startsWith("₹")?"₹":""} suffix={value.endsWith("%")?"%":value.endsWith("k")?"k":""}/> }
function Preview({icon:Icon,title,text}:{icon:React.ElementType;title:string;text:string}) { return <div className="rounded-[1.5rem] border border-violet-100 bg-[#faf8fc] p-5"><span className="grid h-10 w-10 place-items-center rounded-xl bg-violet-100 text-violet-800"><Icon size={18}/></span><p className="mt-4 font-bold">{title}</p><p className="mt-1 text-xs leading-5 text-zinc-500">{text}</p></div> }
function PreviewLarge({icon:Icon,title,text}:{icon:React.ElementType;title:string;text:string}) { return <div className="rounded-[2rem] border border-violet-100 bg-white p-6"><span className="jv-brand-gradient grid h-11 w-11 place-items-center rounded-2xl text-white"><Icon size={20}/></span><h3 className="mt-5 text-xl font-bold">{title}</h3><p className="mt-3 text-sm leading-6 text-zinc-600">{text}</p></div> }
