import Link from "next/link";
import { notFound } from "next/navigation";
import { ArrowLeft, PencilLine, Save } from "lucide-react";
import { requireRole } from "@/lib/auth/authorization";
import { updateCreatorService } from "./actions";

export default async function EditCreatorServicePage({params}:{params:Promise<{id:string}>}){const{id}=await params;const{supabase,user}=await requireRole(["candidate","creator"]);const{data:service}=await supabase.from("marketplace_services").select("id,title,audience,category,short_description,description,price,delivery_days,delivery_mode,status").eq("id",id).eq("provider_id",user.id).maybeSingle();if(!service)notFound();return <main className="min-h-screen bg-[#f5f5f3] px-5 pb-24 pt-36 sm:px-8"><div className="mx-auto max-w-4xl"><Link href="/earn-with-jobiverse/dashboard" className="inline-flex items-center gap-2 text-sm font-semibold text-zinc-600"><ArrowLeft size={16}/>Creator dashboard</Link><section className="mt-8 rounded-[2.75rem] bg-zinc-950 p-8 text-white sm:p-12"><PencilLine/><p className="mt-5 text-xs font-bold uppercase tracking-[.18em] text-zinc-500">Edit marketplace listing</p><h1 className="mt-3 text-4xl font-semibold">Make your service stronger.</h1><p className="mt-4 text-zinc-400">{service.category} | {service.audience} | Current status: {service.status}</p></section><form action={updateCreatorService} className="mt-7 grid gap-5 rounded-[2rem] border border-zinc-200 bg-white p-7 sm:grid-cols-2 sm:p-9"><input type="hidden" name="serviceId" value={service.id}/><Field label="Listing title" name="title" value={service.title} wide/><Field label="Card description" name="shortDescription" value={service.short_description} wide minLength={20}/><label className="text-sm font-semibold sm:col-span-2">Complete service details<textarea name="description" required minLength={40} maxLength={4000} defaultValue={service.description} rows={10} className="mt-2 w-full rounded-2xl border border-zinc-200 p-4 font-normal outline-none focus:border-zinc-500"/></label><Field label="Your earning price (₹)" name="price" value={String(service.price)} type="number"/><Field label="Delivery time (days)" name="deliveryDays" value={String(service.delivery_days)} type="number"/><label className="text-sm font-semibold sm:col-span-2">Delivery mode<select name="deliveryMode" defaultValue={service.delivery_mode} className="mt-2 h-12 w-full rounded-xl border border-zinc-200 bg-white px-4 font-normal"><option value="online">Online</option><option value="call">Video / voice call</option><option value="document">Document delivery</option><option value="hybrid">Hybrid</option></select></label><div className="flex flex-wrap items-center justify-between gap-4 border-t border-zinc-100 pt-6 sm:col-span-2"><p className="text-xs text-zinc-500">Changes update the listing without affecting existing paid orders.</p><button className="inline-flex cursor-pointer items-center gap-2 rounded-xl bg-zinc-950 px-6 py-3 font-semibold text-white"><Save size={17}/>Save changes</button></div></form></div></main>}

function Field({label,name,value,wide,type="text",minLength}:{label:string;name:string;value:string;wide?:boolean;type?:"text"|"number";minLength?:number}){return <label className={`text-sm font-semibold ${wide?"sm:col-span-2":""}`}>{label}<input name={name} type={type} required minLength={minLength} maxLength={type==="text"?240:undefined} min={type==="number"?0:undefined} defaultValue={value} className="mt-2 h-12 w-full rounded-xl border border-zinc-200 px-4 font-normal outline-none focus:border-zinc-500"/></label>}


