import Link from "next/link";
import { AlertTriangle, BadgeCheck, Download, FileSearch } from "lucide-react";
import { requireRole } from "@/lib/auth/authorization";
import { adminSupabase } from "@/lib/supabase/admin";
import { evaluateJobQuality } from "@/lib/jobs/quality";

export default async function AdminJobQualityPage() {
  await requireRole(["admin"]);
  const { data, error } = await adminSupabase.from("requirements").select("id,job_title,job_description,location,primary_skills,employment_type,work_mode,experience,status,is_public,published_at,employer_id,companies(company_name,website,logo_url)").eq("is_public", true).order("published_at", { ascending: false });
  if (error) throw new Error(error.message);
  const rows = (data ?? []).map((job) => { const company=job.companies?.[0]??null;const quality=evaluateJobQuality({...job,companyName:company?.company_name,companyWebsite:company?.website,companyLogo:company?.logo_url});return {...job,company,quality}; });
  const excellent=rows.filter(row=>row.quality.score>=90).length, needsWork=rows.filter(row=>row.quality.score<75).length, critical=rows.filter(row=>row.quality.score<55).length;
  return <div className="space-y-8"><section className="rounded-[2.5rem] bg-[radial-gradient(circle_at_82%_18%,rgba(245,158,11,.28),transparent_22rem),linear-gradient(135deg,#09090b,#27272a)] p-9 text-white sm:p-11"><FileSearch/><p className="mt-5 text-xs font-bold uppercase tracking-[.18em] text-amber-300">Direct jobs governance</p><div className="mt-3 flex flex-wrap items-end justify-between gap-5"><div><h1 className="text-4xl font-bold">Job Quality Report</h1><p className="mt-3 max-w-3xl text-zinc-300">Find incomplete, stale or SEO-weak JobiVerse direct roles before candidates or search engines see a poor listing.</p></div><Link href="/api/admin/job-quality/export" className="inline-flex items-center gap-2 rounded-xl bg-white px-5 py-3 text-sm font-bold text-zinc-950"><Download size={16}/>Download CSV</Link></div></section><section className="grid gap-4 sm:grid-cols-4"><Metric label="Public direct roles" value={rows.length}/><Metric label="Excellent" value={excellent} tone="green"/><Metric label="Needs work" value={needsWork} tone="amber"/><Metric label="Critical" value={critical} tone="red"/></section><section className="space-y-4">{rows.length?rows.map(row=><article key={row.id} className={`rounded-3xl border bg-white p-6 ${row.quality.score<55?"border-red-200":row.quality.score<75?"border-amber-200":"border-zinc-200"}`}><div className="flex flex-wrap items-start justify-between gap-5"><div><p className="text-xs font-bold uppercase tracking-wider text-zinc-400">{row.company?.company_name||"Company missing"}</p><h2 className="mt-2 text-xl font-bold">{row.job_title||"Untitled role"}</h2><p className="mt-2 text-sm text-zinc-500">{row.location||"Location missing"} · {row.status||"Status missing"}</p></div><div className="text-right"><p className={`text-3xl font-bold ${row.quality.score>=90?"text-emerald-600":row.quality.score>=75?"text-blue-600":row.quality.score>=55?"text-amber-600":"text-red-600"}`}>{row.quality.score}/100</p><p className="text-xs font-bold uppercase text-zinc-400">{row.quality.grade}</p></div></div>{row.quality.issues.length?<div className="mt-5 flex flex-wrap gap-2">{row.quality.issues.map(issue=><span key={issue} className="inline-flex items-center gap-1 rounded-full bg-amber-50 px-3 py-1.5 text-xs font-semibold text-amber-800"><AlertTriangle size={12}/>{issue}</span>)}</div>:<p className="mt-5 inline-flex items-center gap-2 rounded-full bg-emerald-50 px-3 py-1.5 text-xs font-semibold text-emerald-700"><BadgeCheck size={14}/>No material quality issue detected</p>}<div className="mt-5 flex justify-end border-t border-zinc-100 pt-4"><Link href={`/admin/requirements/${row.id}`} className="rounded-xl bg-zinc-950 px-4 py-2.5 text-sm font-semibold text-white">Review requirement</Link></div></article>):<p className="rounded-3xl border border-dashed border-zinc-200 bg-white p-12 text-center text-zinc-500">No public direct jobs found.</p>}</section></div>;
}
function Metric({label,value,tone="zinc"}:{label:string;value:number;tone?:"zinc"|"green"|"amber"|"red"}){const styles={zinc:"bg-white",green:"border-emerald-200 bg-emerald-50",amber:"border-amber-200 bg-amber-50",red:"border-red-200 bg-red-50"};return <div className={`rounded-3xl border border-zinc-200 p-6 ${styles[tone]}`}><p className="text-xs font-bold uppercase tracking-wider text-zinc-500">{label}</p><p className="mt-2 text-3xl font-bold">{value}</p></div>}
