export const customPortalIndustries = [
  { slug: "healthcare", label: "Healthcare & Clinics", summary: "Run care operations, staff readiness and patient-facing workflows.", modules: ["Patient registration & appointments", "Doctor and shift rosters", "Digital patient records", "Lab and pharmacy coordination", "Inventory & equipment tracking", "Compliance and training records"] },
  { slug: "engineering-manufacturing", label: "Engineering & Manufacturing", summary: "Connect projects, production, quality and field teams.", modules: ["Projects and work orders", "Production planning", "Quality inspections", "Machine maintenance", "Safety incidents & permits", "Vendor and material tracking"] },
  { slug: "education", label: "Education & Training", summary: "Manage learners, faculty, programmes and outcomes.", modules: ["Admissions and enrolment", "Student information system", "Attendance and timetables", "Assignments and assessments", "Faculty workload", "Placements and alumni"] },
  { slug: "retail-ecommerce", label: "Retail & E-commerce", summary: "Keep catalogue, stores, orders and customers connected.", modules: ["Product catalogue", "Inventory across locations", "Orders and fulfilment", "Returns and refunds", "Store task management", "Customer loyalty & support"] },
  { slug: "hospitality-travel", label: "Hospitality & Travel", summary: "Coordinate guests, bookings, properties and service teams.", modules: ["Bookings and reservations", "Guest profiles", "Housekeeping operations", "Property maintenance", "Vendor and procurement", "Service requests & feedback"] },
  { slug: "it-software", label: "IT & Software", summary: "Organise delivery, support, assets and client visibility.", modules: ["Projects and sprint tracking", "Client portal", "Help desk & SLAs", "IT asset management", "Release and incident logs", "Knowledge base"] },
  { slug: "construction-real-estate", label: "Construction & Real Estate", summary: "Track sites, properties, contractors and commercial progress.", modules: ["Site and project tracking", "Daily progress reports", "Contractor management", "Materials and equipment", "Property CRM", "Documents and approvals"] },
  { slug: "logistics-supply-chain", label: "Logistics & Supply Chain", summary: "Create visibility across fleet, warehouse and delivery operations.", modules: ["Fleet and driver records", "Shipment tracking", "Route and dispatch planning", "Warehouse operations", "Proof of delivery", "Vendor performance"] },
  { slug: "finance-professional-services", label: "Finance & Professional Services", summary: "Control clients, engagements, documents and compliance.", modules: ["Client onboarding & KYC", "Engagement and case tracking", "Document vault", "Billing and collections", "Compliance calendar", "Approvals and audit trail"] },
  { slug: "ngo-social-impact", label: "NGO & Social Impact", summary: "Manage programmes, beneficiaries, grants and field evidence.", modules: ["Beneficiary records", "Programme and field activity", "Volunteer management", "Grant and donor tracking", "Impact measurement", "Evidence and reporting"] },
  { slug: "bpo-customer-support", label: "BPO & Customer Support", summary: "Manage queues, agents, quality and service performance.", modules: ["Ticket and queue management", "Agent rosters", "SLA monitoring", "Quality audits", "Knowledge base", "Client reporting"] },
  { slug: "general", label: "General / Something Else", summary: "Combine only the workflows your organisation actually needs.", modules: ["Operations dashboard", "Team and role access", "Requests and approvals", "Tasks and workflows", "Documents and records", "Reports and alerts"] },
] as const;

export type CustomPortalIndustry = (typeof customPortalIndustries)[number];
export const customPortalIndustrySlugs = customPortalIndustries.map(item => item.slug);
export function getCustomPortalIndustry(slug: string) { return customPortalIndustries.find(item => item.slug === slug) ?? customPortalIndustries.at(-1)!; }
