import { LegalDocument, type LegalSection } from "@/components/legal/legal-document";

const sections: LegalSection[]=[
  {title:"Agreement and eligibility",content:<p>These terms govern use of JobiVerse. By creating an account, submitting information, listing or purchasing a service, you confirm that the information supplied is accurate and that you are legally capable of entering the transaction. Children may not independently purchase or provide services.</p>},
  {title:"Platform roles",content:<p>JobiVerse provides recruitment services directly and also operates technology that connects candidates, employers and independent creators. A creator listing identifies the service provider; “JobiVerse Personal” identifies a service delivered or managed directly by JobiVerse. JobiVerse may moderate listings, reviews, messages and accounts for safety and quality.</p>},
  {title:"Recruitment and career services",content:<p>JobiVerse does not guarantee employment, interview selection, candidate performance, hiring, salary or business results. Employers remain responsible for lawful requirements, verification, interviews, offers and employment decisions. Candidates remain responsible for truthful qualifications, availability and application information.</p>},
  {title:"Marketplace bookings and pricing",content:<p>The customer-facing amount may include a JobiVerse platform markup over the creator's base amount. Creator earnings and JobiVerse commercial components are shown in the relevant role workspace and records, not necessarily as the same figure. A negotiated amount becomes binding only after acceptance and successful payment. Service scope, delivery time, mode and included revisions shown at checkout form part of the order.</p>},
  {title:"Payments, invoices and taxes",content:<p>Payments are processed through the displayed payment provider. An order is activated only after server-side payment verification. Billing information must be accurate. GST, invoices, withholding and creator tax treatment will follow applicable law and the final approved commercial configuration. Recruitment mandates may be governed by separate signed commercial terms.</p>},
  {title:"Creator obligations and content rights",content:<p>Creators must have the right to provide every uploaded template, file and service; describe it accurately; meet agreed scope and timelines; protect customer information; and avoid copied, unlawful or misleading material. A creator retains ownership of original material but grants JobiVerse the limited rights needed to host, preview, market, deliver and administer the listing and order. Customer usage rights are limited to the licence or delivered purpose stated for that purchase.</p>},
  {title:"User conduct and communications",content:<p>Users must not impersonate others, scrape data, bypass payments, move transactions off-platform to avoid fees, upload malware, disclose confidential data without authority, harass users, manipulate reviews, or misuse candidate and employer information. Order and support communications may be retained and reviewed for fulfilment, disputes, abuse prevention and legal compliance.</p>},
  {title:"Delivery, acceptance and disputes",content:<p>Customers should review delivery promptly and use included revision tools for in-scope changes. Order approval confirms acceptance of the submitted delivery, subject to rights that cannot legally be excluded. Either participant may raise a supported dispute. JobiVerse may examine order status, scope, messages, files, payments and evidence before taking platform action.</p>},
  {title:"Account action and service availability",content:<p>JobiVerse may restrict, suspend or terminate accounts or listings for security risk, unlawful conduct, material breach, payment abuse, repeated quality issues or platform harm. Features may change, pause or be withdrawn. Planned AI features and other Coming Soon functionality are not part of a purchased service until expressly activated.</p>},
  {title:"Intellectual property and feedback",content:<p>The JobiVerse name, logo, platform design, software and first-party content belong to JobiVerse or its licensors. Users may not copy or exploit them without permission. Feedback may be used to improve the platform without revealing confidential information.</p>},
  {title:"Liability and governing law",content:<p>To the extent permitted by applicable law, JobiVerse is not responsible for indirect losses, independent creator conduct, employer decisions, candidate misrepresentation or third-party service interruptions. Nothing in these terms excludes rights or liability that cannot legally be excluded. Indian law applies and disputes are subject to competent courts in Mumbai, Maharashtra, unless mandatory consumer law provides otherwise.</p>},
  {title:"Contact and changes",content:<p>Questions or grievances: jobiverse@outlook.com, +91 77388 32231, Room No. 25, Plot No. 70, Malad (W), Mumbai, Maharashtra 400095. Material revisions will be published with an updated effective date.</p>},
];
export default function TermsPage(){return <LegalDocument title="Terms & Conditions" description="Rules for recruitment, career services, marketplace transactions, creators and every JobiVerse account." sections={sections}/>;}
