import { BriefcaseBusiness, GraduationCap, IdCard, LibraryBig, UserSearch, WandSparkles, type LucideIcon } from "lucide-react";

export type GuideSection = { title: string; items: string[] };
export type Guide = { slug:string; title:string; shortTitle:string; eyebrow:string; description:string; audience:string; icon:LucideIcon; startHref:string; startLabel:string; sections:GuideSection[] };

export const roleGuideHref = { candidate:"/guides/candidate", employer:"/guides/employer", recruiter:"/guides/recruiter", creator:"/guides/creator" } as const;

export const guides: Guide[] = [
  { slug:"features", title:"Complete JobiVerse Feature Guide", shortTitle:"Complete Feature Guide", eyebrow:"The complete universe", description:"See how hiring, careers, creator commerce, payments, notifications and protection work together.", audience:"Everyone", icon:LibraryBig, startHref:"/choose-your-world", startLabel:"Choose your universe", sections:[
    {title:"One platform, distinct workspaces",items:["Role-based accounts for candidates, creators, employers and recruiters.","A public Jobs Portal, career marketplace, JobiVerse Cards and consultations.","Dedicated dashboards that show tools relevant to the signed-in role."]},
    {title:"Shared account experience",items:["Profile, security, privacy, billing and notification controls.","In-app notifications, email preferences, job digests, reminders and supported web push.","Installable Android and iPhone Safari PWA with offline fallback.","Consent management, data export, support requests and referrals."]},
    {title:"Hiring universe",items:["Free public job posting, Job Quality Assistant and automatic expiry.","Direct, recruiter-submitted and JobiVerse Hiring Team candidates in structured pipelines.","Interviews, messages, offers, counteroffers, placements, reports and billing.","Paid Talent Search, team seats, hiring intelligence and optional Spotlight promotion."]},
    {title:"Career universe",items:["Professional profile, Open to Work and the shareable JobiVerse Card.","Direct and partner-job discovery, trust guidance, comparison, saves and alerts.","Application Health, interview/offer tracking, Follow-up Assistant and withdrawals.","Resume Studio, version history, editable templates and career support."]},
    {title:"Creator universe",items:["Free service publishing with creator-selected earnings.","Offers, paid orders, delivery, revisions, sessions and messaging.","Reviews, refunds, disputes, earnings ledger and verified payouts.","Optional paid 30-day featured marketplace placement."]},
    {title:"Trust and commercial clarity",items:["Candidates are never charged to apply or interview.","Direct Jobs Portal joining uses a one-time 3% annual-CTC employer fee.","Managed JobiVerse hiring has separate scope-based commercials, shown as standard 5% in the active workflow.","AI and provider-backed capabilities depend on stated gates or production configuration."]},
  ]},
  { slug:"employer", title:"Employer Universe Guide", shortTitle:"Employer Guide", eyebrow:"For hiring teams", description:"Set up your company, publish safer roles and manage candidates from application to joining.", audience:"Employers", icon:BriefcaseBusiness, startHref:"/employers/dashboard", startLabel:"Open employer dashboard", sections:[
    {title:"Set up your workspace",items:["Complete the company profile and organization information.","Invite employer or recruiter seats from the master employer account.","Assign recruiters only to the requirements they should work on."]},
    {title:"Create a quality requirement",items:["Add role, skills, experience, location, work type, budget and responsibilities.","Save privately, publish publicly or assign to the JobiVerse Hiring Team.","Use the live 0-100 Job Quality Assistant and resolve critical safety issues."]},
    {title:"Choose the hiring route",items:["Public Jobs Portal: ₹0 upfront; 3% of annual CTC after a direct applicant joins.","Managed sourcing and screening: separate route, shown as standard 5% with scope-based negotiation.","Optional 30-day Spotlight promotion for priority roles."]},
    {title:"Review and organize talent",items:["Filter direct, recruiter and JobiVerse candidates by source, role and status.","Review secure resumes and JobiVerse Cards, compare candidates and add private notes.","Use talent folders and approved paid Talent Search."]},
    {title:"Interview and offer",items:["Schedule rounds with date, time, mode, interviewer and meeting link.","Reschedule, cancel, complete, mark no-show and record feedback.","Send CTC, joining date, location and terms; receive accept, decline or counter responses."]},
    {title:"Close and measure",items:["Track offered, accepted, joined, declined, no-show, replacement and completed outcomes.","Review requirement/recruiter reports, commercial statements and payment status.","Use hiring-health and pipeline signals to identify stalled work."]},
  ]},
  { slug:"candidate", title:"Candidate / Talent Universe Guide", shortTitle:"Candidate Guide", eyebrow:"For professionals and students", description:"Build your career identity, discover safer opportunities and organize every application.", audience:"Candidates", icon:IdCard, startHref:"/candidates/dashboard", startLabel:"Open candidate dashboard", sections:[
    {title:"Build your professional profile",items:["Add headline, experience, skills, preferences, notice period and work mode.","Upload a secure PDF resume and maintain private version history.","Use Open to Work only when you want approved hiring users to discover you."]},
    {title:"Create your JobiVerse Card",items:["Organize experience, education, projects, skills and credentials.","Submit supporting evidence for verification where applicable.","Control public visibility, share your Card and review Card views."]},
    {title:"Discover opportunities",items:["Search direct JobiVerse and clearly attributed partner roles.","Filter by role, location, sector, experience, mode, type, freshness and source.","Use trust signals, directional salary guidance and compare up to three roles.","Save jobs/searches and configure instant, daily or weekly alerts."]},
    {title:"Apply and track",items:["Submit current details and a preserved resume snapshot.","Track JobiVerse and external applications through Application Health stages.","Use messages, attachments, interview calendar, Follow-up Assistant and withdrawal controls."]},
    {title:"Interviews, offers and growth",items:["Receive interview details, reminders and scheduling updates.","Accept, decline or counter an employment offer.","Use Resume Studio, editable premium templates and interview preparation.","Explore optional Career Plus/Pro and marketplace support; applications remain free."]},
    {title:"Stay safe",items:["JobiVerse never charges candidates to apply or interview.","Keep sensitive information inside protected workflows.","Report candidate-fee requests, misleading jobs, discrimination or suspicious contact."]},
  ]},
  { slug:"student", title:"Student Universe Guide", shortTitle:"Student Guide", eyebrow:"For students and freshers", description:"Build proof of potential, discover fresh opportunities and organise your first career moves.", audience:"Students & recent graduates", icon:GraduationCap, startHref:"/students/dashboard", startLabel:"Open student dashboard", sections:[
    {title:"Set up your launchpad",items:["Use the dedicated Student login while keeping one JobiVerse career account.","Add college, degree, projects, skills, certifications and preferred roles.","Your information remains reusable when you move from student to professional."]},
    {title:"Find fresh opportunities",items:["Explore fresher, internship, trainee, graduate and new-this-week collections.","Filter the shared Jobs Portal by location, work mode and source.","Save suitable roles and configure job-alert digests."]},
    {title:"Build proof of potential",items:["Turn education, projects and early experience into an ATS-ready resume.","Use your JobiVerse Card for skills, projects, education and credentials.","Keep resume versions and supporting evidence organised."]},
    {title:"Apply and prepare",items:["Apply free of charge and track application stages in one workspace.","Use interview preparation, readiness checklists and career services.","Never pay an application or interview fee; report suspicious requests."]},
  ]},
  { slug:"creator", title:"Creator Universe Guide", shortTitle:"Creator Guide", eyebrow:"For experts who create and earn", description:"Turn career expertise into a storefront with orders, scheduling, delivery and payouts.", audience:"Creators", icon:WandSparkles, startHref:"/earn-with-jobiverse/dashboard", startLabel:"Open creator dashboard", sections:[
    {title:"Publish your offering",items:["Choose audience/category and explain the service, deliverables, timeline and revisions.","Add previews and confirm submitted materials are original.","Set your desired earning and review the customer-facing price.","Publish normally for free, then edit, pause, resume or archive."]},
    {title:"Manage demand",items:["Track views, orders, active services and earnings.","Accept, decline or counter customer offers.","Use optional paid featured placement for 30 days of added visibility."]},
    {title:"Deliver and communicate",items:["Move paid orders into progress, submit delivery and respond to revisions.","Keep customer messages and supported attachments connected to the order.","Complete the service after approval and preserve the timeline."]},
    {title:"Schedule sessions",items:["Set available days/hours, minimum notice and daily booking capacity.","Pause new bookings when unavailable.","Propose, confirm or reschedule session times."]},
    {title:"Earnings and payouts",items:["Review lifetime, clearing, available and paid balances.","Wait for completion and the customer-protection period.","Maintain a verified payout profile, request withdrawal and download statements."]},
    {title:"Trust and protection",items:["Build trust through quality listings, verification and reviews.","Use recorded revision, refund and dispute workflows.","Featured visibility does not guarantee sales; refunds/disputes can affect settlement."]},
  ]},
  { slug:"recruiter", title:"Recruiter Universe Guide", shortTitle:"Recruiter Guide", eyebrow:"For sourcing and delivery teams", description:"Work assigned requirements, submit relevant talent and maintain accountable movement.", audience:"Recruiters", icon:UserSearch, startHref:"/recruiter", startLabel:"Open recruiter dashboard", sections:[
    {title:"Access the right workspace",items:["Use your recruiter login or accept an employer team invitation.","Work within the employer/company access and requirements assigned to you.","Keep notification and security settings current."]},
    {title:"Work assigned requirements",items:["Review role, skills, experience, location, budget and expectations.","Focus sourcing on active assigned requirements.","Use status and activity to prioritize daily work."]},
    {title:"Source and submit candidates",items:["Maintain candidate records with professional and resume information.","Map candidates to the correct requirement and preserve source attribution.","Use Talent Search only when employer access is approved."]},
    {title:"Manage pipeline movement",items:["Track submitted, shortlisted, interview, offered, joined and closed movement.","Keep notes connected to the correct candidate and requirement.","Use talent folders for relevant follow-up profiles."]},
    {title:"Coordinate and report",items:["Use the interview calendar and same-day reminders.","Support scheduling, rescheduling and accurate outcome updates.","Review submissions, conversion and fulfilment by date and requirement."]},
    {title:"Recruiter standard",items:["Never request candidate application or interview fees.","Never request OTPs, banking credentials or unsafe information.","Use JobiVerse workflows to preserve introductions and accountability."]},
  ]},
];

export function getGuide(slug:string){ return guides.find(guide=>guide.slug===slug); }
