import Link from "next/link";
import { BadgeCheck, Ban, Download, Search, UsersRound } from "lucide-react";
import { updatePlatformUser } from "./actions";
import { requireRole } from "@/lib/auth/authorization";
import { listAllAuthUsers, signupProvider } from "@/lib/admin/auth-users";
import { adminSupabase } from "@/lib/supabase/admin";

export default async function AdminUsersPage({ searchParams }: { searchParams: Promise<{ q?: string; role?: string; status?: string }> }) {
  await requireRole(["admin"]); const params = await searchParams;
  const [authUsers, { data: profiles, error }] = await Promise.all([listAllAuthUsers(), adminSupabase.from("users").select("id,email,full_name,role,is_active,created_at")]);
  if (error) throw new Error(error.message); const profileMap = new Map((profiles ?? []).map((profile) => [profile.id, profile])); const q = params.q?.trim().toLowerCase() ?? "";
  const all = authUsers.map((authUser) => { const profile = profileMap.get(authUser.id); return { id: authUser.id, email: authUser.email ?? profile?.email ?? "", name: profile?.full_name || String(authUser.user_metadata?.full_name ?? ""), role: profile?.role || String(authUser.user_metadata?.role ?? "unassigned"), active: profile?.is_active !== false && !authUser.banned_until, verified: Boolean(authUser.email_confirmed_at), provider: signupProvider(authUser), createdAt: authUser.created_at, lastSignIn: authUser.last_sign_in_at }; });
  const rows = all.filter((item) => (!q || `${item.name} ${item.email}`.toLowerCase().includes(q)) && (!params.role || params.role === "all" || item.role === params.role) && (!params.status || params.status === "all" || (params.status === "active" ? item.active : params.status === "suspended" ? !item.active : params.status === "pending" ? !item.verified : true)));
  const pending = all.filter((user) => !user.verified).length; const suspended = all.filter((user) => !user.active).length;
  return <div className="space-y-8"><section className="rounded-[2.5rem] bg-gradient-to-br from-zinc-950 via-zinc-900 to-blue-950 p-9 text-white sm:p-12"><UsersRound/><p className="mt-5 text-xs font-bold uppercase tracking-[.2em] text-blue-300">Identity operations</p><h1 className="mt-3 text-4xl font-bold sm:text-5xl">User Management</h1><p className="mt-4 max-w-3xl text-zinc-300">Search every account, review verification and last-login health, and restrict or restore access without deleting history.</p></section>
  <section className="grid gap-4 sm:grid-cols-3"><Metric label="Registered accounts" value={all.length} icon={UsersRound}/><Metric label="Pending verification" value={pending} icon={BadgeCheck} attention={pending>0}/><Metric label="Suspended accounts" value={suspended} icon={Ban} attention={suspended>0}/></section>
  <section className="rounded-3xl border border-zinc-200 bg-white p-6"><form className="grid gap-3 lg:grid-cols-[1fr_180px_180px_auto]"><label className="flex h-12 items-center gap-3 rounded-xl border border-zinc-200 px-4"><Search size={17}/><input name="q" defaultValue={params.q} placeholder="Search name or email" className="w-full outline-none"/></label><select name="role" defaultValue={params.role??"all"} className="h-12 rounded-xl border border-zinc-200 px-3"><option value="all">All roles</option>{["candidate","employer","recruiter","creator","admin"].map(role=><option key={role} value={role}>{role}</option>)}</select><select name="status" defaultValue={params.status??"all"} className="h-12 rounded-xl border border-zinc-200 px-3"><option value="all">All statuses</option><option value="active">Active</option><option value="pending">Pending verification</option><option value="suspended">Suspended</option></select><button className="rounded-xl bg-zinc-950 px-6 font-semibold text-white">Filter</button></form><div className="mt-4 flex justify-between text-sm text-zinc-500"><span>{rows.length} matching accounts</span><Link href="/api/admin/users/export" className="inline-flex items-center gap-2 font-semibold text-zinc-900"><Download size={15}/>Export CSV</Link></div></section>
  <section className="overflow-hidden rounded-3xl border border-zinc-200 bg-white"><div className="overflow-x-auto"><table className="w-full min-w-[1000px] text-left text-sm"><thead className="bg-zinc-50 text-xs uppercase tracking-wide text-zinc-400"><tr>{["User","Role / source","Registered","Last login","Status","Action"].map(value=><th key={value} className="p-4">{value}</th>)}</tr></thead><tbody>{rows.map(item=><tr key={item.id} className="border-t border-zinc-100"><td className="p-4"><p className="font-semibold">{item.name||"Name not added"}</p><p className="mt-1 text-xs text-zinc-500">{item.email}</p></td><td className="p-4"><p className="capitalize font-semibold">{item.role}</p><p className="mt-1 text-xs capitalize text-zinc-400">{item.provider}</p></td><td className="p-4 text-zinc-500">{format(item.createdAt)}</td><td className="p-4 text-zinc-500">{item.lastSignIn?format(item.lastSignIn):"Never"}</td><td className="p-4"><div className="flex flex-wrap gap-2"><Pill ok={item.active} text={item.active?"Active":"Suspended"}/><Pill ok={item.verified} text={item.verified?"Verified":"Email pending"}/></div></td><td className="p-4"><div className="flex gap-2">{item.role!=="admin"&&<form action={updatePlatformUser}><input type="hidden" name="userId" value={item.id}/><button name="action" value={item.active?"suspend":"restore"} className={`rounded-lg px-3 py-2 text-xs font-bold ${item.active?"bg-red-50 text-red-700":"bg-emerald-600 text-white"}`}>{item.active?"Suspend":"Restore"}</button></form>}{!item.verified&&<form action={updatePlatformUser}><input type="hidden" name="userId" value={item.id}/><button name="action" value="verify_email" className="rounded-lg bg-zinc-950 px-3 py-2 text-xs font-bold text-white">Verify email</button></form>}</div></td></tr>)}</tbody></table></div>{!rows.length&&<p className="p-12 text-center text-zinc-500">No users match these filters.</p>}</section></div>;
}
function Metric({label,value,icon:Icon,attention=false}:{label:string;value:number;icon:typeof UsersRound;attention?:boolean}){return <article className={`rounded-3xl border p-6 ${attention?"border-amber-200 bg-amber-50":"border-zinc-200 bg-white"}`}><Icon className={attention?"text-amber-700":"text-zinc-400"}/><p className="mt-5 text-3xl font-bold">{value}</p><p className="mt-1 text-sm text-zinc-500">{label}</p></article>}
function Pill({ok,text}:{ok:boolean;text:string}){return <span className={`rounded-full px-3 py-1 text-[10px] font-bold uppercase ${ok?"bg-emerald-100 text-emerald-700":"bg-amber-100 text-amber-800"}`}>{text}</span>}
function format(value:string){return new Date(value).toLocaleString("en-IN",{dateStyle:"medium",timeStyle:"short",timeZone:"Asia/Kolkata"})}
