"use server";
import {revalidatePath} from "next/cache";
import {z} from "zod";
import {createServerSupabaseClient} from "@/lib/supabase/server";
import {adminSupabase} from "@/lib/supabase/admin";

export type ReviewActionState={error?:string;success?:string};const uuid=z.string().uuid();
export async function toggleHelpfulReview(_state:ReviewActionState,formData:FormData):Promise<ReviewActionState>{const reviewId=uuid.safeParse(formData.get("reviewId"));if(!reviewId.success)return{error:"Invalid review."};const supabase=await createServerSupabaseClient();const{data:{user}}=await supabase.auth.getUser();if(!user)return{error:"Log in to mark reviews helpful."};const{data:review}=await supabase.from("marketplace_reviews").select("id,reviewer_id").eq("id",reviewId.data).maybeSingle();if(!review)return{error:"Review not found."};if(review.reviewer_id===user.id)return{error:"You cannot vote on your own review."};const{data:existing}=await supabase.from("marketplace_review_votes").select("review_id").eq("review_id",review.id).eq("user_id",user.id).maybeSingle();const{error}=existing?await supabase.from("marketplace_review_votes").delete().eq("review_id",review.id).eq("user_id",user.id):await supabase.from("marketplace_review_votes").insert({review_id:review.id,user_id:user.id});if(error)return{error:error.message};revalidatePath("/marketplace/services/[slug]","page");return{success:existing?"Helpful vote removed.":"Marked as helpful."};}
export async function reportReview(_state:ReviewActionState,formData:FormData):Promise<ReviewActionState>{const parsed=z.object({reviewId:z.string().uuid(),reason:z.enum(["spam","abuse","misleading","personal_information","other"]),details:z.string().trim().min(10).max(1000)}).safeParse({reviewId:formData.get("reviewId"),reason:formData.get("reason"),details:formData.get("details")});if(!parsed.success)return{error:parsed.error.issues[0]?.message??"Check report details."};const supabase=await createServerSupabaseClient();const{data:{user}}=await supabase.auth.getUser();if(!user)return{error:"Log in to report a review."};const{data:review}=await supabase.from("marketplace_reviews").select("id,reviewer_id").eq("id",parsed.data.reviewId).maybeSingle();if(!review)return{error:"Review not found."};if(review.reviewer_id===user.id)return{error:"You cannot report your own review."};const{error}=await supabase.from("marketplace_review_reports").insert({review_id:review.id,reporter_id:user.id,reason:parsed.data.reason,details:parsed.data.details});if(error)return{error:error.code==="23505"?"You already reported this review.":error.message};const{data:admins}=await adminSupabase.from("users").select("id").eq("role","admin");if(admins?.length)await adminSupabase.from("notifications").insert(admins.map(admin=>({user_id:admin.id,type:"review_report_new",title:"New review report",message:`A marketplace review was reported for ${parsed.data.reason.replaceAll("_"," ")}.`,href:"/admin/marketplace",reference_id:review.id})));return{success:"Review reported to JobiVerse for moderation."};}
