import { randomUUID } from "crypto";
import { createServerSupabaseClient } from "@/lib/supabase/server";
import { adminSupabase } from "@/lib/supabase/admin";
import { createRazorpayOrder, razorpayConfig } from "@/lib/payments/razorpay";
import { amountWithPaymentProcessing, paymentProcessingFeeFor } from "@/lib/payments/processing-fee";
import { getResumeTemplate } from "@/lib/resume-templates";
import { featuredListingPrice } from "@/lib/marketplace/pricing";

export async function POST(request:Request){try{const supabase=await createServerSupabaseClient();const{data:{user}}=await supabase.auth.getUser();if(!user)return Response.json({error:"Please log in."},{status:401});const{data:billingProfile}=await supabase.from("buyer_billing_profiles").select("id").eq("user_id",user.id).maybeSingle();if(!billingProfile)return Response.json({error:"Complete your billing profile before payment."},{status:400});const body=await request.json() as{targetType?:string;targetId?:string};let amount=0;let localOrderId:string|null=null;let title="JobiVerse payment";
if(body.targetType==="marketplace_offer"){const{data:offer}=await supabase.from("marketplace_offers").select("id,customer_id,provider_id,service_id,customer_offer,creator_earning,platform_margin,message,status,marketplace_services(title)").eq("id",body.targetId).eq("customer_id",user.id).eq("status","accepted").maybeSingle();if(!offer)return Response.json({error:"Accepted negotiation not found."},{status:404});amount=Number(offer.customer_offer);const{data:existing}=await supabase.from("marketplace_orders").select("id,status").eq("offer_id",offer.id).maybeSingle();if(existing){if(existing.status!=="pending_payment")return Response.json({error:"This service is already paid."},{status:409});localOrderId=existing.id;}else{const{data:created,error}=await supabase.from("marketplace_orders").insert({offer_id:offer.id,service_id:offer.service_id,customer_id:user.id,provider_id:offer.provider_id,amount,creator_earning:offer.creator_earning,platform_margin:offer.platform_margin,requirements:offer.message,status:"pending_payment"}).select("id").single();if(error)throw new Error(error.message);localOrderId=created.id;}const service=Array.isArray(offer.marketplace_services)?offer.marketplace_services[0]:offer.marketplace_services;title=service?.title??"Creator service";
}else if(body.targetType==="marketplace_order"){const{data:order}=await supabase.from("marketplace_orders").select("id,amount,status,service_title,marketplace_services(title)").eq("id",body.targetId).eq("customer_id",user.id).eq("status","pending_payment").maybeSingle();if(!order)return Response.json({error:"Pending order not found."},{status:404});amount=Number(order.amount);localOrderId=order.id;const service=Array.isArray(order.marketplace_services)?order.marketplace_services[0]:order.marketplace_services;title=service?.title??order.service_title??"JobiVerse service";
}else if(body.targetType==="resume_download"){const template=getResumeTemplate(String(body.targetId));amount=template.price;title=`CV Template: ${template.name}`;let{data:purchased}=await supabase.from("resume_purchases").select("id").eq("user_id",user.id).eq("template_id",template.id).maybeSingle();if(!purchased){const{data:captured}=await adminSupabase.from("payment_attempts").select("id,amount").eq("user_id",user.id).eq("target_type","resume_download").eq("target_id",template.id).eq("status","captured").order("created_at",{ascending:false}).limit(1).maybeSingle();if(captured){const{error:recoveryError}=await adminSupabase.from("resume_purchases").upsert({user_id:user.id,template_id:template.id,payment_attempt_id:captured.id,amount:captured.amount},{onConflict:"user_id,template_id",ignoreDuplicates:true});if(recoveryError)throw new Error(recoveryError.message);purchased={id:captured.id}}}if(purchased)return Response.json({alreadyPaid:true,redirectUrl:`/candidates/resume-builder?template=${template.id}&download=1`});
}else if(body.targetType==="featured_listing"){const{data:service}=await supabase.from("marketplace_services").select("id,title,price,is_featured,featured_until").eq("id",body.targetId).eq("provider_id",user.id).eq("status","published").maybeSingle();if(!service)return Response.json({error:"Published service listing not found."},{status:404});if(service.is_featured&&(!service.featured_until||new Date(service.featured_until)>new Date()))return Response.json({alreadyPaid:true,redirectUrl:"/earn-with-jobiverse/dashboard?featured=active"});amount=featuredListingPrice(Number(service.price));title=`Featured placement: ${service.title}`;
}else return Response.json({error:"Invalid payment target."},{status:400});if(!Number.isFinite(amount)||amount<=0)throw new Error("Invalid payment amount.");const payableAmount=amountWithPaymentProcessing(amount);const processingFee=paymentProcessingFeeFor(amount);const attemptId=randomUUID();const gateway=await createRazorpayOrder(payableAmount,`jv_${attemptId.replaceAll("-","").slice(0,30)}`,{user_id:user.id,target_type:String(body.targetType),target_id:String(body.targetId),base_amount:String(amount),processing_recovery:String(processingFee)});const{error}=await adminSupabase.from("payment_attempts").insert({id:attemptId,user_id:user.id,target_type:body.targetType,target_id:body.targetId,local_order_id:localOrderId,amount:payableAmount,gateway_order_id:gateway.id});if(error)throw new Error(error.message);const{keyId}=razorpayConfig();return Response.json({keyId,gatewayOrderId:gateway.id,amount:gateway.amount,currency:"INR",title,attemptId,baseAmount:amount,processingFee});}catch(error){return Response.json({error:error instanceof Error?error.message:"Unable to start payment."},{status:500});}}
