"use server";
import { revalidatePath } from "next/cache";
import { z } from "zod";
import { requireRole } from "@/lib/auth/authorization";
import { adminSupabase } from "@/lib/supabase/admin";
import { getEmployerCompanyAccess } from "@/lib/employer-team/access";

async function ownRequest(id:string,userId:string){const access=await getEmployerCompanyAccess(userId).catch(()=>null);const{data}=await adminSupabase.from("custom_portal_requests").select("id,requester_user_id,company_id,status,proposal_number").eq("id",id).maybeSingle();if(!data||(data.requester_user_id!==userId&&(!access||data.company_id!==access.company.id)))throw new Error("Portal request not found.");return data}
export async function acceptPortalProposal(formData:FormData){const{id}=z.object({id:z.string().uuid()}).parse({id:formData.get("id")});const{user}=await requireRole(["employer"]);const request=await ownRequest(id,user.id);if(request.status!=="proposal_sent")throw new Error("This proposal is not awaiting acceptance.");const now=new Date().toISOString();await adminSupabase.from("custom_portal_requests").update({status:"accepted",proposal_accepted_at:now,updated_at:now}).eq("id",id);await adminSupabase.from("custom_portal_updates").insert({request_id:id,actor_user_id:user.id,update_type:"proposal",title:"Proposal accepted",message:`The employer accepted proposal ${request.proposal_number||""}.`});await notifyAdmins(id,"Portal proposal accepted","An employer accepted a custom portal proposal.");revalidatePath(`/employers/custom-portal/requests/${id}`);revalidatePath("/admin/custom-portals")}
export async function submitPortalUat(formData:FormData){const parsed=z.object({id:z.string().uuid(),decision:z.enum(["approved","changes"]),feedback:z.string().trim().max(5000)}).parse({id:formData.get("id"),decision:formData.get("decision"),feedback:formData.get("feedback")??""});const{user}=await requireRole(["employer"]);await ownRequest(parsed.id,user.id);const now=new Date().toISOString();const approved=parsed.decision==="approved";await adminSupabase.from("custom_portal_requests").update({uat_feedback:parsed.feedback||null,uat_approved_at:approved?now:null,updated_at:now}).eq("id",parsed.id);await adminSupabase.from("custom_portal_updates").insert({request_id:parsed.id,actor_user_id:user.id,update_type:"uat",title:approved?"UAT approved":"UAT changes requested",message:parsed.feedback||null});await notifyAdmins(parsed.id,approved?"Portal UAT approved":"Portal UAT feedback received",parsed.feedback||"The employer updated UAT status.");revalidatePath(`/employers/custom-portal/requests/${parsed.id}`);revalidatePath(`/admin/custom-portals/${parsed.id}`)}
async function notifyAdmins(referenceId:string,title:string,message:string){const{data}=await adminSupabase.from("users").select("id").eq("role","admin").eq("is_active",true);if(data?.length)await adminSupabase.from("notifications").insert(data.map(admin=>({user_id:admin.id,type:"custom_portal_update",title,message,href:`/admin/custom-portals/${referenceId}`,reference_id:referenceId})))}
