import { LegalDocument, type LegalSection } from "@/components/legal/legal-document";

const sections: LegalSection[]=[
  {title:"Scope",content:<p>This policy covers customer cancellation and refund handling for JobiVerse marketplace services, JobiVerse Personal services and paid CV or digital products. Employer recruitment engagements may instead follow the signed commercial agreement for that mandate.</p>},
  {title:"Unpaid orders",content:<p>An order in pending-payment status may be cancelled instantly without charge because no payment has been captured.</p>},
  {title:"Paid service orders",content:<p>A customer may submit a refund request from the order workspace while the order is paid, in progress, delivered, under revision or completed and before creator payout is completed. Availability of the request form does not guarantee approval. JobiVerse reviews payment verification, agreed scope, work completed, delivery, included revisions, messages and supporting evidence.</p>},
  {title:"Delivered and customized work",content:<p>Services already delivered, substantially performed or customized are generally not automatically refundable. Customers should first review the delivery and request an included in-scope revision where appropriate. Refunds may still be approved for non-delivery, material scope failure, duplicate payment, verified technical failure or another justified exception after review.</p>},
  {title:"Digital CV templates and downloads",content:<p>Before payment, users should review the displayed template preview and description. Once paid digital access or a downloadable file has been unlocked, the purchase is ordinarily non-refundable unless the purchased item is inaccessible, materially different from the paid listing, duplicated, corrupted and not replaceable, or refund rights otherwise apply by law.</p>},
  {title:"Creator payout and disputes",content:<p>If creator payout has already been completed, the automated refund-request route may be unavailable. The customer may open a dispute for exceptional manual review. JobiVerse may seek information from both participants and may pause an eligible payout while a timely dispute is reviewed.</p>},
  {title:"Refund amount",content:<p>An approved refund may be full or partial depending on duplicate charges, undelivered scope, usable work already supplied, agreed milestones and applicable law. JobiVerse will not deduct an undisclosed amount from an approved refund. Any non-refundable component must have a documented basis communicated during review.</p>},
  {title:"Processing and settlement",content:<p>Approved refunds are initiated to the original payment method through the payment gateway. JobiVerse will show the request and gateway status in the relevant workspace. Bank or payment-network settlement commonly requires additional working days after processing; displayed estimates are not a guarantee by the receiving bank.</p>},
  {title:"How to request help",content:<p>Use Request refund or Raise dispute inside the relevant paid order so payment and delivery evidence remain connected. For access problems or a transaction not visible in your account, contact jobiverse@outlook.com or +91 77388 32231 with the registered email and payment/order reference. Do not share card credentials, OTPs or passwords.</p>},
  {title:"Fair use and mandatory rights",content:<p>Fraudulent, abusive or repeated unsupported claims may result in account review. Nothing in this policy removes consumer rights or remedies that cannot be waived under applicable law.</p>},
];
export default function RefundPolicyPage(){return <LegalDocument title="Refund & Cancellation Policy" description="Clear rules for unpaid cancellations, paid service reviews, digital products, disputes and payment settlement." sections={sections}/>;}
