export type JobQualityInput={job_title?:string|null;job_description?:string|null;budget_ctc?:string|null;experience?:string|null;skills?:string|null;location?:string|null;employment_type?:string|null;work_mode?:string|null;education?:string|null};
export type JobQualityIssue={code:string;severity:"critical"|"warning"|"suggestion";title:string;message:string};
export function analyzeJobQuality(input:JobQualityInput){const title=(input.job_title??"").trim();const description=(input.job_description??"").trim();const combined=`${title} ${description}`.toLowerCase();const issues:JobQualityIssue[]=[];const add=(issue:JobQualityIssue)=>issues.push(issue);
if(title.length<4)add({code:"title_missing",severity:"critical",title:"Add a clear role title",message:"Use a recognizable job title candidates can search for."});
if(description.length<180)add({code:"description_short",severity:"critical",title:"Expand the job description",message:"Include responsibilities, outcomes, team context and selection process (minimum 180 characters)."});
if(!input.budget_ctc?.trim())add({code:"salary_missing",severity:"warning",title:"Add salary transparency",message:"A realistic CTC range improves trust and application quality."});
if(!input.location?.trim())add({code:"location_missing",severity:"warning",title:"Clarify work location",message:"Specify city or explicitly state Remote."});
if(!input.employment_type?.trim())add({code:"type_missing",severity:"warning",title:"Choose employment type",message:"Candidates need to know whether this is full-time, contract or internship."});
if(!input.experience?.trim())add({code:"experience_missing",severity:"warning",title:"Add experience expectations",message:"Use a reasonable range rather than an ambiguous seniority label."});
if(!input.skills?.trim())add({code:"skills_missing",severity:"warning",title:"List essential skills",message:"Separate required skills from optional preferences."});
const discriminatory=[/\bmale candidates? only\b/,/\bfemale candidates? only\b/,/\b(unmarried|married) (women|female|men|male)\b/,/\bage (below|under|between|limit)\b/,/\b(hindu|muslim|christian|caste) candidates?\b/];if(discriminatory.some(pattern=>pattern.test(combined)))add({code:"discriminatory_language",severity:"critical",title:"Remove discriminatory criteria",message:"Hiring criteria must relate to lawful role requirements, not gender, age, religion, caste or marital status."});
if(/(registration|security|training|application|interview) fee|pay (₹|rs\.?|inr)|refundable deposit|purchase.*before joining/.test(combined))add({code:"candidate_payment",severity:"critical",title:"Candidate payment language detected",message:"JobiVerse never permits charging candidates to apply, interview or receive an offer."});
if(/whatsapp only|telegram|dm for job|send otp|bank details|upi id/.test(combined))add({code:"unsafe_contact",severity:"critical",title:"Unsafe contact or data request",message:"Keep applications and communication within secure hiring channels; never request OTP or banking credentials."});
if(/rockstar|ninja|guru|young and dynamic|digital native/.test(combined))add({code:"vague_language",severity:"suggestion",title:"Use inclusive, specific language",message:"Replace coded or vague labels with measurable skills and responsibilities."});
const skillCount=(input.skills??"").split(/[,;/|]+/).filter(Boolean).length;if(skillCount>12)add({code:"skills_overload",severity:"warning",title:"Prioritize essential skills",message:"More than 12 required skills can discourage qualified candidates. Move optional skills to the description."});
if(/fresher|entry.level|0.?1 year/.test(combined)&&/(5\+|6\+|7\+|8\+|10\+) years/.test(combined))add({code:"experience_conflict",severity:"critical",title:"Conflicting experience requirement",message:"Entry-level positioning conflicts with the requested years of experience."});
if(!/(responsibilit|you will|role involves|outcomes|day.to.day)/.test(description.toLowerCase()))add({code:"responsibilities_missing",severity:"suggestion",title:"Describe day-to-day outcomes",message:"Candidates respond better when responsibilities and success measures are explicit."});
const deduction={critical:30,warning:12,suggestion:5};const score=Math.max(0,100-issues.reduce((sum,issue)=>sum+deduction[issue.severity],0));return{score,grade:score>=85?"Excellent":score>=70?"Good":score>=50?"Needs improvement":"High risk",issues,canPublish:!issues.some(issue=>issue.severity==="critical")}}
