import Link from "next/link";
import { ArrowLeft, BadgeCheck, Building2, Landmark, ShieldCheck } from "lucide-react";
import { requireRole } from "@/lib/auth/authorization";
import { savePayoutProfile } from "./actions";

export default async function CreatorPayoutProfilePage() {
  const { supabase, user } = await requireRole(["candidate", "creator"]);
  const { data: profile } = await supabase.from("creator_payout_profiles").select("account_holder_name,bank_name,account_number,ifsc_code,upi_id,status,admin_note,updated_at").eq("creator_id", user.id).maybeSingle();
  return <main className="min-h-screen bg-[#f5f5f3] px-5 pb-24 pt-36 sm:px-8"><div className="mx-auto max-w-4xl"><Link href="/earn-with-jobiverse/dashboard/earnings" className="inline-flex items-center gap-2 text-sm font-semibold text-zinc-600"><ArrowLeft size={16}/>Earnings & payouts</Link><section className="mt-8 rounded-[2.75rem] bg-zinc-950 p-8 text-white sm:p-12"><Landmark/><p className="mt-5 text-xs font-bold uppercase tracking-[.18em] text-zinc-500">Secure payout destination</p><h1 className="mt-3 text-4xl font-semibold sm:text-5xl">Bank & payout profile.</h1><p className="mt-4 max-w-2xl text-zinc-400">These details are private and used only by JobiVerse finance for verified creator payouts.</p></section>{profile&&<div className={`mt-6 flex items-start gap-3 rounded-2xl border p-5 ${profile.status==="verified"?"border-emerald-200 bg-emerald-50 text-emerald-800":profile.status==="rejected"?"border-red-200 bg-red-50 text-red-800":"border-amber-200 bg-amber-50 text-amber-800"}`}>{profile.status==="verified"?<BadgeCheck/>:<ShieldCheck/>}<div><p className="font-bold capitalize">Payout profile {profile.status}</p><p className="mt-1 text-sm">{profile.status==="pending"?"JobiVerse Finance will verify these details before transfer.":profile.admin_note??"Your payout destination is ready."}</p></div></div>}<form action={savePayoutProfile} className="mt-6 rounded-[2rem] border border-zinc-200 bg-white p-7 sm:p-9"><div className="grid gap-5 sm:grid-cols-2"><Field label="Account holder name" name="accountHolderName" value={profile?.account_holder_name}/><Field label="Bank name" name="bankName" value={profile?.bank_name}/><Field label="Account number" name="accountNumber" value={profile?.account_number} inputMode="numeric"/><Field label="IFSC code" name="ifscCode" value={profile?.ifsc_code}/><Field label="UPI ID (optional)" name="upiId" value={profile?.upi_id} optional/></div><div className="mt-6 flex items-start gap-3 rounded-xl bg-zinc-50 p-4 text-xs leading-5 text-zinc-500"><Building2 className="shrink-0" size={17}/>Updating verified details sends them for verification again. Confirm the account holder name matches the bank record.</div><button className="mt-6 cursor-pointer rounded-xl bg-zinc-950 px-6 py-3 font-semibold text-white">Save & submit for verification</button></form></div></main>;
}

function Field({label,name,value,inputMode,optional}:{label:string;name:string;value?:string|null;inputMode?:"numeric";optional?:boolean}){return <label className="text-sm font-semibold text-zinc-700">{label}<input name={name} required={!optional} minLength={optional?undefined:2} defaultValue={value??""} inputMode={inputMode} autoComplete="off" className="mt-2 h-12 w-full rounded-xl border border-zinc-200 px-4 font-normal outline-none focus:border-zinc-500"/></label>}
