import Link from "next/link";
import { ArrowLeft, ArrowRight, BadgeCheck, BriefcaseBusiness, Building2, MapPin, Search, ShieldCheck } from "lucide-react";

import { requireRole } from "@/lib/auth/authorization";
import { adminSupabase } from "@/lib/supabase/admin";

export default async function CandidateJobsPage({searchParams}:{searchParams:Promise<{q?:string;location?:string}>}) {
  await requireRole(["candidate"]);
  const filters=await searchParams;const query=(filters.q??"").trim().toLowerCase();const selectedLocation=(filters.location??"").trim();
  const { data: allJobs, error } = await adminSupabase.from("requirements").select("id,job_title,department,employment_type,work_mode,experience,vacancies,location,primary_skills,published_at,company_id,employer_id,companies(company_name,is_verified,industry,location)").eq("is_public", true).not("status", "in", '("Closed","Cancelled")').order("published_at", { ascending: false });
  if (error) throw new Error(error.message);
  const ownerIds=Array.from(new Set((allJobs??[]).filter(job=>!job.companies?.[0]&&job.employer_id).map(job=>job.employer_id)));
  const {data:ownerCompanies}=ownerIds.length?await adminSupabase.from("companies").select("owner_id,company_name,is_verified,industry,location").in("owner_id",ownerIds):{data:[]};
  const ownerCompanyMap=new Map((ownerCompanies??[]).map(company=>[company.owner_id,company]));
  const resolvedCompany=(job:(typeof allJobs)[number])=>job.companies?.[0]||ownerCompanyMap.get(job.employer_id);
  const locations=Array.from(new Set((allJobs??[]).map(job=>job.location||resolvedCompany(job)?.location).filter((value):value is string=>Boolean(value)))).sort();
  const hydratedJobs=(allJobs??[]).map(job=>({...job,companies:job.companies?.length?job.companies:(ownerCompanyMap.get(job.employer_id)?[ownerCompanyMap.get(job.employer_id)!]:[])}));
  const jobs=hydratedJobs.filter(job=>{const company=job.companies?.[0];const searchable=[job.job_title,job.department,job.primary_skills,company?.company_name,company?.industry].filter(Boolean).join(" ").toLowerCase();const location=job.location||company?.location||"";return(!query||searchable.includes(query))&&(!selectedLocation||location===selectedLocation)});

  return <main className="min-h-screen bg-[#f5f5f3] px-5 pb-24 pt-36 sm:px-8"><div className="mx-auto max-w-7xl">
    <div className="flex flex-wrap items-center justify-between gap-3"><Link href="/candidates/dashboard" className="inline-flex items-center gap-2 rounded-full border bg-white px-4 py-2 text-sm"><ArrowLeft size={16}/>Dashboard</Link><Link href="/candidates/applications" className="rounded-full bg-zinc-950 px-5 py-2 text-sm font-semibold text-white">Career Activity</Link></div>
    <section className="my-8 rounded-[2.5rem] bg-zinc-950 p-9 text-white sm:p-12"><p className="text-xs font-bold uppercase tracking-[.2em] text-zinc-400">JobiVerse Jobs Portal</p><h1 className="mt-4 text-4xl font-semibold sm:text-6xl">Active opportunities.</h1><p className="mt-5 text-zinc-300">Search roles and locations, then open any opportunity for complete details.</p></section>
    <form className="mb-6 grid gap-3 rounded-[2rem] border border-zinc-200 bg-white p-4 shadow-sm md:grid-cols-[1fr_280px_auto]" action="/candidates/jobs"><label className="relative"><Search className="absolute left-4 top-1/2 -translate-y-1/2 text-zinc-400" size={18}/><span className="sr-only">Search jobs</span><input name="q" defaultValue={filters.q??""} placeholder="Search role, skill, company or industry" className="h-13 w-full rounded-xl border border-zinc-200 pl-12 pr-4 outline-none focus:border-zinc-500"/></label><label><span className="sr-only">Filter by location</span><select name="location" defaultValue={selectedLocation} className="h-13 w-full cursor-pointer rounded-xl border border-zinc-200 bg-white px-4 outline-none focus:border-zinc-500"><option value="">All locations</option>{locations.map(location=><option key={location} value={location}>{location}</option>)}</select></label><button className="h-13 cursor-pointer rounded-xl bg-zinc-950 px-7 font-semibold text-white">Search jobs</button></form>
    {(query||selectedLocation)&&<div className="mb-6 flex items-center justify-between gap-3 rounded-2xl bg-zinc-100 px-5 py-3 text-sm"><p><strong>{jobs.length}</strong> matching opportunities</p><Link href="/candidates/jobs" className="font-semibold underline">Clear filters</Link></div>}
    <section className="mb-8 flex items-start gap-4 rounded-3xl border border-amber-200 bg-amber-50 p-5 text-amber-950"><ShieldCheck className="mt-0.5 shrink-0"/><div><h2 className="font-bold">Jobs are never sold to candidates.</h2><p className="mt-1 text-sm leading-6">Do not pay anyone for a JobiVerse application or interview. Report suspicious activity from the detailed job page.</p></div></section>
    {!jobs.length?<div className="rounded-3xl border border-dashed bg-white p-16 text-center"><BriefcaseBusiness className="mx-auto text-zinc-400"/><h2 className="mt-5 text-2xl font-semibold">No matching opportunities</h2><p className="mt-2 text-zinc-500">Try another keyword or clear the location filter.</p></div>:<section className="grid gap-5 md:grid-cols-2 xl:grid-cols-3">{jobs.map((job)=>{const company=job.companies?.[0];return <Link href={`/candidates/jobs/${job.id}`} key={job.id} className="group flex min-h-full flex-col rounded-[2rem] border border-zinc-200 bg-white p-6 shadow-sm transition duration-300 hover:-translate-y-1 hover:border-zinc-400 hover:shadow-xl"><div className="flex items-start justify-between gap-3"><span className="grid h-12 w-12 place-items-center rounded-2xl bg-zinc-950 text-white"><BriefcaseBusiness size={20}/></span><span className="rounded-full bg-emerald-50 px-3 py-1 text-[10px] font-bold uppercase text-emerald-700">Actively hiring</span></div><div className="mt-6 flex flex-wrap items-center gap-2"><p className="text-sm font-semibold text-zinc-600">{company?.company_name||"JobiVerse hiring partner"}</p>{company?.is_verified&&<BadgeCheck size={15} className="text-emerald-600"/>}</div><h2 className="mt-2 text-2xl font-semibold tracking-tight text-zinc-950">{job.job_title}</h2><div className="mt-5 grid grid-cols-2 gap-2 text-xs"><Essential label="Experience" value={job.experience||"Open"}/><Essential label="Work mode" value={job.work_mode||"Flexible"}/><Essential label="Type" value={job.employment_type||"Not specified"}/><Essential label="Openings" value={String(job.vacancies||1)}/></div><p className="mt-5 flex items-center gap-2 text-sm text-zinc-500"><MapPin size={15}/>{job.location||company?.location||"India"}</p><p className="mt-3 flex items-center gap-2 text-sm text-zinc-500"><Building2 size={15}/>{company?.industry||job.department||"Industry not specified"}</p><p className="mt-5 line-clamp-2 rounded-xl bg-zinc-50 p-4 text-sm leading-6 text-zinc-600">{job.primary_skills||"Role-specific skills available in complete details."}</p><div className="mt-auto flex items-center justify-between border-t border-zinc-100 pt-5 text-sm font-semibold">View complete role <ArrowRight size={16} className="transition group-hover:translate-x-1"/></div></Link>})}</section>}
  </div></main>;
}

function Essential({label,value}:{label:string;value:string}){return <div className="rounded-xl bg-zinc-50 p-3"><p className="text-[10px] font-bold uppercase tracking-wider text-zinc-400">{label}</p><p className="mt-1 truncate font-semibold text-zinc-700">{value}</p></div>}
