import Link from "next/link";
import { BadgeIndianRupee, CalendarClock, FileText, ShieldCheck } from "lucide-react";
import { requireRole } from "@/lib/auth/authorization";
import { getEmployerCompanyAccess, scopeEmployerJoinedRequirementQuery } from "@/lib/employer-team/access";

const money=new Intl.NumberFormat("en-IN",{style:"currency",currency:"INR",maximumFractionDigits:2});
const tones:Record<string,string>={paid:"bg-emerald-100 text-emerald-700",overdue:"bg-red-100 text-red-700",partially_paid:"bg-amber-100 text-amber-700",invoiced:"bg-blue-100 text-blue-700",cancelled:"bg-zinc-200 text-zinc-600",not_invoiced:"bg-zinc-100 text-zinc-600"};

export default async function EmployerBillingPage(){
  const{supabase,user}=await requireRole(["employer"]);
  const access=await getEmployerCompanyAccess(user.id);
  const{data,error}=await scopeEmployerJoinedRequirementQuery(supabase.from("placements").select("id,offered_ctc,fee_percentage,placement_fee,gst_amount,invoice_number,invoice_date,payment_due_date,payment_status,replacement_end_date,status,candidates(full_name),requirements!inner(job_title,employer_id,company_id,fee_percentage,minimum_fee,replacement_days,companies(company_name))"),access,user.id).order("created_at",{ascending:false});
  if(error)throw new Error(error.message);
  const rows=(data??[]) as any[];
  const invoiced=rows.filter((item:any)=>item.payment_status!=="not_invoiced"&&item.payment_status!=="cancelled");
  const outstanding=invoiced.filter((item:any)=>item.payment_status!=="paid").reduce((sum:number,item:any)=>sum+Number(item.placement_fee??0)+Number(item.gst_amount??0),0);
  return <main className="min-h-screen bg-[#f5f5f3] px-5 pb-24 pt-36 sm:px-8"><div className="mx-auto max-w-7xl">
    <section className="relative overflow-hidden rounded-[2.75rem] bg-zinc-950 p-8 text-white sm:p-12"><div className="absolute -right-16 -top-20 h-72 w-72 rounded-full border border-white/10"/><BadgeIndianRupee/><p className="mt-5 text-xs font-bold uppercase tracking-[.18em] text-zinc-500">Employer finance workspace</p><h1 className="mt-3 text-4xl font-semibold sm:text-6xl">Recruitment billing.</h1><p className="mt-4 max-w-3xl text-zinc-400">Commercial terms, success fees, replacement coverage and payment status linked to real placements.</p></section>
    <section className="mt-7 grid gap-4 sm:grid-cols-3"><Stat label="Placement records" value={String(rows.length)} icon={<ShieldCheck/>}/><Stat label="Invoices issued" value={String(invoiced.length)} icon={<FileText/>}/><Stat label="Outstanding" value={money.format(outstanding)} icon={<CalendarClock/>}/></section>
    <section className="mt-7"><div className="mb-5"><h2 className="text-2xl font-bold">Commercial records</h2><p className="mt-1 text-sm text-zinc-500">A statutory tax invoice is available only after JobiVerse issues an invoice number and date.</p></div>{rows.length?<div className="grid gap-5 xl:grid-cols-2">{rows.map((item:any)=>{const req=Array.isArray(item.requirements)?item.requirements[0]:item.requirements;const candidate=Array.isArray(item.candidates)?item.candidates[0]:item.candidates;const total=Number(item.placement_fee??0)+Number(item.gst_amount??0);return <article key={item.id} className="rounded-[2rem] border border-zinc-200 bg-white p-7 shadow-sm"><div className="flex items-start justify-between gap-4"><div><p className="text-xs font-bold uppercase tracking-wider text-zinc-400">{companyName(req?.companies)}</p><h3 className="mt-2 text-xl font-bold">{candidate?.full_name??"Placement"}</h3><p className="mt-1 text-sm text-zinc-500">{req?.job_title}</p></div><span className={`rounded-full px-3 py-1 text-xs font-bold capitalize ${tones[item.payment_status]??tones.not_invoiced}`}>{item.payment_status.replaceAll("_"," ")}</span></div><div className="mt-6 grid grid-cols-2 gap-3 sm:grid-cols-4"><Metric label="Success fee" value={item.fee_percentage?`${item.fee_percentage}%`:"Pending"}/><Metric label="Professional fee" value={item.placement_fee?money.format(item.placement_fee):"Pending"}/><Metric label="GST" value={item.gst_amount?money.format(item.gst_amount):"Pending"}/><Metric label="Total" value={item.placement_fee?money.format(total):"Pending"}/></div><div className="mt-5 flex flex-wrap items-center justify-between gap-3 border-t border-zinc-100 pt-5"><p className="text-xs text-zinc-500">Replacement coverage: {item.replacement_end_date?`until ${new Date(item.replacement_end_date).toLocaleDateString("en-IN")}`:`${req?.replacement_days??0} days after joining`}</p>{item.invoice_number?<Link href={`/employers/billing/${item.id}`} className="rounded-xl bg-zinc-950 px-5 py-3 text-sm font-semibold text-white">View statement</Link>:<span className="rounded-xl bg-zinc-100 px-4 py-2 text-xs font-semibold text-zinc-500">Invoice not issued</span>}</div></article>})}</div>:<div className="rounded-[2rem] border border-dashed border-zinc-300 bg-white p-16 text-center text-zinc-500">No placement billing records yet.</div>}</section>
  </div></main>;
}
function Stat({label,value,icon}:{label:string;value:string;icon:React.ReactNode}){return <article className="rounded-3xl border border-zinc-200 bg-white p-6"><div className="text-zinc-400">{icon}</div><p className="mt-5 text-sm text-zinc-500">{label}</p><p className="mt-2 text-3xl font-bold">{value}</p></article>}
function Metric({label,value}:{label:string;value:string}){return <div className="rounded-2xl bg-zinc-50 p-4"><p className="text-[10px] uppercase tracking-wider text-zinc-400">{label}</p><p className="mt-2 text-sm font-bold">{value}</p></div>}
function companyName(value:{company_name?:string|null}|Array<{company_name?:string|null}>|null|undefined){return (Array.isArray(value)?value[0]:value)?.company_name??"Your company"}
