import type { Metadata } from "next";
import Link from "next/link";
import { ArrowRight, BookOpenCheck, ShieldCheck } from "lucide-react";
import { guides } from "@/lib/guides";
import { JoviGuide } from "@/components/brand/jovi-guide";

export const metadata: Metadata = { title:"Help & Guides | JobiVerse", description:"Creative role-specific guides for JobiVerse employers, candidates, creators and recruiters." };

export default function GuidesPage(){return <main className="min-h-screen bg-[#f5f5f3] px-5 pb-24 pt-36 sm:px-8"><div className="mx-auto max-w-[1450px]">
  <section className="jv-noise relative overflow-hidden rounded-[3rem] bg-[radial-gradient(circle_at_85%_15%,rgba(124,58,237,.34),transparent_25rem),linear-gradient(135deg,#09090b,#18181b_60%,#3f3f46)] p-8 text-white shadow-2xl sm:p-14 lg:p-20">
    <div aria-hidden="true" className="absolute -right-24 -top-28 h-96 w-96 rounded-full border border-white/10"/><div aria-hidden="true" className="absolute right-20 top-24 h-48 w-48 rounded-full border border-white/10"/>
    <div className="relative"><BookOpenCheck size={31}/><p className="mt-6 text-xs font-bold uppercase tracking-[.2em] text-zinc-400">Help & Guides</p><h1 className="mt-4 max-w-4xl text-5xl font-semibold tracking-[-.055em] sm:text-7xl">Learn your universe.<br/><span className="text-zinc-500">Move with confidence.</span></h1><p className="mt-6 max-w-2xl text-lg leading-8 text-zinc-300">Choose what you want to do on JobiVerse. Every visual guide explains the available tools, recommended journey and important commercial or safety rules.</p></div>
  </section>
  <div className="mt-8 max-w-2xl"><JoviGuide title="I’ll help you choose the right guide" message="Start with your role, then follow the visual journey. I’ll keep the important safety, pricing and workflow details easy to spot." href="/guides/features" action="See every JobiVerse feature" /></div><section className="mt-8 grid gap-5 md:grid-cols-2 xl:grid-cols-3">{guides.map(guide=>{const Icon=guide.icon;return <Link key={guide.slug} href={`/guides/${guide.slug}`} className="group flex min-h-72 flex-col overflow-hidden rounded-[2rem] border border-zinc-200 bg-white p-7 shadow-sm transition duration-300 hover:-translate-y-1 hover:shadow-xl"><div className="flex items-center justify-between"><span className="grid h-12 w-12 place-items-center rounded-2xl bg-zinc-950 text-white transition group-hover:bg-violet-600"><Icon size={21}/></span><span className="rounded-full bg-zinc-100 px-3 py-1 text-[10px] font-bold uppercase tracking-wider text-zinc-500">{guide.audience}</span></div><h2 className="mt-7 text-2xl font-semibold tracking-tight">{guide.title}</h2><p className="mt-3 flex-1 text-sm leading-6 text-zinc-600">{guide.description}</p><span className="mt-7 inline-flex items-center gap-2 text-sm font-bold">Enter this guide <ArrowRight className="transition group-hover:translate-x-1" size={16}/></span></Link>})}</section>
  <section className="mt-8 flex flex-col gap-5 rounded-[2rem] border border-emerald-200 bg-emerald-50 p-7 sm:flex-row sm:items-center"><ShieldCheck className="shrink-0 text-emerald-700" size={28}/><div><h2 className="text-xl font-semibold text-emerald-950">Platform truth comes first.</h2><p className="mt-2 text-sm leading-6 text-emerald-800">Paid, controlled and production-dependent capabilities are identified in the relevant guide. JobiVerse never charges candidates to apply or interview.</p></div></section>
</div></main>}
