"use client";

import { useMemo, useState, useTransition } from "react";
import { BadgeCheck, LoaderCircle, Plus, Send, X } from "lucide-react";
import { customPortalIndustries, getCustomPortalIndustry } from "@/lib/custom-portals/catalog";
import { submitCustomPortalRequest, type PortalRequestState } from "@/app/employers/custom-portal/actions";

const inputClass="h-12 w-full rounded-xl border border-violet-100 bg-white px-4 outline-none transition focus:border-violet-500";
export function CustomPortalRequestForm(){
  const [industry,setIndustry]=useState<string>(customPortalIndustries[0].slug);const [selected,setSelected]=useState<string[]>([]);const [customModuleInput,setCustomModuleInput]=useState("");const [customModules,setCustomModules]=useState<string[]>([]);const [state,setState]=useState<PortalRequestState|null>(null);const [pending,startTransition]=useTransition();
  const pack=useMemo(()=>getCustomPortalIndustry(industry),[industry]);
  function changeIndustry(value:string){setIndustry(value);setSelected([]);setState(null)}
  function addCustomModule(){const moduleName=customModuleInput.trim();if(!moduleName)return;setCustomModules(items=>items.some(item=>item.toLowerCase()===moduleName.toLowerCase())?items:[...items,moduleName]);setCustomModuleInput("");setState(null)}
  function removeCustomModule(module:string){setCustomModules(items=>items.filter(item=>item!==module));setState(null)}
  function toggle(module:string){setSelected(items=>items.includes(module)?items.filter(item=>item!==module):[...items,module])}
  function submit(formData:FormData){setState(null);startTransition(async()=>setState(await submitCustomPortalRequest({organisationName:formData.get("organisationName"),contactName:formData.get("contactName"),email:formData.get("email"),phone:formData.get("phone"),industry,companySize:formData.get("companySize"),website:formData.get("website"),selectedModules:selected,customModules:customModules.join("\n"),requirements:formData.get("requirements"),expectedUsers:formData.get("expectedUsers"),integrations:formData.get("integrations"),timeline:formData.get("timeline"),budgetRange:formData.get("budgetRange"),callbackRequested:formData.get("callbackRequested")==="on",websiteGuard:formData.get("websiteGuard")})))}
  if(state?.success)return <div className="rounded-[2rem] border border-emerald-200 bg-emerald-50 p-8"><BadgeCheck className="text-emerald-700" size={34}/><h2 className="mt-4 text-2xl font-bold">Brief received.</h2><p className="mt-2 text-zinc-600">{state.message}</p><p className="mt-5 inline-flex rounded-full bg-white px-4 py-2 text-sm font-bold text-emerald-800">Reference: {state.reference}</p></div>;
  return <form action={submit} className="space-y-8 rounded-[2.25rem] border border-violet-100 bg-white p-6 shadow-xl shadow-violet-950/5 sm:p-9">
    <div><p className="text-xs font-black uppercase tracking-[.18em] text-violet-700">01 · Your organisation</p><div className="mt-4 grid gap-4 sm:grid-cols-2"><input className={inputClass} name="organisationName" required placeholder="Organisation name *"/><input className={inputClass} name="contactName" required placeholder="Contact person *"/><input className={inputClass} name="email" type="email" required placeholder="Work email *"/><input className={inputClass} name="phone" required placeholder="Phone / WhatsApp *"/><select className={inputClass} name="companySize" defaultValue=""><option value="">Team size</option><option>1–20</option><option>21–100</option><option>101–500</option><option>501–2,000</option><option>2,000+</option></select><input className={inputClass} name="website" placeholder="Website (optional)"/></div><input className="hidden" tabIndex={-1} autoComplete="off" name="websiteGuard"/></div>
    <div><p className="text-xs font-black uppercase tracking-[.18em] text-violet-700">02 · Choose an industry starting point</p><select className={`${inputClass} mt-4`} value={industry} onChange={e=>changeIndustry(e.target.value)}>{customPortalIndustries.map(item=><option key={item.slug} value={item.slug}>{item.label}</option>)}</select><p className="mt-3 text-sm text-zinc-500">{pack.summary}</p><div className="mt-4 grid gap-3 sm:grid-cols-2">{pack.modules.map(module=><button type="button" key={module} onClick={()=>toggle(module)} className={`flex min-h-14 items-center gap-3 rounded-2xl border p-4 text-left text-sm font-semibold transition ${selected.includes(module)?"border-violet-600 bg-violet-50 text-violet-950":"border-zinc-200 hover:border-violet-300"}`}><span className={`grid h-7 w-7 shrink-0 place-items-center rounded-full ${selected.includes(module)?"bg-violet-700 text-white":"bg-zinc-100"}`}>{selected.includes(module)?<BadgeCheck size={15}/>:<Plus size={15}/>}</span>{module}</button>)}</div><div className="mt-4 rounded-2xl border border-violet-100 p-4"><label className="text-xs font-black uppercase tracking-[.16em] text-violet-700">Your own module</label><div className="mt-3 flex gap-2"><input value={customModuleInput} onChange={event=>setCustomModuleInput(event.target.value)} onKeyDown={event=>{if(event.key==="Enter"){event.preventDefault();addCustomModule()}}} className={inputClass} placeholder="e.g. Vendor approval workflow"/><button type="button" onClick={addCustomModule} aria-label="Add custom module" className="grid h-12 w-12 shrink-0 place-items-center rounded-xl bg-violet-950 text-white"><Plus size={20}/></button></div>{customModules.length>0&&<div className="mt-3 flex flex-wrap gap-2">{customModules.map(module=><span key={module} className="inline-flex items-center gap-2 rounded-full bg-violet-50 px-3 py-2 text-xs font-bold text-violet-950">{module}<button type="button" onClick={()=>removeCustomModule(module)} aria-label={`Remove ${module}`} className="text-violet-500 hover:text-violet-950"><X size={14}/></button></span>)}</div>}<p className="mt-3 text-xs text-zinc-500">Add one module at a time. Each plus adds ₹500 to setup.</p></div><PriceCalculator selected={selected.length} custom={customModules.length}/></div>
    <div><p className="text-xs font-black uppercase tracking-[.18em] text-violet-700">03 · Describe the outcome</p><textarea name="requirements" required minLength={20} rows={6} className="mt-4 w-full rounded-xl border border-violet-100 p-4 outline-none focus:border-violet-500" placeholder="What should this portal solve? Explain your current workflow, users and pain points. *"/><div className="mt-4 grid gap-4 sm:grid-cols-2"><input className={inputClass} name="expectedUsers" placeholder="Expected portal users"/><input className={inputClass} name="integrations" placeholder="Tools/integrations needed"/><select className={inputClass} name="timeline" defaultValue=""><option value="">Preferred timeline</option><option>Within 1 month</option><option>1–3 months</option><option>3–6 months</option><option>Exploring</option></select><select className={inputClass} name="budgetRange" defaultValue=""><option value="">Indicative budget (optional)</option><option>Below ₹1 lakh</option><option>₹1–3 lakh</option><option>₹3–10 lakh</option><option>₹10 lakh+</option><option>Need guidance</option></select></div><label className="mt-4 flex items-start gap-3 text-sm text-zinc-600"><input type="checkbox" name="callbackRequested" className="mt-1"/>Request a discovery call from JobiVerse</label></div>
    {state&&!state.success&&<p className="rounded-xl bg-red-50 p-4 text-sm font-semibold text-red-700">{state.message}</p>}<p className="text-xs leading-5 text-zinc-500">Sample modules are examples, not a fixed product promise. Final scope, security, timeline and commercials are confirmed after discovery.</p><button disabled={pending} className="inline-flex min-h-13 w-full items-center justify-center gap-2 rounded-2xl bg-violet-950 px-6 font-bold text-white disabled:opacity-60">{pending?<LoaderCircle className="animate-spin" size={18}/>:<Send size={18}/>} {pending?"Submitting brief…":"Submit custom portal brief"}</button>
  </form>}
function PriceCalculator({selected,custom}:{selected:number;custom:number}){const modules=selected+custom;const setup=modules*500;const annual=4999;return <div className="mt-5 rounded-[1.75rem] border border-violet-200 bg-violet-50 p-5"><div className="flex flex-wrap items-end justify-between gap-4"><div><p className="text-xs font-black uppercase tracking-[.18em] text-violet-700">Live final price</p><p className="mt-2 text-sm text-zinc-600">{modules?`${modules} requested module${modules===1?"":"s"} × ₹500` : "Add modules to calculate setup"}</p></div><div className="text-right"><p className="text-sm font-bold text-zinc-600">Setup: ₹{setup.toLocaleString("en-IN")}</p><p className="text-sm font-bold text-zinc-600">Annual platform: ₹{annual.toLocaleString("en-IN")}</p><p className="mt-1 text-2xl font-black text-violet-950">First year: ₹{(setup+annual).toLocaleString("en-IN")}</p></div></div><p className="mt-3 text-xs leading-5 text-zinc-500">Only requested modules are included—there are no default modules. Renewal is ₹4,999/year. Integrations or data migration, if requested, are quoted separately before acceptance.</p></div>}
