import Link from "next/link";
import { redirect } from "next/navigation";
import { ArrowLeft, ArrowRight, PackageCheck } from "lucide-react";
import { createServerSupabaseClient } from "@/lib/supabase/server";
import { OrderStatusBadge } from "@/components/marketplace/order-status-badge";
import { filterOrders, OrderFilterTabs } from "@/components/marketplace/order-filter-tabs";

export default async function CreatorOrdersPage({searchParams}:{searchParams:Promise<{status?:string}>}){
  const supabase=await createServerSupabaseClient();const {data:{user}}=await supabase.auth.getUser();if(!user)redirect("/login/creator?next=/earn-with-jobiverse/dashboard/orders");
  const {data:profile}=await supabase.from("users").select("role").eq("id",user.id).maybeSingle();if(!profile?.role||!["candidate","creator"].includes(profile.role))redirect("/login/creator?error=creator_required");
  const {data:dbOrders}=await supabase.from("marketplace_orders").select("id,amount:creator_earning,status,requirements,created_at,marketplace_services(title)").eq("provider_id",user.id).order("created_at",{ascending:false});
  const orderIds=(dbOrders??[]).map(order=>order.id);const[{data:activeDisputes},{data:unreadUpdates}]=await Promise.all([orderIds.length?supabase.from("marketplace_disputes").select("order_id").in("order_id",orderIds).in("status",["open","reviewing"]):Promise.resolve({data:[]}),orderIds.length?supabase.from("notifications").select("reference_id").eq("user_id",user.id).in("reference_id",orderIds).is("read_at",null):Promise.resolve({data:[]})]);const disputedOrderIds=new Set((activeDisputes??[]).map(item=>item.order_id));const updatedOrderIds=new Set((unreadUpdates??[]).map(item=>item.reference_id));const rawOrders=(dbOrders??[]).map(order=>({...order,isDisputed:disputedOrderIds.has(order.id)}));
  const {status="all"}=await searchParams;const orders=filterOrders(rawOrders??[],status);
  return <main className="min-h-screen bg-[#f5f5f3] px-5 pb-24 pt-36 sm:px-8"><div className="mx-auto max-w-6xl"><Link href="/earn-with-jobiverse/dashboard" className="inline-flex items-center gap-2 text-sm font-semibold text-zinc-600"><ArrowLeft size={16}/>Creator dashboard</Link><section className="mt-8 rounded-[2.75rem] bg-zinc-950 p-8 text-white sm:p-12"><p className="text-xs font-bold uppercase tracking-[.18em] text-zinc-500">Creator workspace</p><h1 className="mt-4 text-4xl font-semibold tracking-[-.04em] sm:text-6xl">Orders.</h1><p className="mt-4 text-zinc-400">Start work, deliver files, handle revisions and track payout eligibility.</p></section>{!!rawOrders?.length&&<OrderFilterTabs basePath="/earn-with-jobiverse/dashboard/orders" active={status} orders={rawOrders}/>}<section className="mt-7 rounded-[2rem] border border-zinc-200 bg-white p-7">{orders.length?<div className="space-y-3">{orders.map(order=>{const service=Array.isArray(order.marketplace_services)?order.marketplace_services[0]:order.marketplace_services;return <article key={order.id} className={`rounded-2xl border p-5 transition ${updatedOrderIds.has(order.id)?"border-violet-400 bg-violet-50 shadow-lg ring-2 ring-violet-200":order.status==="completed"?"border-emerald-200 bg-emerald-50/50":"border-zinc-100 bg-zinc-50"}`}><div className="flex flex-wrap items-start justify-between gap-3"><div>{updatedOrderIds.has(order.id)&&<span className="mb-2 inline-flex rounded-full bg-violet-600 px-3 py-1 text-[10px] font-bold uppercase tracking-wider text-white">New update</span>}<h2 className="font-semibold">{service?.title??"Service order"}</h2><p className="mt-2 text-sm text-zinc-500">Your earning ₹{Number(order.amount).toLocaleString("en-IN")} | {new Date(order.created_at).toLocaleDateString("en-IN")}</p></div><OrderStatusBadge status={order.status}/></div>{order.requirements&&<p className="mt-3 line-clamp-2 text-sm text-zinc-600">{order.requirements}</p>}<Link href={`/earn-with-jobiverse/dashboard/orders/${order.id}`} className="mt-5 inline-flex items-center gap-2 rounded-xl bg-zinc-950 px-5 py-3 text-sm font-semibold text-white">Open workspace <ArrowRight size={15}/></Link></article>})}</div>:<div className="py-16 text-center"><PackageCheck className="mx-auto text-zinc-300" size={42}/><h2 className="mt-5 text-xl font-semibold">No {status==="all"?"":"matching "}orders</h2><p className="mt-2 text-sm text-zinc-500">Orders in this stage will appear here automatically.</p></div>}</section></div></main>;
}




