"use client";

import { useEffect, useState } from "react";
import { Camera, Download, LayoutTemplate, Pencil, Plus, Scissors, Trash2 } from "lucide-react";
import { getResumeTemplate, resumeTemplates } from "@/lib/resume-templates";
import RichResumeDocument from "@/components/candidate/RichResumeDocument";

type Initial = { full_name?: string | null; email?: string | null; headline?: string | null; phone?: string | null; current_location?: string | null; bio?: string | null; primary_skills?: string | null; current_company?: string | null; total_experience?: string | null };
export default function EditableResumeBuilder({ initial, defaultTemplate, unlocked = false, autoDownload = false }: { initial: Initial; defaultTemplate: string; unlocked?: boolean; autoDownload?: boolean }) {
  const initialDesign = getResumeTemplate(defaultTemplate);
  const [template, setTemplate] = useState(initialDesign.id);
  const [photoUrl, setPhotoUrl] = useState<string | null>(null); const [pageCount, setPageCount] = useState(initialDesign.multiPage ? 2 : 1); const [customizing, setCustomizing] = useState(false); const [customAccent, setCustomAccent] = useState(initialDesign.accent); const [customFont, setCustomFont] = useState("system");
  const [directEditing, setDirectEditing] = useState(false);
  const [savedHtml, setSavedHtml] = useState<string | null>(null);
  const [fontScale, setFontScale] = useState(1);
  const [data, setData] = useState({ name: initial.full_name ?? "Your Name", title: initial.headline ?? "Professional Headline", email: initial.email ?? "email@example.com", phone: initial.phone ?? "+91 00000 00000", location: initial.current_location ?? "Mumbai, India", summary: initial.bio ?? "Write a compelling professional summary that highlights your experience, strengths and career direction.", skills: initial.primary_skills ?? "Communication, Problem Solving, Leadership", experience: initial.current_company ? `${initial.headline ?? "Professional"} - ${initial.current_company}\nDescribe your responsibilities, measurable achievements and business impact.` : "Role - Company\nDescribe your responsibilities, measurable achievements and business impact.", education: "Degree - University\nGraduation year and relevant achievements", projects: "Project or Achievement\nExplain the challenge, your contribution and measurable result.", certifications: "Professional Certification - Issuing Organization", languages: "English - Professional\nHindi - Native" });
  useEffect(() => () => { if (photoUrl) URL.revokeObjectURL(photoUrl); }, [photoUrl]);
  useEffect(() => { setSavedHtml(window.localStorage.getItem(`jobiverse-cv-${template}`)); }, [template]);
  useEffect(() => {
    if (!autoDownload || !unlocked) return;
    const timer = window.setTimeout(() => window.print(), 500);
    return () => window.clearTimeout(timer);
  }, [autoDownload, unlocked]);
  function update(name: keyof typeof data, value: string) { setData((current) => ({ ...current, [name]: value })); }
  function removeSelectedSection() { const node = window.getSelection()?.anchorNode; const element = node instanceof Element ? node : node?.parentElement; const section = element?.closest("[data-cv-section]"); if (section) section.remove(); }
  const design = getResumeTemplate(template); const accent = customizing ? customAccent : design.accent; const sidebar = ["sidebar", "split", "geometric"].includes(design.layout); const fresh = design.layout === "minimal"; const centered = [3, 7, 9].includes(design.headerStyle); const serif = design.layout === "editorial"; const fontFamily = customFont === "arial" ? "Arial, sans-serif" : customFont === "georgia" ? "Georgia, serif" : customFont === "times" ? "'Times New Roman', serif" : customFont === "garamond" ? "Garamond, Georgia, serif" : customFont === "verdana" ? "Verdana, sans-serif" : customFont === "helvetica" ? "Helvetica, Arial, sans-serif" : serif ? "Georgia, serif" : undefined;
  return <div className="cv-builder-print-root grid gap-7 xl:grid-cols-[.78fr_1.22fr]">
    <section className="print:hidden rounded-[2rem] border border-white bg-white/90 p-7 shadow-sm"><div className="flex items-center gap-3"><LayoutTemplate /><div><h2 className="text-xl font-semibold">CV Editor</h2><p className="text-sm text-zinc-500">Changes appear instantly in the preview.</p></div></div>
      <label className="mt-6 block text-sm font-medium text-zinc-700">Template<select value={template} onChange={(event) => setTemplate(event.target.value)} className="mt-2 h-12 w-full rounded-xl border border-zinc-200 bg-zinc-50 px-4 outline-none">{resumeTemplates.map((item) => <option key={item.id} value={item.id}>{item.name} - {item.family}</option>)}</select></label>
      {design.supportsPhoto ? <label className="mt-6 flex cursor-pointer items-center justify-center gap-2 rounded-xl border border-dashed border-zinc-300 bg-zinc-50 px-4 py-4 text-sm font-semibold"><Camera size={18} />{photoUrl ? "Replace Profile Photo" : "Add Profile Photo"}<input type="file" accept="image/png,image/jpeg,image/webp" className="sr-only" onChange={(event) => { const file = event.target.files?.[0]; if (file) setPhotoUrl(URL.createObjectURL(file)); }} /></label> : <p className="mt-6 rounded-xl bg-zinc-50 px-4 py-3 text-sm text-zinc-500">This professional layout is intentionally photo-free.</p>}
      <div className="mt-3 grid grid-cols-2 gap-3"><button type="button" onClick={() => setPageCount((count) => Math.min(count + 1, 6))} className="inline-flex items-center justify-center gap-2 rounded-xl bg-zinc-950 px-4 py-3 text-sm font-semibold text-white"><Plus size={17} /> Add Page</button><button type="button" onClick={() => { window.location.href = `/candidates/resume-builder/edit?template=${template}`; }} className="inline-flex items-center justify-center gap-2 rounded-xl border border-zinc-300 bg-white px-4 py-3 text-sm font-semibold"><Pencil size={17} /> Edit Template Yourself</button></div>
      <div className="mt-3 flex items-center justify-between rounded-xl bg-zinc-50 px-4 py-3 text-sm"><span>{pageCount} A4 {pageCount === 1 ? "page" : "pages"}</span>{pageCount > 1 && <button type="button" onClick={() => setPageCount((count) => Math.max(1, count - 1))} className="inline-flex items-center gap-1 font-semibold text-red-600"><Trash2 size={15} /> Remove Last</button>}</div>
      {customizing && <div className="mt-4 rounded-2xl border border-zinc-200 bg-zinc-50 p-4"><p className="text-sm font-semibold">Design controls</p><div className="mt-4 grid gap-4 sm:grid-cols-2"><label className="text-xs font-medium">Accent colour<input type="color" value={customAccent} onChange={(event) => setCustomAccent(event.target.value)} className="mt-2 h-11 w-full rounded-lg border border-zinc-200 bg-white p-1" /></label><label className="text-xs font-medium">Font style<select value={customFont} onChange={(event) => setCustomFont(event.target.value)} className="mt-2 h-11 w-full rounded-lg border border-zinc-200 bg-white px-3"><option value="system">Template Default</option><option value="arial">Arial</option><option value="helvetica">Helvetica</option><option value="verdana">Verdana</option><option value="georgia">Georgia</option><option value="garamond">Garamond</option><option value="times">Times New Roman</option></select></label></div><p className="mt-3 text-xs text-zinc-500">All content fields below are fully editable.</p></div>}
      <div className="mt-7 space-y-4"><Field label="Full name" value={data.name} onChange={(value) => update("name", value)} /><Field label="Professional headline" value={data.title} onChange={(value) => update("title", value)} /><div className="grid gap-4 sm:grid-cols-2"><Field label="Email" value={data.email} onChange={(value) => update("email", value)} /><Field label="Phone" value={data.phone} onChange={(value) => update("phone", value)} /></div><Field label="Location" value={data.location} onChange={(value) => update("location", value)} /><Area label="Professional summary" value={data.summary} onChange={(value) => update("summary", value)} /><Area label="Skills (comma separated)" value={data.skills} onChange={(value) => update("skills", value)} /><Area label="Experience" value={data.experience} onChange={(value) => update("experience", value)} /><Area label="Education" value={data.education} onChange={(value) => update("education", value)} />{pageCount > 1 && <><Area label="Projects & achievements" value={data.projects} onChange={(value) => update("projects", value)} /><Area label="Certifications" value={data.certifications} onChange={(value) => update("certifications", value)} /><Area label="Languages" value={data.languages} onChange={(value) => update("languages", value)} /></>}</div>
      <button type="button" onClick={() => { if (unlocked && template === initialDesign.id) window.print(); else window.location.href = `/candidates/resume-checkout?template=${template}`; }} className="mt-7 inline-flex cursor-pointer items-center gap-2 rounded-2xl bg-gradient-to-r from-black via-zinc-800 to-zinc-600 px-6 py-4 font-semibold text-white"><Download size={18} /> {unlocked && template === initialDesign.id ? "Download Purchased CV" : "Unlock & Download CV"}</button><p className="mt-3 text-xs text-zinc-400">{unlocked && template === initialDesign.id ? "This template is unlocked for your account." : "Secure payment is required before the PDF download is unlocked."}</p>
    </section>
    <section className="cv-builder-print-stage overflow-auto rounded-[2rem] bg-zinc-200 p-4 shadow-inner print:overflow-visible print:rounded-none print:bg-white print:p-0">
      <div className="sticky left-0 top-0 z-50 mb-4 flex flex-wrap items-center gap-2 rounded-2xl border border-zinc-200 bg-white/95 p-3 shadow-lg backdrop-blur print:hidden"><button type="button" onClick={() => setDirectEditing((value) => !value)} className={`rounded-xl px-4 py-2 text-sm font-semibold ${directEditing ? "bg-zinc-950 text-white" : "border border-zinc-300 bg-white"}`}>{directEditing ? "Direct editing ON" : "Enable direct editing"}</button><button type="button" onClick={removeSelectedSection} className="inline-flex items-center gap-2 rounded-xl border border-red-200 bg-red-50 px-4 py-2 text-sm font-semibold text-red-700"><Scissors size={16}/> Remove selected section</button><p className="basis-full text-xs text-zinc-500">Click any name, heading, or text directly on the CV to edit it. Place the cursor inside a section and select “Remove selected section” to delete it.</p></div>
      <div className="cv-print-page mx-auto h-[1120px] w-full max-w-[794px] overflow-hidden bg-white shadow-2xl print:max-w-none print:shadow-none"><div className="origin-top-left scale-[3.2]">
        <RichResumeDocument template={design} data={data} photoUrl={photoUrl} accent={accent} fontFamily={fontFamily} fontScale={fontScale} totalPages={pageCount} editable={directEditing} customHtml={savedHtml} />
      </div></div>
      {Array.from({ length: pageCount - 1 }, (_, index) => <div key={index} className="cv-print-page break-before-page mx-auto mt-6 h-[1120px] w-full max-w-[794px] overflow-hidden bg-white shadow-2xl print:mt-0 print:max-w-none print:shadow-none"><div className="origin-top-left scale-[3.2]"><RichResumeDocument template={design} data={data} photoUrl={photoUrl} page={index + 2} totalPages={pageCount} accent={accent} fontFamily={fontFamily} fontScale={fontScale} editable={directEditing} /></div></div>)}
    </section>
  </div>;
}

function Field({ label, value, onChange }: { label: string; value: string; onChange: (value: string) => void }) { return <label className="block text-sm font-medium text-zinc-700">{label}<input value={value} onChange={(event) => onChange(event.target.value)} className="mt-2 h-11 w-full rounded-xl border border-zinc-200 bg-zinc-50 px-4 outline-none focus:border-zinc-500" /></label>; }
function Area({ label, value, onChange }: { label: string; value: string; onChange: (value: string) => void }) { return <label className="block text-sm font-medium text-zinc-700">{label}<textarea value={value} onChange={(event) => onChange(event.target.value)} rows={4} className="mt-2 w-full rounded-xl border border-zinc-200 bg-zinc-50 p-4 outline-none focus:border-zinc-500" /></label>; }
function Section({ title, children }: { title: string; children: React.ReactNode }) { return <section className="mb-9"><h2 className="mb-4 border-b border-zinc-300 pb-2 text-sm font-bold uppercase tracking-[.18em]">{title}</h2><div className="text-sm leading-7 text-zinc-700">{children}</div></section>; }
function Multiline({ value }: { value: string }) { return <>{value.split("\n").map((line, index) => <p key={`${line}-${index}`} className={index === 0 ? "font-semibold text-zinc-900" : ""}>{line || <br />}</p>)}</>; }
