import type { ResumeTemplate } from "@/lib/resume-templates";

export type ResumeContent = { name: string; title: string; email: string; phone: string; location: string; summary: string; skills: string; experience: string; education: string; projects: string; certifications: string; languages: string };

export default function ResumeDocument({ template, data, photoUrl, page = 1, totalPages = 1, accent = template.accent, fontFamily }: { template: ResumeTemplate; data: ResumeContent; photoUrl?: string | null; page?: number; totalPages?: number; accent?: string; fontFamily?: string }) {
  const sidebar = ["sidebar", "split", "geometric"].includes(template.layout); const centered = [3, 7, 9].includes(template.headerStyle);
  if (page > 1) return <article className="relative min-h-[1120px] overflow-hidden bg-white p-10 text-zinc-900 sm:p-14" style={{ fontFamily }}><Decoration template={template} accent={accent} /><div className="relative mb-10 flex items-end justify-between border-b-4 pb-5" style={{ borderColor: accent }}><div><p className="text-3xl font-bold">{data.name}</p><p className="mt-1 text-sm text-zinc-500">Career Portfolio | Page {page} of {totalPages}</p></div><span className="text-3xl" style={{ color: accent }}>+</span></div><div className="relative grid gap-10 sm:grid-cols-[1.25fr_.75fr]"><div><Section title="Projects & Achievements" accent={accent}><Lines value={data.projects} /></Section><Section title="Additional Experience" accent={accent}><Lines value={data.experience} /></Section></div><aside><Section title="Certifications" accent={accent}><Lines value={data.certifications} /></Section><Section title="Languages" accent={accent}><Lines value={data.languages} /></Section><Section title="Education" accent={accent}><Lines value={data.education} /></Section></aside></div></article>;
  return <article className="relative min-h-[1120px] overflow-hidden bg-white text-zinc-900" style={{ fontFamily, borderTop: template.layout === "minimal" ? `12px solid ${accent}` : undefined }}><Decoration template={template} accent={accent} /><header className={`relative p-10 sm:p-14 ${centered ? "text-center" : ""} ${template.headerStyle === 5 ? "py-20 sm:py-24" : ""}`} style={template.dark || [0, 5, 8].includes(template.headerStyle) ? { background: accent, color: "white" } : { background: template.soft, borderBottom: `4px solid ${accent}` }}><div className={`flex gap-6 ${centered ? "flex-col items-center" : "items-center"}`}>{photoUrl && template.supportsPhoto && <img src={photoUrl} alt="Candidate" className={`${template.headerStyle === 6 ? "rounded-2xl" : "rounded-full"} h-28 w-28 shrink-0 border-4 border-white/70 object-cover shadow-xl`} />}<div><h1 className={`${template.headerStyle === 5 ? "text-6xl" : "text-4xl"} font-bold tracking-tight`}>{data.name}</h1><p className="mt-2 text-lg opacity-75">{data.title}</p><p className="mt-5 text-sm opacity-65">{data.email} | {data.phone} | {data.location}</p></div></div></header><div className={`relative grid gap-10 p-10 sm:p-14 ${sidebar ? "sm:grid-cols-[1fr_2.1fr]" : ""} ${template.layout === "timeline" ? "border-l-[6px]" : ""}`} style={template.layout === "timeline" ? { borderColor: accent } : undefined}>{sidebar && <aside className={template.layout === "split" ? "-mt-28 rounded-t-3xl p-7 text-white" : ""} style={template.layout === "split" ? { background: accent } : undefined}><Section title="Skills" accent={accent}><div className="flex flex-wrap gap-2">{data.skills.split(",").map((skill) => <span key={skill} className="rounded-full px-3 py-1.5 text-xs" style={{ background: template.layout === "split" ? "rgba(255,255,255,.15)" : template.soft }}>{skill.trim()}</span>)}</div></Section><Section title="Education" accent={accent}><Lines value={data.education} /></Section></aside>}<main><Section title="Profile" accent={accent}>{data.summary}</Section>{!sidebar && <Section title="Core Skills" accent={accent}>{data.skills}</Section>}<Section title="Experience" accent={accent}><Lines value={data.experience} /></Section>{!sidebar && <Section title="Education" accent={accent}><Lines value={data.education} /></Section>}</main></div></article>;
}
function Decoration({ template, accent }: { template: ResumeTemplate; accent: string }) { return <>{template.decorationStyle === 1 && <span className="absolute -right-20 -top-20 h-64 w-64 rotate-45" style={{ background: accent }} />}{template.decorationStyle === 2 && <span className="absolute inset-y-0 left-0 w-4" style={{ background: accent }} />}{template.decorationStyle === 3 && <span className="absolute right-12 top-52 h-20 w-20 rounded-full opacity-20" style={{ background: accent }} />}</>; }
function Section({ title, accent, children }: { title: string; accent: string; children: React.ReactNode }) { return <section className="mb-9"><h2 className="mb-4 border-b pb-2 text-sm font-bold uppercase tracking-[.18em]" style={{ borderColor: accent, color: accent }}>{title}</h2><div className="text-sm leading-7">{children}</div></section>; }
function Lines({ value }: { value: string }) { return <>{value.split("\n").map((line, index) => <p key={`${line}-${index}`} className={index === 0 ? "font-semibold" : ""}>{line || <br />}</p>)}</>; }




