"use client";

import Link from "next/link";
import { useMemo, useState } from "react";
import { ArrowRight, Crown, Search } from "lucide-react";
import { resumeTemplates, type ResumeTemplate } from "@/lib/resume-templates";
import RichResumeDocument from "@/components/candidate/RichResumeDocument";
import type { ResumeContent } from "@/components/candidate/ResumeDocument";

export default function ResumeTemplateCatalog({ compact = false, initialType = "All", ownedTemplateIds = [] }: { compact?: boolean; initialType?: string; ownedTemplateIds?: string[] }) {
  const [query, setQuery] = useState(""); const [family, setFamily] = useState("All"); const [type, setType] = useState(initialType); const [limit, setLimit] = useState(20);
  const families = ["All", ...new Set(resumeTemplates.map((item) => item.family))];
  const owned = useMemo(() => new Set(ownedTemplateIds), [ownedTemplateIds]);
  const filtered = useMemo(() => resumeTemplates.filter((item) => (family === "All" || item.family === family) && (type === "All" || (type === "Photo" ? item.supportsPhoto : type === "Multi-Page" ? item.multiPage : owned.has(item.id))) && `${item.name} ${item.audience} ${item.style}`.toLowerCase().includes(query.toLowerCase())), [family, type, query, owned]);
  const featured = [resumeTemplates[0], resumeTemplates[56], resumeTemplates[112], resumeTemplates[278], resumeTemplates[444]];
  const photo = resumeTemplates.filter((item) => item.supportsPhoto).slice(0, 5); const multi = resumeTemplates.filter((item) => item.multiPage).slice(0, 5);
  const ownedItems = resumeTemplates.filter((item) => owned.has(item.id)).slice(0, 5);
  if (compact) return <section className="mt-10">{ownedItems.length > 0 && <Shelf eyebrow="Owned CVs" title="Your purchased templates, ready to edit again." items={ownedItems} href="/candidates/resume-templates?type=owned" />}<Shelf eyebrow="Featured Premium Templates" title="Distinct compositions, built for real careers." items={featured} action /><Shelf eyebrow="CV With Photo" title="Personal, visual and professionally balanced." items={photo} href="/candidates/resume-templates?type=photo" /><Shelf eyebrow="Multi-Page CV" title="Room for experience, projects and credentials." items={multi} href="/candidates/resume-templates?type=multi" /></section>;
  const visible = filtered.slice(0, limit);
  return <section className="mt-10"><div className="flex flex-col justify-between gap-5 lg:flex-row lg:items-end"><div><p className="text-xs font-bold uppercase tracking-[.18em] text-zinc-400">500 Premium Compositions</p><h2 className="mt-2 text-3xl font-semibold">Filter by career and CV format.</h2></div><label className="flex h-12 items-center gap-3 rounded-2xl border border-zinc-200 bg-white px-4 shadow-sm"><Search size={17} className="text-zinc-400" /><input value={query} onChange={(event) => { setQuery(event.target.value); setLimit(20); }} placeholder="Search templates" className="w-56 bg-transparent text-sm outline-none" /></label></div>
    <div className="mt-6 flex gap-2 overflow-x-auto pb-2">{["All", "Owned CVs", "Photo", "Multi-Page"].map((item) => <button key={item} onClick={() => { setType(item); setLimit(20); }} className={`shrink-0 rounded-full px-4 py-2 text-xs font-semibold ${type === item ? "bg-zinc-950 text-white" : "border border-zinc-200 bg-white text-zinc-600"}`}>{item}{item === "Owned CVs" ? ` (${owned.size})` : ""}</button>)}</div>
    <div className="mt-3 flex gap-2 overflow-x-auto pb-2">{families.map((item) => <button key={item} onClick={() => { setFamily(item); setLimit(20); }} className={`shrink-0 rounded-full px-4 py-2 text-xs font-semibold ${family === item ? "bg-zinc-700 text-white" : "border border-zinc-200 bg-white text-zinc-600"}`}>{item}</button>)}</div>{type === "Owned CVs" && !filtered.length ? <div className="mt-6 rounded-2xl border border-dashed border-zinc-300 bg-white p-10 text-center text-sm text-zinc-500">Your purchased CV templates will appear here.</div> : <><p className="mt-5 text-sm text-zinc-500">Showing {Math.min(limit, filtered.length)} of {filtered.length} templates</p><TemplateGrid items={visible} /></>}
    {visible.length < filtered.length && <div className="mt-8 text-center"><button onClick={() => setLimit((value) => value + 20)} className="rounded-2xl bg-zinc-950 px-6 py-3 text-sm font-semibold text-white">Load 20 More</button></div>}
  </section>;
}

function Shelf({ eyebrow, title, items, href = "/candidates/resume-templates", action = false }: { eyebrow: string; title: string; items: ResumeTemplate[]; href?: string; action?: boolean }) { return <section className="mb-14"><div className="flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div><p className="text-xs font-bold uppercase tracking-[.18em] text-zinc-400">{eyebrow}</p><h2 className="mt-2 text-3xl font-semibold">{title}</h2></div><Link href={href} className="inline-flex items-center gap-2 text-sm font-semibold">{action ? "Show All Templates" : "Explore Section"} <ArrowRight size={16} /></Link></div><TemplateGrid items={items} compact /></section>; }
function TemplateGrid({ items, compact = false }: { items: ResumeTemplate[]; compact?: boolean }) { return <div className={`mt-6 grid gap-4 sm:grid-cols-2 lg:grid-cols-3 ${compact ? "xl:grid-cols-5" : "xl:grid-cols-4"}`}>{items.map((template) => <Link href={`/candidates/resume-builder?template=${template.id}`} key={template.id} className="group overflow-hidden rounded-[1.5rem] border border-zinc-200 bg-white shadow-sm transition hover:-translate-y-1 hover:shadow-xl"><ResumeMiniPreview template={template} /><div className="p-4"><div className="flex items-center justify-between gap-3"><div className="flex items-center gap-2 text-[10px] font-bold uppercase tracking-[.14em] text-amber-700"><Crown size={13} /> Premium</div><span className="rounded-full bg-zinc-950 px-2.5 py-1 text-[10px] font-bold text-white">₹{template.price}</span></div><h3 className="mt-2 text-sm font-semibold">{template.name}</h3><p className="mt-1 text-[11px] text-zinc-500">{template.supportsPhoto ? "Photo" : "No photo"} | {template.multiPage ? "Multi-page" : "One page"}</p><p className="mt-3 text-xs font-semibold">Preview & edit →</p></div></Link>)}</div>; }

const catalogResumeData: ResumeContent = { name: "Aslam Ansari", title: "Senior Product Professional", email: "tribute@email.com", phone: "+91 98765 43210", location: "Mumbai, India", summary: "Impact-driven professional building teams, products and measurable outcomes.", skills: "Strategy, Leadership, Analytics, Product Management", experience: "Senior Product Manager - JobiVerse\nBuilt products and teams delivering measurable growth.", education: "MBA - University of Mumbai", projects: "Talent Intelligence Platform\nCreated scalable career and hiring experiences.", certifications: "Product Leadership Certification", languages: "English - Professional\nHindi - Native" };

function ResumeMiniPreview({ template }: { template: ResumeTemplate }) {
  const data = { ...catalogResumeData, name: template.headerStyle % 2 === 0 ? "Aslam Ansari" : "Shama Ansari" };
  return <div className="relative h-72 overflow-hidden p-4" style={{ backgroundColor: template.soft }}>
    {template.multiPage && <div className="absolute left-[24%] top-8 h-[238px] w-[168px] rotate-3 overflow-hidden bg-white shadow-xl"><div className="origin-top-left scale-[.68]"><RichResumeDocument template={template} data={data} page={2} totalPages={2}/></div></div>}
    <div className={`relative z-10 mx-auto h-[350px] w-[248px] origin-top scale-[.68] overflow-hidden bg-white shadow-2xl transition ${template.multiPage ? "-translate-x-3 -rotate-1" : ""} group-hover:scale-[.71]`}><RichResumeDocument template={template} data={data} totalPages={template.multiPage ? 2 : 1}/></div>
    <span className="absolute right-3 top-3 z-20 rounded-full bg-black px-2.5 py-1 text-[8px] font-bold uppercase text-white">{template.multiPage ? "2 Pages" : "Preview"}</span>
  </div>;
}

function UniqueMiniContent({ template: t }: { template: ResumeTemplate }) {
  const name = t.headerStyle % 2 === 0 ? "Aslam Ansari" : "Shama Ansari";
  const common = <><b>Senior Product Manager</b><p className="opacity-60">JobiVerse | 2022-Present</p><p>Built products and teams delivering measurable growth.</p></>;
  if (t.bodyStyle === 0) return <div><div className="bg-zinc-950 px-6 py-7 text-white"><p className="text-2xl font-bold">{name}</p><p className="mt-1 text-[8px] text-zinc-400">BUSINESS & PRODUCT LEADER</p><div className="mt-5 grid grid-cols-3 gap-3 text-center"><Metric value="42%" label="Growth"/><Metric value="18" label="Launches"/><Metric value="9Y" label="Experience"/></div></div><div className="grid grid-cols-[.7fr_1.3fr] gap-5 p-6"><div><Mini title="EXPERTISE" accent={t.accent}>Strategy<br/>P&L Ownership<br/>Leadership<br/>Transformation</Mini><Mini title="EDUCATION" accent={t.accent}>MBA | Mumbai<br/>B.Tech | Pune</Mini></div><div><Mini title="EXECUTIVE PROFILE" accent={t.accent}>Commercial leader translating strategy into sustainable business results.</Mini><Mini title="CAREER IMPACT" accent={t.accent}>{common}</Mini></div></div></div>;
  if (t.bodyStyle === 1) return <div className="grid h-full grid-cols-[.72fr_1.28fr]"><aside className="p-5 text-white" style={{background:t.accent}}><div className="mx-auto grid h-20 w-20 place-items-center rounded-full border-4 border-white/70 bg-white/20 text-[8px]">PHOTO</div><p className="mt-4 text-center text-lg font-bold">{name}</p><Mini title="CONTACT" accent="#fff">Mumbai<br/>+91 98765 43210<br/>tribute@email.com</Mini><Mini title="SKILLS" accent="#fff">Product Strategy<br/>User Research<br/>Analytics</Mini></aside><main className="p-6"><p className="text-xs font-bold tracking-[.2em]" style={{color:t.accent}}>PRODUCT LEADER</p><Mini title="ABOUT ME" accent={t.accent}>Customer-focused leader with a record of building useful, scalable products.</Mini><Mini title="EXPERIENCE" accent={t.accent}>{common}<br/><br/><b>Product Manager</b><p>Growth Labs | 2020-2022</p></Mini><Mini title="EDUCATION" accent={t.accent}>MBA | University of Mumbai</Mini></main></div>;
  if (t.bodyStyle === 2) return <div className="p-8"><div className="flex items-end justify-between border-b-2 pb-5" style={{borderColor:t.accent}}><div><p className="text-3xl font-light">{name}</p><p className="text-[8px] tracking-[.24em]">PRODUCT DESIGNER</p></div><p className="text-right text-[6px]">Mumbai, India<br/>tribute@email.com</p></div><div className="mt-6 grid grid-cols-2 gap-6"><div><Mini title="PROFILE" accent={t.accent}>Minimalist designer creating intuitive experiences and clear visual systems.</Mini><Mini title="TOOLS" accent={t.accent}>Figma | Research | Prototyping | Design Systems</Mini></div><div><Mini title="SELECTED EXPERIENCE" accent={t.accent}>{common}</Mini><Mini title="AWARDS" accent={t.accent}>Design Excellence 2025<br/>Product Impact Award</Mini></div></div></div>;
  if (t.bodyStyle === 3) return <div><div className="relative h-32 p-6 text-white" style={{background:t.accent}}><div className="absolute right-6 top-6 grid h-20 w-20 place-items-center rounded-2xl bg-white/20 text-[8px]">PHOTO</div><p className="text-3xl font-black">{name}</p><p className="mt-2 text-[8px]">CREATIVE STRATEGIST</p></div><div className="grid grid-cols-3 gap-3 p-5"><Metric value="12" label="Brands"/><Metric value="28" label="Campaigns"/><Metric value="6" label="Awards"/></div><div className="grid grid-cols-2 gap-5 px-6"><Mini title="MY STORY" accent={t.accent}>I turn complex ideas into memorable brand experiences.</Mini><Mini title="CAPABILITIES" accent={t.accent}>Brand Direction<br/>Campaign Design<br/>Content Strategy</Mini><Mini title="FEATURED WORK" accent={t.accent}>{common}</Mini><Mini title="CLIENTS" accent={t.accent}>FinTech | Retail | SaaS | Culture</Mini></div></div>;
  if (t.bodyStyle === 4) return <div className="p-7" style={{fontFamily:"Georgia,serif"}}><div className="border-y-4 py-5 text-center" style={{borderColor:t.accent}}><p className="text-3xl">{name}</p><p className="mt-1 text-[8px] italic">Researcher | Educator | Author</p></div><div className="mt-6 columns-2 gap-6 text-[7px] leading-relaxed"><h3 className="text-sm">Academic Profile</h3><p>Interdisciplinary researcher focused on technology, organizations and human potential.</p><h3 className="mt-4 text-sm">Appointments</h3>{common}<h3 className="mt-4 text-sm">Selected Publications</h3><p>Designing Human Systems, 2025</p><p>Future of Work, 2024</p><h3 className="mt-4 text-sm">Education</h3><p>PhD | University of Mumbai</p></div></div>;
  if (t.bodyStyle === 5) return <div className="p-6"><p className="text-2xl font-bold">{name}</p><p className="text-[8px]" style={{color:t.accent}}>OPERATIONS TRANSFORMATION</p><div className="mt-7 border-l-4 pl-5" style={{borderColor:t.accent}}><Timeline year="2025" title="Director of Operations"/><Timeline year="2022" title="Senior Operations Manager"/><Timeline year="2019" title="Process Excellence Lead"/><Timeline year="2017" title="Management Trainee"/></div><div className="mt-5 grid grid-cols-3 gap-2"><Metric value="31%" label="Faster"/><Metric value="INR 4Cr" label="Saved"/><Metric value="120" label="Team"/></div></div>;
  if (t.bodyStyle === 6) return <div className="grid h-full grid-cols-[.82fr_1.18fr]"><aside className="p-6 text-white" style={{background:t.accent}}><p className="text-2xl font-bold">{name}</p><p className="mt-2 text-[8px]">FULL STACK ENGINEER</p><Mini title="STACK" accent="#fff">TypeScript<br/>React / Next.js<br/>Node / PostgreSQL<br/>AWS / Docker</Mini><Mini title="CERTIFICATIONS" accent="#fff">AWS Solutions Architect<br/>Scrum Master</Mini></aside><main className="p-6"><Mini title="ENGINEERING PROFILE" accent={t.accent}>Product-minded engineer shipping reliable platforms at scale.</Mini><Mini title="EXPERIENCE" accent={t.accent}>{common}</Mini><Mini title="PROJECTS" accent={t.accent}><b>Talent Intelligence Platform</b><br/>Architected event-driven hiring workflows.<br/><br/><b>Analytics Engine</b><br/>Reduced reporting time by 70%.</Mini></main></div>;
  if (t.bodyStyle === 7) return <div className="p-7 text-center"><div className="mx-auto grid h-24 w-24 place-items-center rounded-full border-8 text-[8px]" style={{borderColor:t.soft,background:t.accent,color:"white"}}>PHOTO</div><p className="mt-4 text-2xl font-semibold">Dr. {name}</p><p className="text-[8px] tracking-[.16em]" style={{color:t.accent}}>HEALTHCARE PROFESSIONAL</p><p className="mx-auto mt-4 max-w-[190px] text-[7px] leading-relaxed">Patient-centered clinician combining evidence-based care with empathetic communication.</p><div className="mt-6 grid grid-cols-3 gap-3 text-left"><Mini title="SPECIALITY" accent={t.accent}>Internal Medicine<br/>Preventive Care</Mini><Mini title="EXPERIENCE" accent={t.accent}>Apollo Hospitals<br/>2021-Present</Mini><Mini title="CREDENTIALS" accent={t.accent}>MBBS | MD<br/>MMC Registered</Mini></div></div>;
  if (t.bodyStyle === 8) return <div className="p-5"><div className="flex justify-between border-b-4 pb-4" style={{borderColor:t.accent}}><div><p className="text-xl font-bold">{name}</p><p className="text-[7px]">FINANCE & RISK</p></div><p className="text-right text-[6px]">CA | CFA L2<br/>Mumbai</p></div><div className="mt-4 grid grid-cols-4 gap-2"><Metric value="INR 850Cr" label="Portfolio"/><Metric value="99.8%" label="Accuracy"/><Metric value="18%" label="ROI"/><Metric value="0" label="Findings"/></div><div className="mt-5 grid grid-cols-[1.4fr_.6fr] gap-5"><div><Mini title="PROFESSIONAL EXPERIENCE" accent={t.accent}>{common}<br/><br/><b>Risk Analyst</b><p>National Bank | 2019-2022</p></Mini></div><div><Mini title="CORE" accent={t.accent}>Financial Modelling<br/>Risk Controls<br/>Audit<br/>Valuation</Mini><Mini title="EDUCATION" accent={t.accent}>Chartered Accountant<br/>B.Com</Mini></div></div></div>;
  return <div className="relative p-6"><span className="absolute -right-12 -top-12 h-36 w-36 rotate-45" style={{background:t.accent}}/><div className="flex items-center gap-4"><div className="grid h-20 w-20 place-items-center rounded-2xl text-[8px] text-white" style={{background:t.accent}}>PHOTO</div><div><p className="text-2xl font-bold">{name}</p><p className="text-[8px]">BRAND & VISUAL DESIGNER</p></div></div><div className="mt-7 grid grid-cols-2 gap-3"><Portfolio title="Brand Systems"/><Portfolio title="Digital Products"/><Portfolio title="Campaign Direction"/><Portfolio title="Editorial Design"/></div><div className="mt-6 grid grid-cols-2 gap-5"><Mini title="PROFILE" accent={t.accent}>Visual storyteller creating brands with clarity and character.</Mini><Mini title="TOOLS" accent={t.accent}>Figma | Adobe CC | Motion | Strategy</Mini></div></div>;
}

function Metric({value,label}:{value:string;label:string}){return <div className="rounded bg-white/10 p-2"><p className="text-sm font-bold">{value}</p><p className="text-[6px] opacity-60">{label}</p></div>}
function Timeline({year,title}:{year:string;title:string}){return <div className="relative mb-5"><span className="absolute -left-[27px] top-0 h-3 w-3 rounded-full bg-zinc-900"/><p className="text-[7px] font-bold opacity-50">{year}</p><p className="text-[9px] font-bold">{title}</p><p className="text-[6px]">Improved delivery, quality and commercial outcomes.</p></div>}
function Portfolio({title}:{title:string}){return <div className="h-16 rounded-lg bg-zinc-100 p-3"><div className="h-6 rounded opacity-20 bg-zinc-700"/><p className="mt-2 text-[7px] font-bold">{title}</p></div>}
function Mini({ title, accent, children }: { title: string; accent: string; children: React.ReactNode }) { return <section className="mb-3 text-[5.5px] leading-[1.45]"><h4 className="mb-1 border-b pb-1 text-[6.5px] font-bold tracking-[.1em]" style={{ borderColor: accent, color: accent }}>{title}</h4>{children}</section>; }
