import type { ResumeTemplate } from "@/lib/resume-templates";
import type { ResumeContent } from "@/components/candidate/ResumeDocument";

type Props = { template: ResumeTemplate; data: ResumeContent; photoUrl?: string | null; page?: number; totalPages?: number; accent?: string; fontFamily?: string; fontScale?: number; editable?: boolean; customHtml?: string | null };

export default function RichResumeDocument({ template: t, data, photoUrl, page = 1, totalPages = 1, accent = t.accent, fontFamily, fontScale = 1, editable = false, customHtml }: Props) {
  const style = { fontFamily: fontFamily ?? (t.bodyStyle === 4 ? "Georgia,serif" : undefined), zoom: fontScale };
  if (page === 1 && customHtml) return <article contentEditable={editable} suppressContentEditableWarning className="relative h-[350px] w-[248px] overflow-hidden bg-white text-zinc-800 outline-none" style={style} dangerouslySetInnerHTML={{ __html: customHtml }} />;
  if (page > 1) return <article contentEditable={editable} suppressContentEditableWarning className="relative h-[350px] w-[248px] overflow-hidden bg-white p-6 text-zinc-800" style={style}><Decoration template={t} accent={accent} /><div className="relative border-b-2 pb-3" style={{ borderColor: accent }}><p className="text-xl font-bold">{data.name}</p><p className="text-[7px] text-zinc-500">Career Portfolio | Page {page} of {totalPages}</p></div><div className="relative mt-5 grid grid-cols-[1.25fr_.75fr] gap-5"><div><Mini title="PROJECTS & ACHIEVEMENTS" accent={accent}><Lines value={data.projects} /></Mini><Mini title="ADDITIONAL EXPERIENCE" accent={accent}><Lines value={data.experience} /></Mini></div><aside><Mini title="CERTIFICATIONS" accent={accent}><Lines value={data.certifications} /></Mini><Mini title="LANGUAGES" accent={accent}><Lines value={data.languages} /></Mini><Mini title="EDUCATION" accent={accent}><Lines value={data.education} /></Mini></aside></div></article>;
  const contact = <>{data.location}<br />{data.phone}<br />{data.email}</>;
  const experience = <Lines value={data.experience} />;
  let content: React.ReactNode;
  if (t.bodyStyle === 0) content = <div><div className="bg-zinc-950 px-6 py-7 text-white"><p className="text-2xl font-bold">{data.name}</p><p className="mt-1 text-[8px] text-zinc-400">{data.title.toUpperCase()}</p><div className="mt-5 grid grid-cols-3 gap-3 text-center"><Metric value="42%" label="Growth"/><Metric value="18" label="Launches"/><Metric value="9Y" label="Experience"/></div></div><div className="grid grid-cols-[.7fr_1.3fr] gap-5 p-6"><div><Mini title="EXPERTISE" accent={accent}>{data.skills}</Mini><Mini title="EDUCATION" accent={accent}><Lines value={data.education}/></Mini></div><div><Mini title="EXECUTIVE PROFILE" accent={accent}>{data.summary}</Mini><Mini title="CAREER IMPACT" accent={accent}>{experience}</Mini></div></div></div>;
  else if (t.bodyStyle === 1) content = <div className="grid h-full grid-cols-[.72fr_1.28fr]"><aside className="p-5 text-white" style={{background:accent}}><Photo photoUrl={photoUrl}/><p className="mt-4 text-center text-lg font-bold">{data.name}</p><Mini title="CONTACT" accent="#fff">{contact}</Mini><Mini title="SKILLS" accent="#fff">{data.skills}</Mini></aside><main className="p-6"><p className="text-xs font-bold tracking-[.2em]" style={{color:accent}}>{data.title.toUpperCase()}</p><Mini title="ABOUT ME" accent={accent}>{data.summary}</Mini><Mini title="EXPERIENCE" accent={accent}>{experience}</Mini><Mini title="EDUCATION" accent={accent}><Lines value={data.education}/></Mini></main></div>;
  else if (t.bodyStyle === 2) content = <div className="p-8"><div className="flex items-end justify-between border-b-2 pb-5" style={{borderColor:accent}}><div><p className="text-3xl font-light">{data.name}</p><p className="text-[8px] tracking-[.24em]">{data.title.toUpperCase()}</p></div><p className="text-right text-[6px]">{contact}</p></div><div className="mt-6 grid grid-cols-2 gap-6"><div><Mini title="PROFILE" accent={accent}>{data.summary}</Mini><Mini title="TOOLS & SKILLS" accent={accent}>{data.skills}</Mini></div><div><Mini title="SELECTED EXPERIENCE" accent={accent}>{experience}</Mini><Mini title="EDUCATION" accent={accent}><Lines value={data.education}/></Mini></div></div></div>;
  else if (t.bodyStyle === 3) content = <div><div className="relative h-32 p-6 text-white" style={{background:accent}}><div className="absolute right-6 top-6"><Photo photoUrl={photoUrl} square/></div><p className="max-w-[145px] text-3xl font-black leading-none">{data.name}</p><p className="mt-2 text-[8px]">{data.title.toUpperCase()}</p></div><div className="grid grid-cols-3 gap-3 p-5"><Metric value="12" label="Brands"/><Metric value="28" label="Projects"/><Metric value="6" label="Awards"/></div><div className="grid grid-cols-2 gap-5 px-6"><Mini title="MY STORY" accent={accent}>{data.summary}</Mini><Mini title="CAPABILITIES" accent={accent}>{data.skills}</Mini><Mini title="FEATURED WORK" accent={accent}><Lines value={data.projects}/></Mini><Mini title="EXPERIENCE" accent={accent}>{experience}</Mini></div></div>;
  else if (t.bodyStyle === 4) content = <div className="p-6"><div className="border-y-4 py-4 text-center" style={{borderColor:accent}}><p className="text-3xl">{data.name}</p><p className="mt-1 text-[8px] italic">{data.title}</p></div><div className="mt-4 columns-2 gap-6 text-[7px] leading-relaxed"><h3 className="text-sm">Academic Profile</h3><p>{data.summary}</p><h3 className="mt-3 text-sm">Appointments</h3>{experience}<h3 className="mt-3 text-sm">Selected Projects</h3><Lines value={data.projects}/>{totalPages===1&&<><h3 className="mt-3 text-sm">Education</h3><Lines value={data.education}/></>}</div></div>;
  else if (t.bodyStyle === 5) content = <div className="p-6"><p className="text-2xl font-bold">{data.name}</p><p className="text-[8px]" style={{color:accent}}>{data.title.toUpperCase()}</p><div className="mt-7 border-l-4 pl-5" style={{borderColor:accent}}><Timeline year="2025" title="Current Role" text={data.experience}/><Timeline year="2022" title="Career Progression" text={data.projects}/><Timeline year="2019" title="Education" text={data.education}/></div><div className="mt-5 grid grid-cols-3 gap-2"><Metric value="31%" label="Faster"/><Metric value="4Cr" label="Impact"/><Metric value="120" label="Team"/></div></div>;
  else if (t.bodyStyle === 6) content = <div className="grid h-full grid-cols-[.82fr_1.18fr]"><aside className="p-6 text-white" style={{background:accent}}><p className="text-2xl font-bold">{data.name}</p><p className="mt-2 text-[8px]">{data.title.toUpperCase()}</p><Mini title="STACK & SKILLS" accent="#fff">{data.skills}</Mini><Mini title="CERTIFICATIONS" accent="#fff"><Lines value={data.certifications}/></Mini></aside><main className="p-6"><Mini title="PROFESSIONAL PROFILE" accent={accent}>{data.summary}</Mini><Mini title="EXPERIENCE" accent={accent}>{experience}</Mini><Mini title="PROJECTS" accent={accent}><Lines value={data.projects}/></Mini></main></div>;
  else if (t.bodyStyle === 7) content = <div className="p-7 text-center"><div className="mx-auto"><Photo photoUrl={photoUrl} large/></div><p className="mt-4 text-2xl font-semibold">{data.name}</p><p className="text-[8px] tracking-[.16em]" style={{color:accent}}>{data.title.toUpperCase()}</p><p className="mx-auto mt-4 max-w-[190px] text-[7px] leading-relaxed">{data.summary}</p><div className="mt-6 grid grid-cols-3 gap-3 text-left"><Mini title="SKILLS" accent={accent}>{data.skills}</Mini><Mini title="EXPERIENCE" accent={accent}>{experience}</Mini><Mini title="CREDENTIALS" accent={accent}><Lines value={data.certifications}/></Mini></div></div>;
  else if (t.bodyStyle === 8) content = <div className="p-5"><div className="flex justify-between border-b-4 pb-4" style={{borderColor:accent}}><div><p className="text-xl font-bold">{data.name}</p><p className="text-[7px]">{data.title.toUpperCase()}</p></div><p className="text-right text-[6px]">{data.location}<br/>{data.phone}</p></div><div className="mt-4 grid grid-cols-4 gap-2"><Metric value="850Cr" label="Portfolio"/><Metric value="99.8%" label="Accuracy"/><Metric value="18%" label="ROI"/><Metric value="0" label="Findings"/></div><div className="mt-5 grid grid-cols-[1.4fr_.6fr] gap-5"><div><Mini title="PROFESSIONAL EXPERIENCE" accent={accent}>{experience}</Mini></div><div><Mini title="CORE" accent={accent}>{data.skills}</Mini><Mini title="EDUCATION" accent={accent}><Lines value={data.education}/></Mini></div></div></div>;
  else content = <div className="relative p-6"><span className="absolute -right-12 -top-12 h-36 w-36 rotate-45" style={{background:accent}}/><div className="flex items-center gap-4"><Photo photoUrl={photoUrl} square/><div><p className="text-2xl font-bold">{data.name}</p><p className="text-[8px]">{data.title.toUpperCase()}</p></div></div><div className="mt-7 grid grid-cols-2 gap-3"><Portfolio title="Brand Systems"/><Portfolio title="Digital Products"/><Portfolio title="Campaign Direction"/><Portfolio title="Editorial Design"/></div><div className="mt-6 grid grid-cols-2 gap-5"><Mini title="PROFILE" accent={accent}>{data.summary}</Mini><Mini title="TOOLS" accent={accent}>{data.skills}</Mini></div></div>;
  return <article contentEditable={editable} suppressContentEditableWarning className="relative h-[350px] w-[248px] overflow-hidden bg-white text-zinc-800" style={{...style,borderTop:t.decorationStyle===0?`9px solid ${accent}`:undefined}}><Decoration template={t} accent={accent}/><div className="relative h-full">{content}</div></article>;
}

function Decoration({template:t,accent}:{template:ResumeTemplate;accent:string}){return <>{t.decorationStyle===1&&<span className="absolute -right-12 -top-12 h-28 w-28 rotate-45" style={{background:accent}}/>}{t.decorationStyle===2&&<span className="absolute inset-y-0 left-0 z-20 w-2" style={{background:accent}}/>}{t.decorationStyle===3&&<span className="absolute right-4 top-4 z-20 h-16 w-16 rounded-full opacity-20" style={{background:accent}}/>}</>}
function Photo({photoUrl,square=false,large=false}:{photoUrl?:string|null;square?:boolean;large?:boolean}){return photoUrl?<img src={photoUrl} alt="Candidate" className={`${large?"h-24 w-24 border-8":square?"h-20 w-20":"mx-auto h-20 w-20 border-4"} object-cover ${square?"rounded-2xl":"rounded-full"}`}/>:<div className={`${large?"h-24 w-24 border-8":square?"h-20 w-20":"mx-auto h-20 w-20 border-4"} grid place-items-center bg-zinc-200 text-[8px] text-zinc-500 ${square?"rounded-2xl":"rounded-full"}`}>PHOTO</div>}
function Mini({title,accent,children}:{title:string;accent:string;children:React.ReactNode}){return <section data-cv-section className="mb-3 text-[5.5px] leading-[1.45]"><h4 className="mb-1 border-b pb-1 text-[6.5px] font-bold tracking-[.1em]" style={{borderColor:accent,color:accent}}>{title}</h4>{children}</section>}
function Lines({value}:{value:string}){return <>{value.split("\n").map((line,index)=><p key={`${line}-${index}`} className={index===0?"font-bold":""}>{line||<br/>}</p>)}</>}
function Metric({value,label}:{value:string;label:string}){return <div className="rounded bg-white/10 p-2"><p className="text-sm font-bold">{value}</p><p className="text-[6px] opacity-60">{label}</p></div>}
function Timeline({year,title,text}:{year:string;title:string;text:string}){return <div className="relative mb-5"><span className="absolute -left-[27px] top-0 h-3 w-3 rounded-full bg-zinc-900"/><p className="text-[7px] font-bold opacity-50">{year}</p><p className="text-[9px] font-bold">{title}</p><p className="line-clamp-2 text-[6px]">{text}</p></div>}
function Portfolio({title}:{title:string}){return <div className="h-16 rounded-lg bg-zinc-100 p-3"><div className="h-6 rounded bg-zinc-700 opacity-20"/><p className="mt-2 text-[7px] font-bold">{title}</p></div>}
