"use server";

import { revalidatePath } from "next/cache";
import { z } from "zod";
import { requireRole } from "@/lib/auth/authorization";
import { adminSupabase } from "@/lib/supabase/admin";

const applicationSchema=z.object({fullName:z.string().trim().min(2).max(120),email:z.string().trim().email(),phone:z.string().trim().min(7).max(30),currentLocation:z.string().trim().min(2).max(150),totalExperience:z.coerce.number().min(0).max(60),relevantExperience:z.coerce.number().min(0).max(60),currentCompany:z.string().trim().max(150).optional(),currentCtc:z.string().trim().max(80).optional(),expectedCtc:z.string().trim().min(1).max(80),noticePeriod:z.string().trim().min(1).max(80),availability:z.string().trim().min(2).max(200),primarySkills:z.string().trim().min(2).max(1000),linkedin:z.union([z.literal(""),z.string().trim().url()]).optional(),whyFit:z.string().trim().min(30,"Explain your role fit in at least 30 characters.").max(2000),coverNote:z.string().trim().min(20,"Write at least 20 characters about your suitability.").max(1500),confirmation:z.literal("yes")});

export async function applyToRequirement(requirementId:string,formData:FormData){
  const input=applicationSchema.parse(Object.fromEntries(formData));const{supabase,user}=await requireRole(["candidate"]);const{data:profile}=await supabase.from("candidate_profiles").select("resume_path").eq("user_id",user.id).maybeSingle();const cv=formData.get("applicationCv");let resumePath=profile?.resume_path??null;let uploadedPath:string|null=null;
  if(cv instanceof File&&cv.size>0){if(cv.type!=="application/pdf")throw new Error("Please attach the CV as a PDF.");if(cv.size>5*1024*1024)throw new Error("CV size must be 5 MB or less.");uploadedPath=`${user.id}/application-${requirementId}-${crypto.randomUUID()}.pdf`;const{error:uploadError}=await supabase.storage.from("candidate-resumes").upload(uploadedPath,cv);if(uploadError)throw new Error(uploadError.message);resumePath=uploadedPath}if(!resumePath)throw new Error("Attach a CV or upload one in your professional profile before applying.");
  const{data:application,error}=await supabase.from("candidate_applications").insert({candidate_user_id:user.id,requirement_id:requirementId,cover_note:input.coverNote,why_fit:input.whyFit,applicant_name:input.fullName,applicant_email:input.email,applicant_phone:input.phone,current_location:input.currentLocation,total_experience:String(input.totalExperience),relevant_experience_years:input.relevantExperience,current_company:input.currentCompany||null,current_ctc:input.currentCtc||null,expected_ctc:input.expectedCtc,notice_period:input.noticePeriod,interview_availability:input.availability,primary_skills:input.primarySkills,linkedin:input.linkedin||null,resume_path:resumePath}).select("id,requirements(job_title,company_id,companies(company_name))").single();if(error){if(uploadedPath)await supabase.storage.from("candidate-resumes").remove([uploadedPath]);if(error.code==="23505")throw new Error("You have already applied for this opportunity.");throw new Error(error.message)}
  const requirement=Array.isArray((application as any)?.requirements)?(application as any).requirements[0]:(application as any)?.requirements;const company=Array.isArray(requirement?.companies)?requirement.companies[0]:requirement?.companies;const{data:admins}=await adminSupabase.from("users").select("id").eq("role","admin").eq("is_active",true);if(admins?.length)await adminSupabase.from("notifications").insert(admins.map((admin)=>({user_id:admin.id,type:"external_application_new",title:"New external applicant",message:`${input.fullName} applied directly for ${requirement?.job_title||"a published role"}${company?.company_name?` at ${company.company_name}`:""}.`,href:"/admin/candidates?source=external",reference_id:application.id})));
  revalidatePath("/admin/candidates");revalidatePath("/candidates/jobs");revalidatePath(`/candidates/jobs/${requirementId}`);revalidatePath("/candidates/dashboard");revalidatePath("/employers/external-applicants");
}
