import type { Metadata } from "next";
import Link from "next/link";
import { notFound } from "next/navigation";
import { ArrowRight, BriefcaseBusiness, CheckCircle2, Search } from "lucide-react";

import { JOB_CITY_LANDINGS, JOB_ROLE_LANDINGS, getRoleLanding } from "@/lib/jobs/seo-landings";

type Props={params:Promise<{role:string}>};
export function generateStaticParams(){return JOB_ROLE_LANDINGS.map(item=>({role:item.slug}))}
export async function generateMetadata({params}:Props):Promise<Metadata>{const item=getRoleLanding((await params).role);if(!item)return{};return{title:`${item.name} Jobs in India | JobiVerse`,description:`${item.summary} Browse clearly sourced opportunities across India.`,alternates:{canonical:`/jobs/role/${item.slug}`}}}
export default async function RoleJobsLanding({params}:Props){const item=getRoleLanding((await params).role);if(!item)notFound();const browse=`/jobs?q=${encodeURIComponent(item.query)}&sector=${item.sector}`;const schema={"@context":"https://schema.org","@type":"CollectionPage",name:`${item.name} jobs in India`,description:item.summary,url:`https://www.jobiverse.in/jobs/role/${item.slug}`};return <main className="min-h-screen bg-[#f5f5f3] px-5 pb-24 pt-36 sm:px-8"><script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify(schema).replace(/</g,"\\u003c")}}/><div className="mx-auto max-w-6xl"><section className="grid gap-0 overflow-hidden rounded-[3rem] bg-white shadow-2xl lg:grid-cols-[1.15fr_.85fr]"><div className="p-9 sm:p-14"><p className="text-xs font-bold uppercase tracking-[.2em] text-violet-700">Career opportunity guide</p><h1 className="mt-5 text-5xl font-semibold tracking-[-.055em] sm:text-7xl">{item.name} jobs.</h1><p className="mt-6 text-lg leading-8 text-zinc-600">{item.summary}</p><Link href={browse} className="mt-8 inline-flex items-center gap-2 rounded-2xl bg-zinc-950 px-6 py-4 font-bold text-white">Search current roles<ArrowRight size={17}/></Link></div><div className="bg-gradient-to-br from-violet-800 to-zinc-950 p-9 text-white sm:p-12"><Search size={28}/><h2 className="mt-6 text-3xl font-bold">Search smarter</h2>{["Filter by city and work mode","Compare opportunity signals","Track applications in your workspace","Open the original licensed listing"].map(x=><p key={x} className="mt-5 flex gap-3 text-sm text-violet-100"><CheckCircle2 className="shrink-0" size={17}/>{x}</p>)}</div></section><section className="mt-12"><h2 className="text-3xl font-bold">Explore {item.name} roles by city</h2><div className="mt-5 grid gap-3 sm:grid-cols-2 lg:grid-cols-4">{JOB_CITY_LANDINGS.map(city=><Link key={city.slug} href={`${browse}&location=${encodeURIComponent(city.name)}`} className="rounded-2xl border border-zinc-200 bg-white p-5"><BriefcaseBusiness/><p className="mt-5 font-bold">{city.name}</p><p className="mt-2 text-sm text-zinc-500">View live roles</p></Link>)}</div></section></div></main>}

