begin;
create table if not exists public.platform_plans(id uuid primary key default gen_random_uuid(),slug text not null unique,audience text not null check(audience in ('candidate','employer')),name text not null,description text not null,price numeric(12,2) not null default 0,billing_interval text not null check(billing_interval in ('free','monthly','quarterly','annual','custom')),features jsonb not null default '[]',is_active boolean not null default true,sort_order integer not null default 0,created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table if not exists public.platform_subscriptions(id uuid primary key default gen_random_uuid(),user_id uuid not null references public.users(id) on delete cascade,plan_id uuid not null references public.platform_plans(id),status text not null default 'requested' check(status in ('requested','pending_payment','active','paused','cancelled','expired','rejected')),gateway_subscription_id text,starts_at timestamptz,ends_at timestamptz,cancelled_at timestamptz,admin_note text,created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create unique index if not exists one_open_subscription_per_plan on public.platform_subscriptions(user_id,plan_id) where status in ('requested','pending_payment','active','paused');
alter table public.platform_plans enable row level security;alter table public.platform_subscriptions enable row level security;
drop policy if exists "Active plans are public" on public.platform_plans;create policy "Active plans are public" on public.platform_plans for select to anon,authenticated using(is_active=true);
drop policy if exists "Users view subscriptions" on public.platform_subscriptions;create policy "Users view subscriptions" on public.platform_subscriptions for select to authenticated using(user_id=auth.uid());
drop policy if exists "Users request subscriptions" on public.platform_subscriptions;create policy "Users request subscriptions" on public.platform_subscriptions for insert to authenticated with check(user_id=auth.uid() and status='requested');
drop policy if exists "Users cancel requested subscriptions" on public.platform_subscriptions;create policy "Users cancel requested subscriptions" on public.platform_subscriptions for update to authenticated using(user_id=auth.uid() and status in ('requested','active')) with check(user_id=auth.uid() and status='cancelled');
insert into public.platform_plans(slug,audience,name,description,price,billing_interval,features,sort_order) values
('career-free','candidate','Career Free','Essential career access without charging candidates for opportunities.',0,'free','["Apply to public opportunities","Candidate profile","Application tracking","Resume upload"]',10),
('career-plus','candidate','Career Plus','Optional career acceleration tools and human support. Job access remains free.',299,'monthly','["Everything in Career Free","Monthly group career clinic","Priority service offers","Career progress insights"]',20),
('career-pro','candidate','Career Pro','Higher-touch support for active career transitions.',799,'monthly','["Everything in Career Plus","One personal consultation per month","Resume strategy review","Interview preparation credit"]',30),
('employer-starter','employer','Employer Starter','Create a company workspace and submit hiring requirements.',0,'free','["Company profile","Requirement submission","Candidate pipeline view","Standard support"]',10),
('employer-growth','employer','Employer Growth','Operational hiring support for growing teams.',2499,'monthly','["Everything in Starter","Priority requirement review","Hiring analytics","Consultation credit","Enhanced support"]',20),
('employer-enterprise','employer','Employer Enterprise','Custom hiring operations, recruitment programmes and reporting.',0,'custom','["Custom hiring programme","Dedicated relationship owner","Executive and volume hiring","Custom reporting and commercials"]',30)
on conflict(slug) do update set name=excluded.name,description=excluded.description,price=excluded.price,billing_interval=excluded.billing_interval,features=excluded.features,sort_order=excluded.sort_order;
commit;
