begin;
create table if not exists public.ai_feature_registry(id uuid primary key default gen_random_uuid(),feature_key text not null unique,name text not null,description text not null,audience text[] not null default '{}',status text not null default 'coming_soon' check(status in ('coming_soon','internal_testing','limited_beta','live','paused')),human_review_required boolean not null default true,uses_personal_data boolean not null default true,disclaimer text not null,model_provider text,model_name text,last_reviewed_at timestamptz,last_reviewed_by uuid references public.users(id),created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table if not exists public.ai_interaction_audit(id uuid primary key default gen_random_uuid(),user_id uuid references public.users(id) on delete set null,feature_key text not null,input_reference text,output_reference text,model_provider text,model_name text,status text not null check(status in ('started','completed','failed','blocked')),error_code text,created_at timestamptz not null default now());
alter table public.ai_feature_registry enable row level security;alter table public.ai_interaction_audit enable row level security;
create policy "Users view available AI registry" on public.ai_feature_registry for select to anon,authenticated using(status in ('coming_soon','limited_beta','live'));
create policy "Users view own AI audit" on public.ai_interaction_audit for select to authenticated using(user_id=auth.uid());
insert into public.ai_feature_registry(feature_key,name,description,audience,status,human_review_required,uses_personal_data,disclaimer) values
('resume_builder','AI Resume Builder','Draft and improve resume content with user-controlled editing.',array['candidate','student'],'coming_soon',false,true,'AI suggestions may be incomplete. Review every statement for truth and accuracy.'),
('resume_analyzer','AI Resume Analyzer','Estimate resume quality, clarity and role alignment.',array['candidate','student'],'coming_soon',false,true,'Scores are guidance only and do not represent an employer or ATS decision.'),
('ats_checker','ATS Compatibility Checker','Review structure and keywords for common parsing patterns.',array['candidate','student'],'coming_soon',false,true,'No tool can guarantee ATS acceptance, interviews or hiring outcomes.'),
('interview_intelligence','AI Interview Preparation','Practice interview responses with automated feedback.',array['candidate','student'],'coming_soon',false,true,'Automated feedback is developmental guidance, not a hiring assessment.'),
('smart_matching','Smart Candidate Matching','Assist recruiters with explainable candidate-role comparisons.',array['candidate','employer','recruiter'],'coming_soon',true,true,'AI must not make final hiring decisions. Human review and lawful, job-relevant criteria are required.'),
('career_coach','Career Coach AI','Provide structured career exploration and learning suggestions.',array['candidate','student'],'coming_soon',false,true,'Career suggestions are informational and cannot guarantee employment or income.')
on conflict(feature_key) do update set name=excluded.name,description=excluded.description,audience=excluded.audience,disclaimer=excluded.disclaimer;
commit;
