"use server";

import { revalidatePath } from "next/cache";
import { z } from "zod";
import { requireRole } from "@/lib/auth/authorization";
import { createRazorpayRefund, fetchRazorpayRefund } from "@/lib/payments/razorpay";

export async function processRefundRequest(formData:FormData){const id=z.string().uuid().parse(formData.get("requestId"));const action=z.enum(["approve","reject"]).parse(formData.get("action"));const note=z.string().trim().max(1000).parse(String(formData.get("adminNote")??""));const{supabase,user}=await requireRole(["admin"]);const{data:request,error:readError}=await supabase.from("marketplace_refund_requests").select("id,order_id,payment_attempt_id,amount,status,payment_attempts(gateway_payment_id)").eq("id",id).eq("status","requested").maybeSingle();if(readError||!request)throw new Error(readError?.message??"Refund request is no longer pending.");if(action==="reject"){const{error}=await supabase.from("marketplace_refund_requests").update({status:"rejected",admin_note:note||"Refund request did not meet the policy criteria.",processed_by:user.id,processed_at:new Date().toISOString()}).eq("id",id).eq("status","requested");if(error)throw new Error(error.message);refresh();return;}const relation=Array.isArray(request.payment_attempts)?request.payment_attempts[0]:request.payment_attempts;const paymentId=relation?.gateway_payment_id;if(!paymentId)throw new Error("Razorpay payment ID is missing.");const refund=await createRazorpayRefund(paymentId,Number(request.amount),`jvr_${request.id.replaceAll("-","").slice(0,28)}`,{refund_request_id:request.id,order_id:request.order_id});const status=refund.status==="processed"?"processed":refund.status==="failed"?"failed":"gateway_pending";const{error}=await supabase.from("marketplace_refund_requests").update({status,gateway_refund_id:refund.id,gateway_status:refund.status,admin_note:note||null,processed_by:user.id,processed_at:status==="processed"?new Date().toISOString():null}).eq("id",id);if(error)throw new Error(error.message);if(status==="processed"){await supabase.from("marketplace_orders").update({status:"refunded",payout_status:"held"}).eq("id",request.order_id);await supabase.from("payment_attempts").update({status:"refunded"}).eq("id",request.payment_attempt_id);}refresh();}
function refresh(){revalidatePath("/admin/refunds");revalidatePath("/admin/finance");revalidatePath("/marketplace/orders","layout");}

export async function syncRefundStatus(formData:FormData){const id=z.string().uuid().parse(formData.get("requestId"));const{supabase}=await requireRole(["admin"]);const{data:request}=await supabase.from("marketplace_refund_requests").select("id,order_id,payment_attempt_id,gateway_refund_id,status").eq("id",id).maybeSingle();if(!request?.gateway_refund_id)throw new Error("Gateway refund ID is missing.");if(!["gateway_pending","approved"].includes(request.status))throw new Error("This refund does not require synchronization.");const refund=await fetchRazorpayRefund(request.gateway_refund_id);const status=refund.status==="processed"?"processed":refund.status==="failed"?"failed":"gateway_pending";const{error}=await supabase.from("marketplace_refund_requests").update({status,gateway_status:refund.status,processed_at:status==="processed"?new Date().toISOString():null}).eq("id",id);if(error)throw new Error(error.message);if(status==="processed"){await supabase.from("marketplace_orders").update({status:"refunded",payout_status:"held"}).eq("id",request.order_id);await supabase.from("payment_attempts").update({status:"refunded"}).eq("id",request.payment_attempt_id);}refresh();}
