"use client";

import Link from "next/link";
import { useEffect, useState } from "react";
import { ArrowLeft, ExternalLink, GitCompareArrows, IndianRupee, ShieldCheck, Trash2 } from "lucide-react";
import { readComparedJobs, writeComparedJobs, type ComparedJob } from "@/components/jobs/JobCompareButton";

export default function CompareJobsPage() {
  const [jobs, setJobs] = useState<ComparedJob[]>([]);
  useEffect(() => {
    const frame = window.requestAnimationFrame(() => setJobs(readComparedJobs()));
    return () => window.cancelAnimationFrame(frame);
  }, []);
  const remove = (key: string) => { const next = jobs.filter((job) => job.key !== key); writeComparedJobs(next); setJobs(next); window.dispatchEvent(new CustomEvent("jobiverse:compare-change")); };
  return <main className="min-h-screen bg-[#f5f5f3] px-5 pb-24 pt-36 sm:px-8"><div className="mx-auto max-w-7xl">
    <Link href="/jobs" className="inline-flex items-center gap-2 text-sm font-semibold text-zinc-600"><ArrowLeft size={16}/>Back to jobs</Link>
    <section className="mt-7 rounded-[2.75rem] bg-[radial-gradient(circle_at_80%_20%,rgba(139,92,246,.35),transparent_24rem),linear-gradient(135deg,#09090b,#27272a)] p-8 text-white sm:p-12"><GitCompareArrows/><p className="mt-5 text-xs font-bold uppercase tracking-[.2em] text-violet-300">Decision workspace</p><h1 className="mt-3 text-4xl font-semibold sm:text-6xl">Compare opportunities clearly.</h1><p className="mt-4 max-w-3xl text-zinc-300">Review up to three roles side by side. Trust and salary signals are guidance—not a hiring guarantee or employer offer.</p></section>
    {jobs.length ? <section className="mt-7 overflow-x-auto rounded-[2rem] border border-zinc-200 bg-white p-4 sm:p-7"><div className={`grid min-w-[760px] gap-4 ${jobs.length === 1 ? "grid-cols-1" : jobs.length === 2 ? "grid-cols-2" : "grid-cols-3"}`}>{jobs.map((job) => <article key={job.key} className="rounded-3xl border border-zinc-200 p-6"><div className="flex justify-between gap-3"><span className="rounded-full bg-violet-50 px-3 py-1 text-[10px] font-bold uppercase text-violet-700">{job.source}</span><button onClick={() => remove(job.key)} className="cursor-pointer text-zinc-400 hover:text-red-600" aria-label={`Remove ${job.title}`}><Trash2 size={17}/></button></div><h2 className="mt-5 text-2xl font-bold">{job.title}</h2><p className="mt-2 text-sm font-semibold text-zinc-600">{job.company}</p><CompareRow label="Location" value={job.location}/><CompareRow label="Work mode" value={job.workMode}/><CompareRow label="Employment" value={job.employmentType}/><CompareRow label="Published salary" value={job.salary}/><div className="mt-5 rounded-2xl bg-emerald-50 p-4 text-emerald-800"><p className="flex items-center gap-2 text-xs font-bold uppercase"><ShieldCheck size={14}/>Trust signals</p><p className="mt-2 text-2xl font-bold">{job.trustScore}/100</p><p className="text-xs">{job.trustLabel}</p></div><div className="mt-3 rounded-2xl bg-amber-50 p-4 text-amber-900"><p className="flex items-center gap-1 text-xs font-bold uppercase"><IndianRupee size={14}/>Estimated market range</p><p className="mt-2 text-xl font-bold">₹{job.estimatedMin}–{job.estimatedMax} LPA</p><p className="mt-1 text-[11px] leading-5">Directional JobiVerse estimate; not an employer offer.</p></div>{job.external?<a href={job.href} target="_blank" rel="nofollow sponsored noreferrer" className="mt-5 inline-flex w-full items-center justify-center gap-2 rounded-xl bg-zinc-950 px-4 py-3 text-sm font-semibold text-white">Original listing <ExternalLink size={14}/></a>:<Link href={job.href} className="mt-5 inline-flex w-full items-center justify-center rounded-xl bg-zinc-950 px-4 py-3 text-sm font-semibold text-white">View full role</Link>}</article>)}</div></section>:<section className="mt-7 rounded-[2rem] border border-dashed border-zinc-300 bg-white p-14 text-center"><GitCompareArrows className="mx-auto text-zinc-400"/><h2 className="mt-4 text-2xl font-bold">No jobs selected</h2><p className="mt-2 text-zinc-500">Use Compare on any job card to add up to three opportunities.</p><Link href="/jobs" className="mt-6 inline-flex rounded-xl bg-zinc-950 px-6 py-3 font-semibold text-white">Explore jobs</Link></section>}
  </div></main>;
}

function CompareRow({label,value}:{label:string;value:string}){return <div className="mt-4 border-t border-zinc-100 pt-4"><p className="text-[10px] font-bold uppercase tracking-wider text-zinc-400">{label}</p><p className="mt-1 text-sm font-semibold">{value||"Not specified"}</p></div>}
