"use server";
import { revalidatePath } from "next/cache";
import { z } from "zod";
import { requireRole } from "@/lib/auth/authorization";
import { adminSupabase } from "@/lib/supabase/admin";

const status=z.enum(["new","contacted","discovery_scheduled","scoping","proposal_sent","accepted","in_development","delivered","closed"]);
async function context(id:string){const{user}=await requireRole(["admin"]);const{data,error}=await adminSupabase.from("custom_portal_requests").select("id,requester_user_id,reference,organisation_name,status").eq("id",id).single();if(error)throw new Error(error.message);return{user,request:data}}
async function timeline(id:string,userId:string,type:string,title:string,message:string,visible=true){await adminSupabase.from("custom_portal_updates").insert({request_id:id,actor_user_id:userId,update_type:type,title,message:message||null,visible_to_employer:visible})}
async function notify(request:any,title:string,message:string){if(request.requester_user_id)await adminSupabase.from("notifications").insert({user_id:request.requester_user_id,type:"custom_portal_update",title,message,href:`/employers/custom-portal/requests/${request.id}`,reference_id:request.id})}
export async function saveDiscovery(formData:FormData){const p=z.object({id:z.string().uuid(),scheduled:z.string().min(1),meetingUrl:z.string().trim().max(500),notes:z.string().trim().max(5000)}).parse({id:formData.get("id"),scheduled:formData.get("scheduled"),meetingUrl:formData.get("meetingUrl")??"",notes:formData.get("notes")??""});const{user,request}=await context(p.id);const at=new Date(p.scheduled).toISOString();await adminSupabase.from("custom_portal_requests").update({status:"discovery_scheduled",discovery_scheduled_at:at,discovery_meeting_url:p.meetingUrl||null,discovery_notes:p.notes||null,updated_at:new Date().toISOString()}).eq("id",p.id);await timeline(p.id,user.id,"discovery","Discovery scheduled",`Discovery is scheduled for ${new Date(at).toLocaleString("en-IN")}.`);await notify(request,"Custom portal discovery scheduled",`Your discovery call is scheduled for ${new Date(at).toLocaleString("en-IN")}.`);refresh(p.id)}
export async function saveProposal(formData:FormData){const p=z.object({id:z.string().uuid(),proposalNumber:z.string().trim().min(2).max(80),scope:z.string().trim().min(20).max(10000),deliverables:z.string().trim().min(2).max(10000),excluded:z.string().trim().max(5000),setup:z.coerce.number().nonnegative(),annual:z.coerce.number().nonnegative(),taxNote:z.string().trim().max(500),start:z.string(),delivery:z.string()}).parse({id:formData.get("id"),proposalNumber:formData.get("proposalNumber"),scope:formData.get("scope"),deliverables:formData.get("deliverables"),excluded:formData.get("excluded")??"",setup:formData.get("setup"),annual:formData.get("annual"),taxNote:formData.get("taxNote")??"",start:formData.get("start")??"",delivery:formData.get("delivery")??""});const{user,request}=await context(p.id);const items=p.deliverables.split(/\r?\n/).map(x=>x.trim()).filter(Boolean);const now=new Date().toISOString();await adminSupabase.from("custom_portal_requests").update({status:"proposal_sent",proposal_number:p.proposalNumber,scope_summary:p.scope,scope_deliverables:items,excluded_scope:p.excluded||null,setup_amount:p.setup,annual_amount:p.annual,tax_note:p.taxNote||null,estimated_start_date:p.start||null,estimated_delivery_date:p.delivery||null,proposal_sent_at:now,updated_at:now}).eq("id",p.id);await timeline(p.id,user.id,"proposal","Proposal sent",`${p.proposalNumber} · Setup ₹${p.setup.toLocaleString("en-IN")} · Annual ₹${p.annual.toLocaleString("en-IN")}/year.`);await notify(request,"Your custom portal proposal is ready",`Review and accept ${p.proposalNumber} inside your JobiVerse portal workspace.`);refresh(p.id)}
export async function addMilestone(formData:FormData){const p=z.object({id:z.string().uuid(),title:z.string().trim().min(2).max(160),description:z.string().trim().max(1000),sequence:z.coerce.number().int().min(1).max(20),percentage:z.coerce.number().min(0).max(100),amount:z.coerce.number().nonnegative(),due:z.string(),status:z.enum(["pending","payment_due","paid","in_progress","completed","approved","waived"])}).parse({id:formData.get("id"),title:formData.get("title"),description:formData.get("description")??"",sequence:formData.get("sequence"),percentage:formData.get("percentage"),amount:formData.get("amount"),due:formData.get("due")??"",status:formData.get("status")});const{user,request}=await context(p.id);const{error}=await adminSupabase.from("custom_portal_milestones").upsert({request_id:p.id,title:p.title,description:p.description||null,sequence:p.sequence,percentage:p.percentage,amount:p.amount,due_date:p.due||null,status:p.status,updated_at:new Date().toISOString()},{onConflict:"request_id,sequence"});if(error)throw new Error(error.message);await timeline(p.id,user.id,"payment",`Milestone ${p.sequence}: ${p.title}`,`₹${p.amount.toLocaleString("en-IN")} · ${p.status.replaceAll("_"," ")}.`);await notify(request,"Custom portal milestone updated",`${p.title} is now ${p.status.replaceAll("_"," ")}.`);refresh(p.id)}
export async function addProjectUpdate(formData:FormData){const p=z.object({id:z.string().uuid(),type:z.enum(["system","discovery","scope","proposal","payment","progress","uat","delivery","support"]),title:z.string().trim().min(2).max(160),message:z.string().trim().max(5000),visible:z.boolean()}).parse({id:formData.get("id"),type:formData.get("type"),title:formData.get("title"),message:formData.get("message")??"",visible:formData.get("visible")==="on"});const{user,request}=await context(p.id);await timeline(p.id,user.id,p.type,p.title,p.message,p.visible);if(p.visible)await notify(request,p.title,p.message||"Your custom portal project has a new update.");refresh(p.id)}
export async function addProjectFile(formData:FormData){const p=z.object({id:z.string().uuid(),category:z.enum(["brief","scope","proposal","design","uat","training","delivery","other"]),title:z.string().trim().min(2).max(160),url:z.url(),visible:z.boolean()}).parse({id:formData.get("id"),category:formData.get("category"),title:formData.get("title"),url:formData.get("url"),visible:formData.get("visible")==="on"});const{user,request}=await context(p.id);await adminSupabase.from("custom_portal_files").insert({request_id:p.id,uploaded_by:user.id,category:p.category,title:p.title,file_url:p.url,visible_to_employer:p.visible});await timeline(p.id,user.id,"progress",`${p.title} added`,"A new project document is available.",p.visible);if(p.visible)await notify(request,"New custom portal document",`${p.title} is available in your project workspace.`);refresh(p.id)}
export async function advanceDelivery(formData:FormData){const p=z.object({id:z.string().uuid(),status,productionUrl:z.string().trim().max(500),supportUntil:z.string(),message:z.string().trim().max(5000)}).parse({id:formData.get("id"),status:formData.get("status"),productionUrl:formData.get("productionUrl")??"",supportUntil:formData.get("supportUntil")??"",message:formData.get("message")??""});const{user,request}=await context(p.id);const now=new Date().toISOString();const update:any={status:p.status,production_url:p.productionUrl||null,support_until:p.supportUntil||null,updated_at:now};if(p.status==="in_development")update.uat_submitted_at=p.message.toLowerCase().includes("uat")?now:undefined;if(p.status==="delivered")update.delivered_at=now;await adminSupabase.from("custom_portal_requests").update(update).eq("id",p.id);await timeline(p.id,user.id,p.status==="delivered"?"delivery":"progress",`Project moved to ${p.status.replaceAll("_"," ")}`,p.message);await notify(request,`Custom portal: ${p.status.replaceAll("_"," ")}`,p.message||"Your project status changed.");refresh(p.id)}
function refresh(id:string){revalidatePath(`/admin/custom-portals/${id}`);revalidatePath("/admin/custom-portals");revalidatePath(`/employers/custom-portal/requests/${id}`)}
